/*
 * This file is generated by jOOQ.
 */
package com.colombus.clan.jooq.tables.records;


import com.colombus.clan.jooq.tables.ClanInviteTicket;

import java.time.Instant;
import java.util.UUID;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ClanInviteTicketRecord extends UpdatableRecordImpl<ClanInviteTicketRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.clan_invite_ticket.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.clan_invite_ticket.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.clan_invite_ticket.clan_id</code>.
     */
    public void setClanId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.clan_invite_ticket.clan_id</code>.
     */
    public UUID getClanId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.clan_invite_ticket.code</code>.
     */
    public void setCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.clan_invite_ticket.code</code>.
     */
    public String getCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.clan_invite_ticket.created_by</code>.
     */
    public void setCreatedBy(UUID value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.clan_invite_ticket.created_by</code>.
     */
    public UUID getCreatedBy() {
        return (UUID) get(3);
    }

    /**
     * Setter for <code>public.clan_invite_ticket.max_uses</code>.
     */
    public void setMaxUses(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.clan_invite_ticket.max_uses</code>.
     */
    public Integer getMaxUses() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.clan_invite_ticket.use_count</code>.
     */
    public void setUseCount(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.clan_invite_ticket.use_count</code>.
     */
    public Integer getUseCount() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.clan_invite_ticket.expires_at</code>.
     */
    public void setExpiresAt(Instant value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.clan_invite_ticket.expires_at</code>.
     */
    public Instant getExpiresAt() {
        return (Instant) get(6);
    }

    /**
     * Setter for <code>public.clan_invite_ticket.is_revoked</code>.
     */
    public void setIsRevoked(Boolean value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.clan_invite_ticket.is_revoked</code>.
     */
    public Boolean getIsRevoked() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>public.clan_invite_ticket.metadata</code>.
     */
    public void setMetadata(JSONB value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.clan_invite_ticket.metadata</code>.
     */
    public JSONB getMetadata() {
        return (JSONB) get(8);
    }

    /**
     * Setter for <code>public.clan_invite_ticket.created_at</code>.
     */
    public void setCreatedAt(Instant value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.clan_invite_ticket.created_at</code>.
     */
    public Instant getCreatedAt() {
        return (Instant) get(9);
    }

    /**
     * Setter for <code>public.clan_invite_ticket.updated_at</code>.
     */
    public void setUpdatedAt(Instant value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.clan_invite_ticket.updated_at</code>.
     */
    public Instant getUpdatedAt() {
        return (Instant) get(10);
    }

    /**
     * Setter for <code>public.clan_invite_ticket.deleted_at</code>.
     */
    public void setDeletedAt(Instant value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.clan_invite_ticket.deleted_at</code>.
     */
    public Instant getDeletedAt() {
        return (Instant) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ClanInviteTicketRecord
     */
    public ClanInviteTicketRecord() {
        super(ClanInviteTicket.CLAN_INVITE_TICKET);
    }

    /**
     * Create a detached, initialised ClanInviteTicketRecord
     */
    public ClanInviteTicketRecord(UUID id, UUID clanId, String code, UUID createdBy, Integer maxUses, Integer useCount, Instant expiresAt, Boolean isRevoked, JSONB metadata, Instant createdAt, Instant updatedAt, Instant deletedAt) {
        super(ClanInviteTicket.CLAN_INVITE_TICKET);

        setId(id);
        setClanId(clanId);
        setCode(code);
        setCreatedBy(createdBy);
        setMaxUses(maxUses);
        setUseCount(useCount);
        setExpiresAt(expiresAt);
        setIsRevoked(isRevoked);
        setMetadata(metadata);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setDeletedAt(deletedAt);
        resetTouchedOnNotNull();
    }
}
