/*
 * This file is generated by jOOQ.
 */
package com.colombus.clan.jooq.tables.records;


import com.colombus.clan.jooq.tables.ClanMember;
import com.colombus.clan.model.type.ClanMemberRole;
import com.colombus.clan.model.type.ClanMemberStatus;

import java.time.Instant;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ClanMemberRecord extends UpdatableRecordImpl<ClanMemberRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.clan_member.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.clan_member.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.clan_member.clan_id</code>.
     */
    public void setClanId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.clan_member.clan_id</code>.
     */
    public UUID getClanId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.clan_member.user_id</code>.
     */
    public void setUserId(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.clan_member.user_id</code>.
     */
    public UUID getUserId() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>public.clan_member.role</code>.
     */
    public void setRole(ClanMemberRole value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.clan_member.role</code>.
     */
    public ClanMemberRole getRole() {
        return (ClanMemberRole) get(3);
    }

    /**
     * Setter for <code>public.clan_member.status</code>.
     */
    public void setStatus(ClanMemberStatus value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.clan_member.status</code>.
     */
    public ClanMemberStatus getStatus() {
        return (ClanMemberStatus) get(4);
    }

    /**
     * Setter for <code>public.clan_member.paint_count_total</code>.
     */
    public void setPaintCountTotal(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.clan_member.paint_count_total</code>.
     */
    public Long getPaintCountTotal() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.clan_member.joined_at</code>.
     */
    public void setJoinedAt(Instant value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.clan_member.joined_at</code>.
     */
    public Instant getJoinedAt() {
        return (Instant) get(6);
    }

    /**
     * Setter for <code>public.clan_member.left_at</code>.
     */
    public void setLeftAt(Instant value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.clan_member.left_at</code>.
     */
    public Instant getLeftAt() {
        return (Instant) get(7);
    }

    /**
     * Setter for <code>public.clan_member.created_at</code>.
     */
    public void setCreatedAt(Instant value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.clan_member.created_at</code>.
     */
    public Instant getCreatedAt() {
        return (Instant) get(8);
    }

    /**
     * Setter for <code>public.clan_member.updated_at</code>.
     */
    public void setUpdatedAt(Instant value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.clan_member.updated_at</code>.
     */
    public Instant getUpdatedAt() {
        return (Instant) get(9);
    }

    /**
     * Setter for <code>public.clan_member.deleted_at</code>.
     */
    public void setDeletedAt(Instant value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.clan_member.deleted_at</code>.
     */
    public Instant getDeletedAt() {
        return (Instant) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ClanMemberRecord
     */
    public ClanMemberRecord() {
        super(ClanMember.CLAN_MEMBER);
    }

    /**
     * Create a detached, initialised ClanMemberRecord
     */
    public ClanMemberRecord(UUID id, UUID clanId, UUID userId, ClanMemberRole role, ClanMemberStatus status, Long paintCountTotal, Instant joinedAt, Instant leftAt, Instant createdAt, Instant updatedAt, Instant deletedAt) {
        super(ClanMember.CLAN_MEMBER);

        setId(id);
        setClanId(clanId);
        setUserId(userId);
        setRole(role);
        setStatus(status);
        setPaintCountTotal(paintCountTotal);
        setJoinedAt(joinedAt);
        setLeftAt(leftAt);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setDeletedAt(deletedAt);
        resetTouchedOnNotNull();
    }
}
