/*
 * This file is generated by jOOQ.
 */
package com.colombus.clan.jooq.tables.records;


import com.colombus.clan.jooq.tables.ClanInfo;
import com.colombus.clan.model.type.ClanJoinPolicy;
import com.fasterxml.jackson.databind.JsonNode;

import java.time.Instant;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ClanInfoRecord extends UpdatableRecordImpl<ClanInfoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.clan_info.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.clan_info.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.clan_info.handle</code>.
     */
    public void setHandle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.clan_info.handle</code>.
     */
    public String getHandle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.clan_info.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.clan_info.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.clan_info.description</code>.
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.clan_info.description</code>.
     */
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.clan_info.owner_id</code>.
     */
    public void setOwnerId(UUID value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.clan_info.owner_id</code>.
     */
    public UUID getOwnerId() {
        return (UUID) get(4);
    }

    /**
     * Setter for <code>public.clan_info.join_policy</code>.
     */
    public void setJoinPolicy(ClanJoinPolicy value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.clan_info.join_policy</code>.
     */
    public ClanJoinPolicy getJoinPolicy() {
        return (ClanJoinPolicy) get(5);
    }

    /**
     * Setter for <code>public.clan_info.is_public</code>.
     */
    public void setIsPublic(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.clan_info.is_public</code>.
     */
    public Boolean getIsPublic() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>public.clan_info.member_count</code>.
     */
    public void setMemberCount(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.clan_info.member_count</code>.
     */
    public Integer getMemberCount() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>public.clan_info.paint_count_total</code>.
     */
    public void setPaintCountTotal(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.clan_info.paint_count_total</code>.
     */
    public Long getPaintCountTotal() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>public.clan_info.metadata</code>.
     */
    public void setMetadata(JsonNode value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.clan_info.metadata</code>.
     */
    public JsonNode getMetadata() {
        return (JsonNode) get(9);
    }

    /**
     * Setter for <code>public.clan_info.created_at</code>.
     */
    public void setCreatedAt(Instant value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.clan_info.created_at</code>.
     */
    public Instant getCreatedAt() {
        return (Instant) get(10);
    }

    /**
     * Setter for <code>public.clan_info.updated_at</code>.
     */
    public void setUpdatedAt(Instant value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.clan_info.updated_at</code>.
     */
    public Instant getUpdatedAt() {
        return (Instant) get(11);
    }

    /**
     * Setter for <code>public.clan_info.deleted_at</code>.
     */
    public void setDeletedAt(Instant value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.clan_info.deleted_at</code>.
     */
    public Instant getDeletedAt() {
        return (Instant) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ClanInfoRecord
     */
    public ClanInfoRecord() {
        super(ClanInfo.CLAN_INFO);
    }

    /**
     * Create a detached, initialised ClanInfoRecord
     */
    public ClanInfoRecord(UUID id, String handle, String name, String description, UUID ownerId, ClanJoinPolicy joinPolicy, Boolean isPublic, Integer memberCount, Long paintCountTotal, JsonNode metadata, Instant createdAt, Instant updatedAt, Instant deletedAt) {
        super(ClanInfo.CLAN_INFO);

        setId(id);
        setHandle(handle);
        setName(name);
        setDescription(description);
        setOwnerId(ownerId);
        setJoinPolicy(joinPolicy);
        setIsPublic(isPublic);
        setMemberCount(memberCount);
        setPaintCountTotal(paintCountTotal);
        setMetadata(metadata);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setDeletedAt(deletedAt);
        resetTouchedOnNotNull();
    }
}
