/*
 * This file is generated by jOOQ.
 */
package com.colombus.clan.jooq.tables.records;


import com.colombus.clan.jooq.tables.ClanJoinRequest;
import com.colombus.clan.model.type.ClanJoinRequestStatus;

import java.time.Instant;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ClanJoinRequestRecord extends UpdatableRecordImpl<ClanJoinRequestRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.clan_join_request.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.clan_join_request.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.clan_join_request.clan_id</code>.
     */
    public void setClanId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.clan_join_request.clan_id</code>.
     */
    public UUID getClanId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.clan_join_request.user_id</code>.
     */
    public void setUserId(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.clan_join_request.user_id</code>.
     */
    public UUID getUserId() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>public.clan_join_request.status</code>.
     */
    public void setStatus(ClanJoinRequestStatus value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.clan_join_request.status</code>.
     */
    public ClanJoinRequestStatus getStatus() {
        return (ClanJoinRequestStatus) get(3);
    }

    /**
     * Setter for <code>public.clan_join_request.message</code>.
     */
    public void setMessage(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.clan_join_request.message</code>.
     */
    public String getMessage() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.clan_join_request.reviewer_id</code>.
     */
    public void setReviewerId(UUID value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.clan_join_request.reviewer_id</code>.
     */
    public UUID getReviewerId() {
        return (UUID) get(5);
    }

    /**
     * Setter for <code>public.clan_join_request.decided_at</code>.
     */
    public void setDecidedAt(Instant value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.clan_join_request.decided_at</code>.
     */
    public Instant getDecidedAt() {
        return (Instant) get(6);
    }

    /**
     * Setter for <code>public.clan_join_request.created_at</code>.
     */
    public void setCreatedAt(Instant value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.clan_join_request.created_at</code>.
     */
    public Instant getCreatedAt() {
        return (Instant) get(7);
    }

    /**
     * Setter for <code>public.clan_join_request.updated_at</code>.
     */
    public void setUpdatedAt(Instant value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.clan_join_request.updated_at</code>.
     */
    public Instant getUpdatedAt() {
        return (Instant) get(8);
    }

    /**
     * Setter for <code>public.clan_join_request.deleted_at</code>.
     */
    public void setDeletedAt(Instant value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.clan_join_request.deleted_at</code>.
     */
    public Instant getDeletedAt() {
        return (Instant) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ClanJoinRequestRecord
     */
    public ClanJoinRequestRecord() {
        super(ClanJoinRequest.CLAN_JOIN_REQUEST);
    }

    /**
     * Create a detached, initialised ClanJoinRequestRecord
     */
    public ClanJoinRequestRecord(UUID id, UUID clanId, UUID userId, ClanJoinRequestStatus status, String message, UUID reviewerId, Instant decidedAt, Instant createdAt, Instant updatedAt, Instant deletedAt) {
        super(ClanJoinRequest.CLAN_JOIN_REQUEST);

        setId(id);
        setClanId(clanId);
        setUserId(userId);
        setStatus(status);
        setMessage(message);
        setReviewerId(reviewerId);
        setDecidedAt(decidedAt);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setDeletedAt(deletedAt);
        resetTouchedOnNotNull();
    }
}
