/*
 * This file is generated by jOOQ.
 */
package com.colombus.media.jooq.tables;


import com.colombus.common.kafka.subject.model.type.AssetPurpose;
import com.colombus.common.kafka.subject.model.type.SubjectKind;
import com.colombus.media.jooq.Indexes;
import com.colombus.media.jooq.Keys;
import com.colombus.media.jooq.Public;
import com.colombus.media.jooq.binding.AssetPurposeBinding;
import com.colombus.media.jooq.binding.SubjectKindBinding;
import com.colombus.media.jooq.tables.ImageAsset.ImageAssetPath;
import com.colombus.media.jooq.tables.SubjectRegistry.SubjectRegistryPath;
import com.colombus.media.jooq.tables.records.AssetLinkRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.DefaultDataType;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AssetLink extends TableImpl<AssetLinkRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.asset_link</code>
     */
    public static final AssetLink ASSET_LINK = new AssetLink();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AssetLinkRecord> getRecordType() {
        return AssetLinkRecord.class;
    }

    /**
     * The column <code>public.asset_link.id</code>.
     */
    public final TableField<AssetLinkRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.asset_link.subject_kind</code>.
     */
    public final TableField<AssetLinkRecord, SubjectKind> SUBJECT_KIND = createField(DSL.name("subject_kind"), DefaultDataType.getDefaultDataType("\"public\".\"subject_kind_enum\"").nullable(false), this, "", new SubjectKindBinding());

    /**
     * The column <code>public.asset_link.subject_id</code>.
     */
    public final TableField<AssetLinkRecord, UUID> SUBJECT_ID = createField(DSL.name("subject_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.asset_link.purpose</code>.
     */
    public final TableField<AssetLinkRecord, AssetPurpose> PURPOSE = createField(DSL.name("purpose"), DefaultDataType.getDefaultDataType("\"public\".\"asset_purpose_enum\"").nullable(false), this, "", new AssetPurposeBinding());

    /**
     * The column <code>public.asset_link.asset_id</code>.
     */
    public final TableField<AssetLinkRecord, UUID> ASSET_ID = createField(DSL.name("asset_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.asset_link.created_at</code>.
     */
    public final TableField<AssetLinkRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.asset_link.updated_at</code>.
     */
    public final TableField<AssetLinkRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.asset_link.deleted_at</code>.
     */
    public final TableField<AssetLinkRecord, OffsetDateTime> DELETED_AT = createField(DSL.name("deleted_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    private AssetLink(Name alias, Table<AssetLinkRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AssetLink(Name alias, Table<AssetLinkRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.asset_link</code> table reference
     */
    public AssetLink(String alias) {
        this(DSL.name(alias), ASSET_LINK);
    }

    /**
     * Create an aliased <code>public.asset_link</code> table reference
     */
    public AssetLink(Name alias) {
        this(alias, ASSET_LINK);
    }

    /**
     * Create a <code>public.asset_link</code> table reference
     */
    public AssetLink() {
        this(DSL.name("asset_link"), null);
    }

    public <O extends Record> AssetLink(Table<O> path, ForeignKey<O, AssetLinkRecord> childPath, InverseForeignKey<O, AssetLinkRecord> parentPath) {
        super(path, childPath, parentPath, ASSET_LINK);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class AssetLinkPath extends AssetLink implements Path<AssetLinkRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> AssetLinkPath(Table<O> path, ForeignKey<O, AssetLinkRecord> childPath, InverseForeignKey<O, AssetLinkRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private AssetLinkPath(Name alias, Table<AssetLinkRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public AssetLinkPath as(String alias) {
            return new AssetLinkPath(DSL.name(alias), this);
        }

        @Override
        public AssetLinkPath as(Name alias) {
            return new AssetLinkPath(alias, this);
        }

        @Override
        public AssetLinkPath as(Table<?> alias) {
            return new AssetLinkPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_ASSET_LINK_ASSET, Indexes.IDX_ASSET_LINK_SUBJECT, Indexes.UQ_ASSET_LINK_ACTIVE_ONE_PER_SUBJECT_PURPOSE);
    }

    @Override
    public UniqueKey<AssetLinkRecord> getPrimaryKey() {
        return Keys.ASSET_LINK_PKEY;
    }

    @Override
    public List<ForeignKey<AssetLinkRecord, ?>> getReferences() {
        return Arrays.asList(Keys.ASSET_LINK__ASSET_LINK_ASSET_ID_FKEY, Keys.ASSET_LINK__FK_ASSET_LINK_SUBJECT);
    }

    private transient ImageAssetPath _imageAsset;

    /**
     * Get the implicit join path to the <code>public.image_asset</code> table.
     */
    public ImageAssetPath imageAsset() {
        if (_imageAsset == null)
            _imageAsset = new ImageAssetPath(this, Keys.ASSET_LINK__ASSET_LINK_ASSET_ID_FKEY, null);

        return _imageAsset;
    }

    private transient SubjectRegistryPath _subjectRegistry;

    /**
     * Get the implicit join path to the <code>public.subject_registry</code>
     * table.
     */
    public SubjectRegistryPath subjectRegistry() {
        if (_subjectRegistry == null)
            _subjectRegistry = new SubjectRegistryPath(this, Keys.ASSET_LINK__FK_ASSET_LINK_SUBJECT, null);

        return _subjectRegistry;
    }

    @Override
    public TableField<AssetLinkRecord, OffsetDateTime> getRecordTimestamp() {
        return UPDATED_AT;
    }

    @Override
    public AssetLink as(String alias) {
        return new AssetLink(DSL.name(alias), this);
    }

    @Override
    public AssetLink as(Name alias) {
        return new AssetLink(alias, this);
    }

    @Override
    public AssetLink as(Table<?> alias) {
        return new AssetLink(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AssetLink rename(String name) {
        return new AssetLink(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AssetLink rename(Name name) {
        return new AssetLink(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AssetLink rename(Table<?> name) {
        return new AssetLink(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AssetLink where(Condition condition) {
        return new AssetLink(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AssetLink where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AssetLink where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AssetLink where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AssetLink where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AssetLink where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AssetLink where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AssetLink where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AssetLink whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AssetLink whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
