/*
 * This file is generated by jOOQ.
 */
package com.colombus.media.jooq.tables;


import com.colombus.common.jooq.JsonNodeConverter;
import com.colombus.media.jooq.Indexes;
import com.colombus.media.jooq.Keys;
import com.colombus.media.jooq.Public;
import com.colombus.media.jooq.tables.AssetLink.AssetLinkPath;
import com.colombus.media.jooq.tables.records.ImageAssetRecord;
import com.fasterxml.jackson.databind.JsonNode;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ImageAsset extends TableImpl<ImageAssetRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.image_asset</code>
     */
    public static final ImageAsset IMAGE_ASSET = new ImageAsset();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ImageAssetRecord> getRecordType() {
        return ImageAssetRecord.class;
    }

    /**
     * The column <code>public.image_asset.id</code>.
     */
    public final TableField<ImageAssetRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.image_asset.raw_sha256</code>.
     */
    public final TableField<ImageAssetRecord, String> RAW_SHA256 = createField(DSL.name("raw_sha256"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>public.image_asset.content_sha256</code>.
     */
    public final TableField<ImageAssetRecord, String> CONTENT_SHA256 = createField(DSL.name("content_sha256"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>public.image_asset.content_type</code>.
     */
    public final TableField<ImageAssetRecord, String> CONTENT_TYPE = createField(DSL.name("content_type"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.image_asset.width</code>.
     */
    public final TableField<ImageAssetRecord, Integer> WIDTH = createField(DSL.name("width"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.image_asset.height</code>.
     */
    public final TableField<ImageAssetRecord, Integer> HEIGHT = createField(DSL.name("height"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.image_asset.size_bytes</code>.
     */
    public final TableField<ImageAssetRecord, Long> SIZE_BYTES = createField(DSL.name("size_bytes"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.image_asset.storage_bucket</code>.
     */
    public final TableField<ImageAssetRecord, String> STORAGE_BUCKET = createField(DSL.name("storage_bucket"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.image_asset.storage_key</code>.
     */
    public final TableField<ImageAssetRecord, String> STORAGE_KEY = createField(DSL.name("storage_key"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.image_asset.public_url</code>.
     */
    public final TableField<ImageAssetRecord, String> PUBLIC_URL = createField(DSL.name("public_url"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.image_asset.exif</code>.
     */
    public final TableField<ImageAssetRecord, JsonNode> EXIF = createField(DSL.name("exif"), SQLDataType.JSONB.nullable(false).defaultValue(DSL.field(DSL.raw("'{}'::jsonb"), SQLDataType.JSONB)), this, "", new JsonNodeConverter());

    /**
     * The column <code>public.image_asset.is_active</code>.
     */
    public final TableField<ImageAssetRecord, Boolean> IS_ACTIVE = createField(DSL.name("is_active"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.image_asset.blocked_at</code>.
     */
    public final TableField<ImageAssetRecord, OffsetDateTime> BLOCKED_AT = createField(DSL.name("blocked_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.image_asset.blocked_reason</code>.
     */
    public final TableField<ImageAssetRecord, String> BLOCKED_REASON = createField(DSL.name("blocked_reason"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.image_asset.created_at</code>.
     */
    public final TableField<ImageAssetRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.image_asset.updated_at</code>.
     */
    public final TableField<ImageAssetRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.image_asset.deleted_at</code>.
     */
    public final TableField<ImageAssetRecord, OffsetDateTime> DELETED_AT = createField(DSL.name("deleted_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    private ImageAsset(Name alias, Table<ImageAssetRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ImageAsset(Name alias, Table<ImageAssetRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.image_asset</code> table reference
     */
    public ImageAsset(String alias) {
        this(DSL.name(alias), IMAGE_ASSET);
    }

    /**
     * Create an aliased <code>public.image_asset</code> table reference
     */
    public ImageAsset(Name alias) {
        this(alias, IMAGE_ASSET);
    }

    /**
     * Create a <code>public.image_asset</code> table reference
     */
    public ImageAsset() {
        this(DSL.name("image_asset"), null);
    }

    public <O extends Record> ImageAsset(Table<O> path, ForeignKey<O, ImageAssetRecord> childPath, InverseForeignKey<O, ImageAssetRecord> parentPath) {
        super(path, childPath, parentPath, IMAGE_ASSET);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ImageAssetPath extends ImageAsset implements Path<ImageAssetRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ImageAssetPath(Table<O> path, ForeignKey<O, ImageAssetRecord> childPath, InverseForeignKey<O, ImageAssetRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ImageAssetPath(Name alias, Table<ImageAssetRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ImageAssetPath as(String alias) {
            return new ImageAssetPath(DSL.name(alias), this);
        }

        @Override
        public ImageAssetPath as(Name alias) {
            return new ImageAssetPath(alias, this);
        }

        @Override
        public ImageAssetPath as(Table<?> alias) {
            return new ImageAssetPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_IMAGE_ASSET_ACTIVE, Indexes.IDX_IMAGE_ASSET_CONTENT_SHA256, Indexes.IDX_IMAGE_ASSET_CREATED_AT);
    }

    @Override
    public UniqueKey<ImageAssetRecord> getPrimaryKey() {
        return Keys.IMAGE_ASSET_PKEY;
    }

    @Override
    public List<UniqueKey<ImageAssetRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UQ_IMAGE_ASSET_RAW);
    }

    private transient AssetLinkPath _assetLink;

    /**
     * Get the implicit to-many join path to the <code>public.asset_link</code>
     * table
     */
    public AssetLinkPath assetLink() {
        if (_assetLink == null)
            _assetLink = new AssetLinkPath(this, null, Keys.ASSET_LINK__ASSET_LINK_ASSET_ID_FKEY.getInverseKey());

        return _assetLink;
    }

    @Override
    public List<Check<ImageAssetRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("chk_deleted_means_inactive_img"), "(((deleted_at IS NULL) OR (is_active = false)))", true),
            Internal.createCheck(this, DSL.name("chk_image_content_type_whitelist"), "((content_type = ANY (ARRAY['image/jpeg'::text, 'image/png'::text, 'image/webp'::text])))", true),
            Internal.createCheck(this, DSL.name("chk_image_dims_positive"), "(((width > 0) AND (height > 0)))", true),
            Internal.createCheck(this, DSL.name("chk_image_size_le_5mb"), "(((size_bytes > 0) AND (size_bytes <= ((5 * 1024) * 1024))))", true),
            Internal.createCheck(this, DSL.name("chk_sha256_hex"), "((((raw_sha256)::text ~ '^[0-9a-f]{64}$'::text) AND ((content_sha256)::text ~ '^[0-9a-f]{64}$'::text)))", true)
        );
    }

    @Override
    public TableField<ImageAssetRecord, OffsetDateTime> getRecordTimestamp() {
        return UPDATED_AT;
    }

    @Override
    public ImageAsset as(String alias) {
        return new ImageAsset(DSL.name(alias), this);
    }

    @Override
    public ImageAsset as(Name alias) {
        return new ImageAsset(alias, this);
    }

    @Override
    public ImageAsset as(Table<?> alias) {
        return new ImageAsset(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ImageAsset rename(String name) {
        return new ImageAsset(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ImageAsset rename(Name name) {
        return new ImageAsset(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ImageAsset rename(Table<?> name) {
        return new ImageAsset(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ImageAsset where(Condition condition) {
        return new ImageAsset(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ImageAsset where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ImageAsset where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ImageAsset where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ImageAsset where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ImageAsset where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ImageAsset where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ImageAsset where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ImageAsset whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ImageAsset whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
