/*
 * This file is generated by jOOQ.
 */
package com.colombus.media.jooq.tables;


import com.colombus.common.kafka.subject.model.type.AssetPurpose;
import com.colombus.common.kafka.subject.model.type.SubjectKind;
import com.colombus.media.jooq.Indexes;
import com.colombus.media.jooq.Keys;
import com.colombus.media.jooq.Public;
import com.colombus.media.jooq.binding.AssetPurposeBinding;
import com.colombus.media.jooq.binding.SubjectKindBinding;
import com.colombus.media.jooq.tables.SubjectRegistry.SubjectRegistryPath;
import com.colombus.media.jooq.tables.records.StagingUploadTicketRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.DefaultDataType;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class StagingUploadTicket extends TableImpl<StagingUploadTicketRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.staging_upload_ticket</code>
     */
    public static final StagingUploadTicket STAGING_UPLOAD_TICKET = new StagingUploadTicket();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StagingUploadTicketRecord> getRecordType() {
        return StagingUploadTicketRecord.class;
    }

    /**
     * The column <code>public.staging_upload_ticket.asset_id</code>.
     */
    public final TableField<StagingUploadTicketRecord, UUID> ASSET_ID = createField(DSL.name("asset_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.staging_upload_ticket.subject_kind</code>.
     */
    public final TableField<StagingUploadTicketRecord, SubjectKind> SUBJECT_KIND = createField(DSL.name("subject_kind"), DefaultDataType.getDefaultDataType("\"public\".\"subject_kind_enum\"").nullable(false), this, "", new SubjectKindBinding());

    /**
     * The column <code>public.staging_upload_ticket.subject_id</code>.
     */
    public final TableField<StagingUploadTicketRecord, UUID> SUBJECT_ID = createField(DSL.name("subject_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.staging_upload_ticket.purpose</code>.
     */
    public final TableField<StagingUploadTicketRecord, AssetPurpose> PURPOSE = createField(DSL.name("purpose"), DefaultDataType.getDefaultDataType("\"public\".\"asset_purpose_enum\"").nullable(false), this, "", new AssetPurposeBinding());

    /**
     * The column <code>public.staging_upload_ticket.s3_key</code>.
     */
    public final TableField<StagingUploadTicketRecord, String> S3_KEY = createField(DSL.name("s3_key"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.staging_upload_ticket.expires_at</code>.
     */
    public final TableField<StagingUploadTicketRecord, OffsetDateTime> EXPIRES_AT = createField(DSL.name("expires_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.staging_upload_ticket.status</code>.
     */
    public final TableField<StagingUploadTicketRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.CLOB.nullable(false).defaultValue(DSL.field(DSL.raw("'PENDING'::text"), SQLDataType.CLOB)), this, "");

    /**
     * The column <code>public.staging_upload_ticket.created_at</code>.
     */
    public final TableField<StagingUploadTicketRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.staging_upload_ticket.updated_at</code>.
     */
    public final TableField<StagingUploadTicketRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.staging_upload_ticket.used_at</code>.
     */
    public final TableField<StagingUploadTicketRecord, OffsetDateTime> USED_AT = createField(DSL.name("used_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    private StagingUploadTicket(Name alias, Table<StagingUploadTicketRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private StagingUploadTicket(Name alias, Table<StagingUploadTicketRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.staging_upload_ticket</code> table
     * reference
     */
    public StagingUploadTicket(String alias) {
        this(DSL.name(alias), STAGING_UPLOAD_TICKET);
    }

    /**
     * Create an aliased <code>public.staging_upload_ticket</code> table
     * reference
     */
    public StagingUploadTicket(Name alias) {
        this(alias, STAGING_UPLOAD_TICKET);
    }

    /**
     * Create a <code>public.staging_upload_ticket</code> table reference
     */
    public StagingUploadTicket() {
        this(DSL.name("staging_upload_ticket"), null);
    }

    public <O extends Record> StagingUploadTicket(Table<O> path, ForeignKey<O, StagingUploadTicketRecord> childPath, InverseForeignKey<O, StagingUploadTicketRecord> parentPath) {
        super(path, childPath, parentPath, STAGING_UPLOAD_TICKET);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class StagingUploadTicketPath extends StagingUploadTicket implements Path<StagingUploadTicketRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> StagingUploadTicketPath(Table<O> path, ForeignKey<O, StagingUploadTicketRecord> childPath, InverseForeignKey<O, StagingUploadTicketRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private StagingUploadTicketPath(Name alias, Table<StagingUploadTicketRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public StagingUploadTicketPath as(String alias) {
            return new StagingUploadTicketPath(DSL.name(alias), this);
        }

        @Override
        public StagingUploadTicketPath as(Name alias) {
            return new StagingUploadTicketPath(alias, this);
        }

        @Override
        public StagingUploadTicketPath as(Table<?> alias) {
            return new StagingUploadTicketPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_STAGING_TICKET_EXPIRES, Indexes.IDX_STAGING_TICKET_SUBJECT);
    }

    @Override
    public UniqueKey<StagingUploadTicketRecord> getPrimaryKey() {
        return Keys.STAGING_UPLOAD_TICKET_PKEY;
    }

    @Override
    public List<ForeignKey<StagingUploadTicketRecord, ?>> getReferences() {
        return Arrays.asList(Keys.STAGING_UPLOAD_TICKET__FK_STAGING_SUBJECT);
    }

    private transient SubjectRegistryPath _subjectRegistry;

    /**
     * Get the implicit join path to the <code>public.subject_registry</code>
     * table.
     */
    public SubjectRegistryPath subjectRegistry() {
        if (_subjectRegistry == null)
            _subjectRegistry = new SubjectRegistryPath(this, Keys.STAGING_UPLOAD_TICKET__FK_STAGING_SUBJECT, null);

        return _subjectRegistry;
    }

    @Override
    public List<Check<StagingUploadTicketRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("chk_staging_status"), "((status = ANY (ARRAY['PENDING'::text, 'USED'::text, 'EXPIRED'::text])))", true)
        );
    }

    @Override
    public TableField<StagingUploadTicketRecord, OffsetDateTime> getRecordTimestamp() {
        return UPDATED_AT;
    }

    @Override
    public StagingUploadTicket as(String alias) {
        return new StagingUploadTicket(DSL.name(alias), this);
    }

    @Override
    public StagingUploadTicket as(Name alias) {
        return new StagingUploadTicket(alias, this);
    }

    @Override
    public StagingUploadTicket as(Table<?> alias) {
        return new StagingUploadTicket(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public StagingUploadTicket rename(String name) {
        return new StagingUploadTicket(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public StagingUploadTicket rename(Name name) {
        return new StagingUploadTicket(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public StagingUploadTicket rename(Table<?> name) {
        return new StagingUploadTicket(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StagingUploadTicket where(Condition condition) {
        return new StagingUploadTicket(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StagingUploadTicket where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StagingUploadTicket where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StagingUploadTicket where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public StagingUploadTicket where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public StagingUploadTicket where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public StagingUploadTicket where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public StagingUploadTicket where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StagingUploadTicket whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public StagingUploadTicket whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
