/*
 * This file is generated by jOOQ.
 */
package com.colombus.media.jooq.tables;


import com.colombus.common.kafka.subject.model.type.SubjectKind;
import com.colombus.media.jooq.Indexes;
import com.colombus.media.jooq.Keys;
import com.colombus.media.jooq.Public;
import com.colombus.media.jooq.binding.SubjectKindBinding;
import com.colombus.media.jooq.tables.AssetLink.AssetLinkPath;
import com.colombus.media.jooq.tables.StagingUploadTicket.StagingUploadTicketPath;
import com.colombus.media.jooq.tables.records.SubjectRegistryRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.DefaultDataType;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SubjectRegistry extends TableImpl<SubjectRegistryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.subject_registry</code>
     */
    public static final SubjectRegistry SUBJECT_REGISTRY = new SubjectRegistry();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SubjectRegistryRecord> getRecordType() {
        return SubjectRegistryRecord.class;
    }

    /**
     * The column <code>public.subject_registry.kind</code>.
     */
    public final TableField<SubjectRegistryRecord, SubjectKind> KIND = createField(DSL.name("kind"), DefaultDataType.getDefaultDataType("\"public\".\"subject_kind_enum\"").nullable(false), this, "", new SubjectKindBinding());

    /**
     * The column <code>public.subject_registry.subject_id</code>.
     */
    public final TableField<SubjectRegistryRecord, UUID> SUBJECT_ID = createField(DSL.name("subject_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.subject_registry.alive</code>.
     */
    public final TableField<SubjectRegistryRecord, Boolean> ALIVE = createField(DSL.name("alive"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.subject_registry.created_at</code>.
     */
    public final TableField<SubjectRegistryRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.subject_registry.updated_at</code>.
     */
    public final TableField<SubjectRegistryRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private SubjectRegistry(Name alias, Table<SubjectRegistryRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private SubjectRegistry(Name alias, Table<SubjectRegistryRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.subject_registry</code> table reference
     */
    public SubjectRegistry(String alias) {
        this(DSL.name(alias), SUBJECT_REGISTRY);
    }

    /**
     * Create an aliased <code>public.subject_registry</code> table reference
     */
    public SubjectRegistry(Name alias) {
        this(alias, SUBJECT_REGISTRY);
    }

    /**
     * Create a <code>public.subject_registry</code> table reference
     */
    public SubjectRegistry() {
        this(DSL.name("subject_registry"), null);
    }

    public <O extends Record> SubjectRegistry(Table<O> path, ForeignKey<O, SubjectRegistryRecord> childPath, InverseForeignKey<O, SubjectRegistryRecord> parentPath) {
        super(path, childPath, parentPath, SUBJECT_REGISTRY);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class SubjectRegistryPath extends SubjectRegistry implements Path<SubjectRegistryRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> SubjectRegistryPath(Table<O> path, ForeignKey<O, SubjectRegistryRecord> childPath, InverseForeignKey<O, SubjectRegistryRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private SubjectRegistryPath(Name alias, Table<SubjectRegistryRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public SubjectRegistryPath as(String alias) {
            return new SubjectRegistryPath(DSL.name(alias), this);
        }

        @Override
        public SubjectRegistryPath as(Name alias) {
            return new SubjectRegistryPath(alias, this);
        }

        @Override
        public SubjectRegistryPath as(Table<?> alias) {
            return new SubjectRegistryPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_SUBJECT_REGISTRY_KIND_ALIVE);
    }

    @Override
    public UniqueKey<SubjectRegistryRecord> getPrimaryKey() {
        return Keys.SUBJECT_REGISTRY_PKEY;
    }

    private transient AssetLinkPath _assetLink;

    /**
     * Get the implicit to-many join path to the <code>public.asset_link</code>
     * table
     */
    public AssetLinkPath assetLink() {
        if (_assetLink == null)
            _assetLink = new AssetLinkPath(this, null, Keys.ASSET_LINK__FK_ASSET_LINK_SUBJECT.getInverseKey());

        return _assetLink;
    }

    private transient StagingUploadTicketPath _stagingUploadTicket;

    /**
     * Get the implicit to-many join path to the
     * <code>public.staging_upload_ticket</code> table
     */
    public StagingUploadTicketPath stagingUploadTicket() {
        if (_stagingUploadTicket == null)
            _stagingUploadTicket = new StagingUploadTicketPath(this, null, Keys.STAGING_UPLOAD_TICKET__FK_STAGING_SUBJECT.getInverseKey());

        return _stagingUploadTicket;
    }

    @Override
    public TableField<SubjectRegistryRecord, OffsetDateTime> getRecordTimestamp() {
        return UPDATED_AT;
    }

    @Override
    public SubjectRegistry as(String alias) {
        return new SubjectRegistry(DSL.name(alias), this);
    }

    @Override
    public SubjectRegistry as(Name alias) {
        return new SubjectRegistry(alias, this);
    }

    @Override
    public SubjectRegistry as(Table<?> alias) {
        return new SubjectRegistry(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public SubjectRegistry rename(String name) {
        return new SubjectRegistry(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SubjectRegistry rename(Name name) {
        return new SubjectRegistry(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public SubjectRegistry rename(Table<?> name) {
        return new SubjectRegistry(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SubjectRegistry where(Condition condition) {
        return new SubjectRegistry(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SubjectRegistry where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SubjectRegistry where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SubjectRegistry where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SubjectRegistry where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SubjectRegistry where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SubjectRegistry where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SubjectRegistry where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SubjectRegistry whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SubjectRegistry whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
