/*
 * This file is generated by jOOQ.
 */
package com.colombus.user.jooq.tables.records;


import com.colombus.user.jooq.tables.AuthEvent;
import com.colombus.user.model.type.AuthEventKind;
import com.colombus.user.model.type.AuthProvider;

import java.time.Instant;
import java.util.UUID;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.postgres.extensions.types.Inet;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AuthEventRecord extends UpdatableRecordImpl<AuthEventRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.auth_event.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.auth_event.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.auth_event.user_id</code>.
     */
    public void setUserId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.auth_event.user_id</code>.
     */
    public UUID getUserId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.auth_event.provider</code>.
     */
    public void setProvider(AuthProvider value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.auth_event.provider</code>.
     */
    public AuthProvider getProvider() {
        return (AuthProvider) get(2);
    }

    /**
     * Setter for <code>public.auth_event.kind</code>.
     */
    public void setKind(AuthEventKind value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.auth_event.kind</code>.
     */
    public AuthEventKind getKind() {
        return (AuthEventKind) get(3);
    }

    /**
     * Setter for <code>public.auth_event.detail</code>.
     */
    public void setDetail(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.auth_event.detail</code>.
     */
    public String getDetail() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.auth_event.ip_addr</code>.
     */
    public void setIpAddr(Inet value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.auth_event.ip_addr</code>.
     */
    public Inet getIpAddr() {
        return (Inet) get(5);
    }

    /**
     * Setter for <code>public.auth_event.user_agent</code>.
     */
    public void setUserAgent(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.auth_event.user_agent</code>.
     */
    public String getUserAgent() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.auth_event.created_at</code>.
     */
    public void setCreatedAt(Instant value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.auth_event.created_at</code>.
     */
    public Instant getCreatedAt() {
        return (Instant) get(7);
    }

    /**
     * Setter for <code>public.auth_event.updated_at</code>.
     */
    public void setUpdatedAt(Instant value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.auth_event.updated_at</code>.
     */
    public Instant getUpdatedAt() {
        return (Instant) get(8);
    }

    /**
     * Setter for <code>public.auth_event.deleted_at</code>.
     */
    public void setDeletedAt(Instant value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.auth_event.deleted_at</code>.
     */
    public Instant getDeletedAt() {
        return (Instant) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<UUID, Instant> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AuthEventRecord
     */
    public AuthEventRecord() {
        super(AuthEvent.AUTH_EVENT);
    }

    /**
     * Create a detached, initialised AuthEventRecord
     */
    public AuthEventRecord(UUID id, UUID userId, AuthProvider provider, AuthEventKind kind, String detail, Inet ipAddr, String userAgent, Instant createdAt, Instant updatedAt, Instant deletedAt) {
        super(AuthEvent.AUTH_EVENT);

        setId(id);
        setUserId(userId);
        setProvider(provider);
        setKind(kind);
        setDetail(detail);
        setIpAddr(ipAddr);
        setUserAgent(userAgent);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setDeletedAt(deletedAt);
        resetTouchedOnNotNull();
    }
}
