/*
 * This file is generated by jOOQ.
 */
package com.colombus.user.jooq.tables.records;


import com.colombus.user.jooq.tables.NicknameSeries;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class NicknameSeriesRecord extends UpdatableRecordImpl<NicknameSeriesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.nickname_series.nickname</code>.
     */
    public void setNickname(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.nickname_series.nickname</code>.
     */
    public String getNickname() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.nickname_series.next_seq</code>.
     */
    public void setNextSeq(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.nickname_series.next_seq</code>.
     */
    public Integer getNextSeq() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NicknameSeriesRecord
     */
    public NicknameSeriesRecord() {
        super(NicknameSeries.NICKNAME_SERIES);
    }

    /**
     * Create a detached, initialised NicknameSeriesRecord
     */
    public NicknameSeriesRecord(String nickname, Integer nextSeq) {
        super(NicknameSeries.NICKNAME_SERIES);

        setNickname(nickname);
        setNextSeq(nextSeq);
        resetTouchedOnNotNull();
    }
}
