/*
 * This file is generated by jOOQ.
 */
package com.colombus.user.jooq.tables.records;


import com.colombus.common.domain.outbox.model.type.OutboxStatus;
import com.colombus.user.jooq.tables.OutboxEvent;
import com.fasterxml.jackson.databind.JsonNode;

import java.time.Instant;
import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OutboxEventRecord extends UpdatableRecordImpl<OutboxEventRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.outbox_event.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.outbox_event.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.outbox_event.aggregate</code>.
     */
    public void setAggregate(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.outbox_event.aggregate</code>.
     */
    public String getAggregate() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.outbox_event.aggregate_id</code>.
     */
    public void setAggregateId(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.outbox_event.aggregate_id</code>.
     */
    public UUID getAggregateId() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>public.outbox_event.type</code>.
     */
    public void setType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.outbox_event.type</code>.
     */
    public String getType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.outbox_event.version</code>.
     */
    public void setVersion(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.outbox_event.version</code>.
     */
    public Long getVersion() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.outbox_event.payload</code>.
     */
    public void setPayload(JsonNode value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.outbox_event.payload</code>.
     */
    public JsonNode getPayload() {
        return (JsonNode) get(5);
    }

    /**
     * Setter for <code>public.outbox_event.headers</code>.
     */
    public void setHeaders(JsonNode value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.outbox_event.headers</code>.
     */
    public JsonNode getHeaders() {
        return (JsonNode) get(6);
    }

    /**
     * Setter for <code>public.outbox_event.status</code>.
     */
    public void setStatus(OutboxStatus value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.outbox_event.status</code>.
     */
    public OutboxStatus getStatus() {
        return (OutboxStatus) get(7);
    }

    /**
     * Setter for <code>public.outbox_event.attempts</code>.
     */
    public void setAttempts(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.outbox_event.attempts</code>.
     */
    public Integer getAttempts() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>public.outbox_event.last_error</code>.
     */
    public void setLastError(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.outbox_event.last_error</code>.
     */
    public String getLastError() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.outbox_event.next_attempt_at</code>.
     */
    public void setNextAttemptAt(Instant value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.outbox_event.next_attempt_at</code>.
     */
    public Instant getNextAttemptAt() {
        return (Instant) get(10);
    }

    /**
     * Setter for <code>public.outbox_event.locked_by</code>.
     */
    public void setLockedBy(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.outbox_event.locked_by</code>.
     */
    public String getLockedBy() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.outbox_event.locked_until</code>.
     */
    public void setLockedUntil(OffsetDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.outbox_event.locked_until</code>.
     */
    public OffsetDateTime getLockedUntil() {
        return (OffsetDateTime) get(12);
    }

    /**
     * Setter for <code>public.outbox_event.created_at</code>.
     */
    public void setCreatedAt(Instant value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.outbox_event.created_at</code>.
     */
    public Instant getCreatedAt() {
        return (Instant) get(13);
    }

    /**
     * Setter for <code>public.outbox_event.updated_at</code>.
     */
    public void setUpdatedAt(Instant value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.outbox_event.updated_at</code>.
     */
    public Instant getUpdatedAt() {
        return (Instant) get(14);
    }

    /**
     * Setter for <code>public.outbox_event.published_at</code>.
     */
    public void setPublishedAt(Instant value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.outbox_event.published_at</code>.
     */
    public Instant getPublishedAt() {
        return (Instant) get(15);
    }

    /**
     * Setter for <code>public.outbox_event.deleted_at</code>.
     */
    public void setDeletedAt(Instant value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.outbox_event.deleted_at</code>.
     */
    public Instant getDeletedAt() {
        return (Instant) get(16);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OutboxEventRecord
     */
    public OutboxEventRecord() {
        super(OutboxEvent.OUTBOX_EVENT);
    }

    /**
     * Create a detached, initialised OutboxEventRecord
     */
    public OutboxEventRecord(UUID id, String aggregate, UUID aggregateId, String type, Long version, JsonNode payload, JsonNode headers, OutboxStatus status, Integer attempts, String lastError, Instant nextAttemptAt, String lockedBy, OffsetDateTime lockedUntil, Instant createdAt, Instant updatedAt, Instant publishedAt, Instant deletedAt) {
        super(OutboxEvent.OUTBOX_EVENT);

        setId(id);
        setAggregate(aggregate);
        setAggregateId(aggregateId);
        setType(type);
        setVersion(version);
        setPayload(payload);
        setHeaders(headers);
        setStatus(status);
        setAttempts(attempts);
        setLastError(lastError);
        setNextAttemptAt(nextAttemptAt);
        setLockedBy(lockedBy);
        setLockedUntil(lockedUntil);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setPublishedAt(publishedAt);
        setDeletedAt(deletedAt);
        resetTouchedOnNotNull();
    }
}
