/*
 * This file is generated by jOOQ.
 */
package com.colombus.user.jooq.tables.records;


import com.colombus.user.jooq.tables.UserIdentity;
import com.colombus.user.model.type.AuthProvider;

import java.time.Instant;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserIdentityRecord extends UpdatableRecordImpl<UserIdentityRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.user_identity.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.user_identity.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.user_identity.user_id</code>.
     */
    public void setUserId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.user_identity.user_id</code>.
     */
    public UUID getUserId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.user_identity.provider</code>.
     */
    public void setProvider(AuthProvider value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.user_identity.provider</code>.
     */
    public AuthProvider getProvider() {
        return (AuthProvider) get(2);
    }

    /**
     * Setter for <code>public.user_identity.provider_tenant</code>.
     */
    public void setProviderTenant(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.user_identity.provider_tenant</code>.
     */
    public String getProviderTenant() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.user_identity.provider_sub</code>.
     */
    public void setProviderSub(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.user_identity.provider_sub</code>.
     */
    public String getProviderSub() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.user_identity.email_at_provider</code>.
     */
    public void setEmailAtProvider(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.user_identity.email_at_provider</code>.
     */
    public String getEmailAtProvider() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.user_identity.display_name_at_provider</code>.
     */
    public void setDisplayNameAtProvider(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.user_identity.display_name_at_provider</code>.
     */
    public String getDisplayNameAtProvider() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.user_identity.last_sync_at</code>.
     */
    public void setLastSyncAt(Instant value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.user_identity.last_sync_at</code>.
     */
    public Instant getLastSyncAt() {
        return (Instant) get(7);
    }

    /**
     * Setter for <code>public.user_identity.created_at</code>.
     */
    public void setCreatedAt(Instant value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.user_identity.created_at</code>.
     */
    public Instant getCreatedAt() {
        return (Instant) get(8);
    }

    /**
     * Setter for <code>public.user_identity.updated_at</code>.
     */
    public void setUpdatedAt(Instant value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.user_identity.updated_at</code>.
     */
    public Instant getUpdatedAt() {
        return (Instant) get(9);
    }

    /**
     * Setter for <code>public.user_identity.deleted_at</code>.
     */
    public void setDeletedAt(Instant value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.user_identity.deleted_at</code>.
     */
    public Instant getDeletedAt() {
        return (Instant) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserIdentityRecord
     */
    public UserIdentityRecord() {
        super(UserIdentity.USER_IDENTITY);
    }

    /**
     * Create a detached, initialised UserIdentityRecord
     */
    public UserIdentityRecord(UUID id, UUID userId, AuthProvider provider, String providerTenant, String providerSub, String emailAtProvider, String displayNameAtProvider, Instant lastSyncAt, Instant createdAt, Instant updatedAt, Instant deletedAt) {
        super(UserIdentity.USER_IDENTITY);

        setId(id);
        setUserId(userId);
        setProvider(provider);
        setProviderTenant(providerTenant);
        setProviderSub(providerSub);
        setEmailAtProvider(emailAtProvider);
        setDisplayNameAtProvider(displayNameAtProvider);
        setLastSyncAt(lastSyncAt);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setDeletedAt(deletedAt);
        resetTouchedOnNotNull();
    }
}
