/*
 * This file is generated by jOOQ.
 */
package com.colombus.user.jooq.tables.records;


import com.colombus.user.jooq.tables.UserAccount;
import com.colombus.user.model.type.AccountRole;
import com.fasterxml.jackson.databind.JsonNode;

import java.time.Instant;
import java.util.List;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserAccountRecord extends UpdatableRecordImpl<UserAccountRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.user_account.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.user_account.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.user_account.email</code>.
     */
    public void setEmail(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.user_account.email</code>.
     */
    public String getEmail() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.user_account.nickname</code>.
     */
    public void setNickname(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.user_account.nickname</code>.
     */
    public String getNickname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.user_account.nickname_seq</code>.
     */
    public void setNicknameSeq(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.user_account.nickname_seq</code>.
     */
    public Integer getNicknameSeq() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.user_account.nickname_handle</code>.
     */
    public void setNicknameHandle(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.user_account.nickname_handle</code>.
     */
    public String getNicknameHandle() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.user_account.roles</code>.
     */
    public void setRoles(List<AccountRole> value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.user_account.roles</code>.
     */
    public List<AccountRole> getRoles() {
        return (List<AccountRole>) get(5);
    }

    /**
     * Setter for <code>public.user_account.is_active</code>.
     */
    public void setIsActive(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.user_account.is_active</code>.
     */
    public Boolean getIsActive() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>public.user_account.email_verified</code>.
     */
    public void setEmailVerified(Boolean value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.user_account.email_verified</code>.
     */
    public Boolean getEmailVerified() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>public.user_account.paint_count_total</code>.
     */
    public void setPaintCountTotal(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.user_account.paint_count_total</code>.
     */
    public Long getPaintCountTotal() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>public.user_account.metadata</code>.
     */
    public void setMetadata(JsonNode value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.user_account.metadata</code>.
     */
    public JsonNode getMetadata() {
        return (JsonNode) get(9);
    }

    /**
     * Setter for <code>public.user_account.last_login_at</code>.
     */
    public void setLastLoginAt(Instant value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.user_account.last_login_at</code>.
     */
    public Instant getLastLoginAt() {
        return (Instant) get(10);
    }

    /**
     * Setter for <code>public.user_account.login_count</code>.
     */
    public void setLoginCount(Long value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.user_account.login_count</code>.
     */
    public Long getLoginCount() {
        return (Long) get(11);
    }

    /**
     * Setter for <code>public.user_account.blocked_at</code>.
     */
    public void setBlockedAt(Instant value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.user_account.blocked_at</code>.
     */
    public Instant getBlockedAt() {
        return (Instant) get(12);
    }

    /**
     * Setter for <code>public.user_account.blocked_reason</code>.
     */
    public void setBlockedReason(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.user_account.blocked_reason</code>.
     */
    public String getBlockedReason() {
        return (String) get(13);
    }

    /**
     * Setter for <code>public.user_account.created_at</code>.
     */
    public void setCreatedAt(Instant value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.user_account.created_at</code>.
     */
    public Instant getCreatedAt() {
        return (Instant) get(14);
    }

    /**
     * Setter for <code>public.user_account.updated_at</code>.
     */
    public void setUpdatedAt(Instant value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.user_account.updated_at</code>.
     */
    public Instant getUpdatedAt() {
        return (Instant) get(15);
    }

    /**
     * Setter for <code>public.user_account.deleted_at</code>.
     */
    public void setDeletedAt(Instant value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.user_account.deleted_at</code>.
     */
    public Instant getDeletedAt() {
        return (Instant) get(16);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserAccountRecord
     */
    public UserAccountRecord() {
        super(UserAccount.USER_ACCOUNT);
    }

    /**
     * Create a detached, initialised UserAccountRecord
     */
    public UserAccountRecord(UUID id, String email, String nickname, Integer nicknameSeq, String nicknameHandle, List<AccountRole> roles, Boolean isActive, Boolean emailVerified, Long paintCountTotal, JsonNode metadata, Instant lastLoginAt, Long loginCount, Instant blockedAt, String blockedReason, Instant createdAt, Instant updatedAt, Instant deletedAt) {
        super(UserAccount.USER_ACCOUNT);

        setId(id);
        setEmail(email);
        setNickname(nickname);
        setNicknameSeq(nicknameSeq);
        setNicknameHandle(nicknameHandle);
        setRoles(roles);
        setIsActive(isActive);
        setEmailVerified(emailVerified);
        setPaintCountTotal(paintCountTotal);
        setMetadata(metadata);
        setLastLoginAt(lastLoginAt);
        setLoginCount(loginCount);
        setBlockedAt(blockedAt);
        setBlockedReason(blockedReason);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setDeletedAt(deletedAt);
        resetTouchedOnNotNull();
    }
}
