/*
 * This file is generated by jOOQ.
 */
package com.colombus.snapshot.jooq.tables;


import com.colombus.snapshot.jooq.Indexes;
import com.colombus.snapshot.jooq.Keys;
import com.colombus.snapshot.jooq.Public;
import com.colombus.snapshot.jooq.tables.ChunkIndex.ChunkIndexPath;
import com.colombus.snapshot.jooq.tables.records.ChunkCompactionJobRecord;
import com.colombus.snapshot.model.jooq.binding.CompactionStatusBinding;
import com.colombus.snapshot.model.type.CompactionStatus;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.DefaultDataType;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ChunkCompactionJob extends TableImpl<ChunkCompactionJobRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.chunk_compaction_job</code>
     */
    public static final ChunkCompactionJob CHUNK_COMPACTION_JOB = new ChunkCompactionJob();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ChunkCompactionJobRecord> getRecordType() {
        return ChunkCompactionJobRecord.class;
    }

    /**
     * The column <code>public.chunk_compaction_job.uuid</code>.
     */
    public final TableField<ChunkCompactionJobRecord, java.util.UUID> UUID = createField(DSL.name("uuid"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.chunk_compaction_job.chunk_id</code>.
     */
    public final TableField<ChunkCompactionJobRecord, java.util.UUID> CHUNK_ID = createField(DSL.name("chunk_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.chunk_compaction_job.from_version</code>.
     */
    public final TableField<ChunkCompactionJobRecord, Long> FROM_VERSION = createField(DSL.name("from_version"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.chunk_compaction_job.to_version</code>.
     */
    public final TableField<ChunkCompactionJobRecord, Long> TO_VERSION = createField(DSL.name("to_version"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.chunk_compaction_job.status</code>.
     */
    public final TableField<ChunkCompactionJobRecord, CompactionStatus> STATUS = createField(DSL.name("status"), DefaultDataType.getDefaultDataType("\"public\".\"compaction_status_enum\"").nullable(false).defaultValue(DSL.field(DSL.raw("'queued'::compaction_status_enum"), org.jooq.impl.SQLDataType.OTHER)), this, "", new CompactionStatusBinding());

    /**
     * The column <code>public.chunk_compaction_job.started_at</code>.
     */
    public final TableField<ChunkCompactionJobRecord, OffsetDateTime> STARTED_AT = createField(DSL.name("started_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.chunk_compaction_job.finished_at</code>.
     */
    public final TableField<ChunkCompactionJobRecord, OffsetDateTime> FINISHED_AT = createField(DSL.name("finished_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.chunk_compaction_job.stats</code>.
     */
    public final TableField<ChunkCompactionJobRecord, JSONB> STATS = createField(DSL.name("stats"), SQLDataType.JSONB, this, "");

    /**
     * The column <code>public.chunk_compaction_job.created_at</code>.
     */
    public final TableField<ChunkCompactionJobRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.chunk_compaction_job.updated_at</code>.
     */
    public final TableField<ChunkCompactionJobRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.chunk_compaction_job.deleted_at</code>.
     */
    public final TableField<ChunkCompactionJobRecord, OffsetDateTime> DELETED_AT = createField(DSL.name("deleted_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    private ChunkCompactionJob(Name alias, Table<ChunkCompactionJobRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ChunkCompactionJob(Name alias, Table<ChunkCompactionJobRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.chunk_compaction_job</code> table
     * reference
     */
    public ChunkCompactionJob(String alias) {
        this(DSL.name(alias), CHUNK_COMPACTION_JOB);
    }

    /**
     * Create an aliased <code>public.chunk_compaction_job</code> table
     * reference
     */
    public ChunkCompactionJob(Name alias) {
        this(alias, CHUNK_COMPACTION_JOB);
    }

    /**
     * Create a <code>public.chunk_compaction_job</code> table reference
     */
    public ChunkCompactionJob() {
        this(DSL.name("chunk_compaction_job"), null);
    }

    public <O extends Record> ChunkCompactionJob(Table<O> path, ForeignKey<O, ChunkCompactionJobRecord> childPath, InverseForeignKey<O, ChunkCompactionJobRecord> parentPath) {
        super(path, childPath, parentPath, CHUNK_COMPACTION_JOB);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ChunkCompactionJobPath extends ChunkCompactionJob implements Path<ChunkCompactionJobRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ChunkCompactionJobPath(Table<O> path, ForeignKey<O, ChunkCompactionJobRecord> childPath, InverseForeignKey<O, ChunkCompactionJobRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ChunkCompactionJobPath(Name alias, Table<ChunkCompactionJobRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ChunkCompactionJobPath as(String alias) {
            return new ChunkCompactionJobPath(DSL.name(alias), this);
        }

        @Override
        public ChunkCompactionJobPath as(Name alias) {
            return new ChunkCompactionJobPath(alias, this);
        }

        @Override
        public ChunkCompactionJobPath as(Table<?> alias) {
            return new ChunkCompactionJobPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_COMPACTION_CHUNK_STATUS);
    }

    @Override
    public UniqueKey<ChunkCompactionJobRecord> getPrimaryKey() {
        return Keys.CHUNK_COMPACTION_JOB_PKEY;
    }

    @Override
    public List<ForeignKey<ChunkCompactionJobRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CHUNK_COMPACTION_JOB__CHUNK_COMPACTION_JOB_CHUNK_ID_FKEY);
    }

    private transient ChunkIndexPath _chunkIndex;

    /**
     * Get the implicit join path to the <code>public.chunk_index</code> table.
     */
    public ChunkIndexPath chunkIndex() {
        if (_chunkIndex == null)
            _chunkIndex = new ChunkIndexPath(this, Keys.CHUNK_COMPACTION_JOB__CHUNK_COMPACTION_JOB_CHUNK_ID_FKEY, null);

        return _chunkIndex;
    }

    @Override
    public TableField<ChunkCompactionJobRecord, OffsetDateTime> getRecordTimestamp() {
        return UPDATED_AT;
    }

    @Override
    public ChunkCompactionJob as(String alias) {
        return new ChunkCompactionJob(DSL.name(alias), this);
    }

    @Override
    public ChunkCompactionJob as(Name alias) {
        return new ChunkCompactionJob(alias, this);
    }

    @Override
    public ChunkCompactionJob as(Table<?> alias) {
        return new ChunkCompactionJob(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ChunkCompactionJob rename(String name) {
        return new ChunkCompactionJob(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ChunkCompactionJob rename(Name name) {
        return new ChunkCompactionJob(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ChunkCompactionJob rename(Table<?> name) {
        return new ChunkCompactionJob(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ChunkCompactionJob where(Condition condition) {
        return new ChunkCompactionJob(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ChunkCompactionJob where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ChunkCompactionJob where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ChunkCompactionJob where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ChunkCompactionJob where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ChunkCompactionJob where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ChunkCompactionJob where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ChunkCompactionJob where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ChunkCompactionJob whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ChunkCompactionJob whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
