/*
 * This file is generated by jOOQ.
 */
package com.colombus.snapshot.jooq.tables;


import com.colombus.snapshot.jooq.Indexes;
import com.colombus.snapshot.jooq.Keys;
import com.colombus.snapshot.jooq.Public;
import com.colombus.snapshot.jooq.tables.ChunkCompactionJob.ChunkCompactionJobPath;
import com.colombus.snapshot.jooq.tables.ChunkMesh.ChunkMeshPath;
import com.colombus.snapshot.jooq.tables.ChunkSnapshot.ChunkSnapshotPath;
import com.colombus.snapshot.jooq.tables.World.WorldPath;
import com.colombus.snapshot.jooq.tables.records.ChunkIndexRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ChunkIndex extends TableImpl<ChunkIndexRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.chunk_index</code>
     */
    public static final ChunkIndex CHUNK_INDEX = new ChunkIndex();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ChunkIndexRecord> getRecordType() {
        return ChunkIndexRecord.class;
    }

    /**
     * The column <code>public.chunk_index.uuid</code>.
     */
    public final TableField<ChunkIndexRecord, java.util.UUID> UUID = createField(DSL.name("uuid"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.chunk_index.world_id</code>.
     */
    public final TableField<ChunkIndexRecord, java.util.UUID> WORLD_ID = createField(DSL.name("world_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.chunk_index.lod</code>.
     */
    public final TableField<ChunkIndexRecord, Short> LOD = createField(DSL.name("lod"), SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * The column <code>public.chunk_index.tx</code>.
     */
    public final TableField<ChunkIndexRecord, Integer> TX = createField(DSL.name("tx"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.chunk_index.ty</code>.
     */
    public final TableField<ChunkIndexRecord, Integer> TY = createField(DSL.name("ty"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.chunk_index.ix</code>.
     */
    public final TableField<ChunkIndexRecord, Integer> IX = createField(DSL.name("ix"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.chunk_index.iy</code>.
     */
    public final TableField<ChunkIndexRecord, Integer> IY = createField(DSL.name("iy"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.chunk_index.iz</code>.
     */
    public final TableField<ChunkIndexRecord, Integer> IZ = createField(DSL.name("iz"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.chunk_index.edge_cells</code>.
     */
    public final TableField<ChunkIndexRecord, Integer> EDGE_CELLS = createField(DSL.name("edge_cells"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.chunk_index.voxel_size_m</code>.
     */
    public final TableField<ChunkIndexRecord, Double> VOXEL_SIZE_M = createField(DSL.name("voxel_size_m"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.chunk_index.aabb_min_x</code>.
     */
    public final TableField<ChunkIndexRecord, Double> AABB_MIN_X = createField(DSL.name("aabb_min_x"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.chunk_index.aabb_min_y</code>.
     */
    public final TableField<ChunkIndexRecord, Double> AABB_MIN_Y = createField(DSL.name("aabb_min_y"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.chunk_index.aabb_min_z</code>.
     */
    public final TableField<ChunkIndexRecord, Double> AABB_MIN_Z = createField(DSL.name("aabb_min_z"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.chunk_index.aabb_max_x</code>.
     */
    public final TableField<ChunkIndexRecord, Double> AABB_MAX_X = createField(DSL.name("aabb_max_x"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.chunk_index.aabb_max_y</code>.
     */
    public final TableField<ChunkIndexRecord, Double> AABB_MAX_Y = createField(DSL.name("aabb_max_y"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.chunk_index.aabb_max_z</code>.
     */
    public final TableField<ChunkIndexRecord, Double> AABB_MAX_Z = createField(DSL.name("aabb_max_z"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.chunk_index.current_snapshot_id</code>.
     */
    public final TableField<ChunkIndexRecord, java.util.UUID> CURRENT_SNAPSHOT_ID = createField(DSL.name("current_snapshot_id"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.chunk_index.current_mesh_id</code>.
     */
    public final TableField<ChunkIndexRecord, java.util.UUID> CURRENT_MESH_ID = createField(DSL.name("current_mesh_id"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.chunk_index.current_version</code>.
     */
    public final TableField<ChunkIndexRecord, Long> CURRENT_VERSION = createField(DSL.name("current_version"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.chunk_index.current_mesh_version</code>.
     */
    public final TableField<ChunkIndexRecord, Long> CURRENT_MESH_VERSION = createField(DSL.name("current_mesh_version"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.chunk_index.last_write_at</code>.
     */
    public final TableField<ChunkIndexRecord, OffsetDateTime> LAST_WRITE_AT = createField(DSL.name("last_write_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.chunk_index.last_compacted_at</code>.
     */
    public final TableField<ChunkIndexRecord, OffsetDateTime> LAST_COMPACTED_AT = createField(DSL.name("last_compacted_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.chunk_index.created_at</code>.
     */
    public final TableField<ChunkIndexRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.chunk_index.updated_at</code>.
     */
    public final TableField<ChunkIndexRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.chunk_index.deleted_at</code>.
     */
    public final TableField<ChunkIndexRecord, OffsetDateTime> DELETED_AT = createField(DSL.name("deleted_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    private ChunkIndex(Name alias, Table<ChunkIndexRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ChunkIndex(Name alias, Table<ChunkIndexRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.chunk_index</code> table reference
     */
    public ChunkIndex(String alias) {
        this(DSL.name(alias), CHUNK_INDEX);
    }

    /**
     * Create an aliased <code>public.chunk_index</code> table reference
     */
    public ChunkIndex(Name alias) {
        this(alias, CHUNK_INDEX);
    }

    /**
     * Create a <code>public.chunk_index</code> table reference
     */
    public ChunkIndex() {
        this(DSL.name("chunk_index"), null);
    }

    public <O extends Record> ChunkIndex(Table<O> path, ForeignKey<O, ChunkIndexRecord> childPath, InverseForeignKey<O, ChunkIndexRecord> parentPath) {
        super(path, childPath, parentPath, CHUNK_INDEX);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ChunkIndexPath extends ChunkIndex implements Path<ChunkIndexRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ChunkIndexPath(Table<O> path, ForeignKey<O, ChunkIndexRecord> childPath, InverseForeignKey<O, ChunkIndexRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ChunkIndexPath(Name alias, Table<ChunkIndexRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ChunkIndexPath as(String alias) {
            return new ChunkIndexPath(DSL.name(alias), this);
        }

        @Override
        public ChunkIndexPath as(Name alias) {
            return new ChunkIndexPath(alias, this);
        }

        @Override
        public ChunkIndexPath as(Table<?> alias) {
            return new ChunkIndexPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_CHUNK_INDEX_WORLD_GRID);
    }

    @Override
    public UniqueKey<ChunkIndexRecord> getPrimaryKey() {
        return Keys.CHUNK_INDEX_PKEY;
    }

    @Override
    public List<UniqueKey<ChunkIndexRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.CHUNK_INDEX_WORLD_ID_LOD_TX_TY_IX_IY_IZ_KEY);
    }

    @Override
    public List<ForeignKey<ChunkIndexRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CHUNK_INDEX__CHUNK_INDEX_WORLD_ID_FKEY);
    }

    private transient WorldPath _world;

    /**
     * Get the implicit join path to the <code>public.world</code> table.
     */
    public WorldPath world() {
        if (_world == null)
            _world = new WorldPath(this, Keys.CHUNK_INDEX__CHUNK_INDEX_WORLD_ID_FKEY, null);

        return _world;
    }

    private transient ChunkCompactionJobPath _chunkCompactionJob;

    /**
     * Get the implicit to-many join path to the
     * <code>public.chunk_compaction_job</code> table
     */
    public ChunkCompactionJobPath chunkCompactionJob() {
        if (_chunkCompactionJob == null)
            _chunkCompactionJob = new ChunkCompactionJobPath(this, null, Keys.CHUNK_COMPACTION_JOB__CHUNK_COMPACTION_JOB_CHUNK_ID_FKEY.getInverseKey());

        return _chunkCompactionJob;
    }

    private transient ChunkMeshPath _chunkMesh;

    /**
     * Get the implicit to-many join path to the <code>public.chunk_mesh</code>
     * table
     */
    public ChunkMeshPath chunkMesh() {
        if (_chunkMesh == null)
            _chunkMesh = new ChunkMeshPath(this, null, Keys.CHUNK_MESH__CHUNK_MESH_CHUNK_ID_FKEY.getInverseKey());

        return _chunkMesh;
    }

    private transient ChunkSnapshotPath _chunkSnapshot;

    /**
     * Get the implicit to-many join path to the
     * <code>public.chunk_snapshot</code> table
     */
    public ChunkSnapshotPath chunkSnapshot() {
        if (_chunkSnapshot == null)
            _chunkSnapshot = new ChunkSnapshotPath(this, null, Keys.CHUNK_SNAPSHOT__CHUNK_SNAPSHOT_CHUNK_ID_FKEY.getInverseKey());

        return _chunkSnapshot;
    }

    @Override
    public TableField<ChunkIndexRecord, OffsetDateTime> getRecordTimestamp() {
        return UPDATED_AT;
    }

    @Override
    public ChunkIndex as(String alias) {
        return new ChunkIndex(DSL.name(alias), this);
    }

    @Override
    public ChunkIndex as(Name alias) {
        return new ChunkIndex(alias, this);
    }

    @Override
    public ChunkIndex as(Table<?> alias) {
        return new ChunkIndex(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ChunkIndex rename(String name) {
        return new ChunkIndex(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ChunkIndex rename(Name name) {
        return new ChunkIndex(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ChunkIndex rename(Table<?> name) {
        return new ChunkIndex(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ChunkIndex where(Condition condition) {
        return new ChunkIndex(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ChunkIndex where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ChunkIndex where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ChunkIndex where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ChunkIndex where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ChunkIndex where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ChunkIndex where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ChunkIndex where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ChunkIndex whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ChunkIndex whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
