/*
 * This file is generated by jOOQ.
 */
package com.colombus.snapshot.jooq.tables;


import com.colombus.snapshot.jooq.Indexes;
import com.colombus.snapshot.jooq.Keys;
import com.colombus.snapshot.jooq.Public;
import com.colombus.snapshot.jooq.tables.ChunkIndex.ChunkIndexPath;
import com.colombus.snapshot.jooq.tables.ChunkMesh.ChunkMeshPath;
import com.colombus.snapshot.jooq.tables.records.ChunkSnapshotRecord;
import com.colombus.snapshot.model.jooq.binding.SnapshotKindBinding;
import com.colombus.snapshot.model.type.SnapshotKind;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.DefaultDataType;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ChunkSnapshot extends TableImpl<ChunkSnapshotRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.chunk_snapshot</code>
     */
    public static final ChunkSnapshot CHUNK_SNAPSHOT = new ChunkSnapshot();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ChunkSnapshotRecord> getRecordType() {
        return ChunkSnapshotRecord.class;
    }

    /**
     * The column <code>public.chunk_snapshot.uuid</code>.
     */
    public final TableField<ChunkSnapshotRecord, java.util.UUID> UUID = createField(DSL.name("uuid"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.chunk_snapshot.chunk_id</code>.
     */
    public final TableField<ChunkSnapshotRecord, java.util.UUID> CHUNK_ID = createField(DSL.name("chunk_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.chunk_snapshot.version</code>.
     */
    public final TableField<ChunkSnapshotRecord, Long> VERSION = createField(DSL.name("version"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.chunk_snapshot.schema_version</code>.
     */
    public final TableField<ChunkSnapshotRecord, Short> SCHEMA_VERSION = createField(DSL.name("schema_version"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("1"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.chunk_snapshot.storage_uri</code>.
     */
    public final TableField<ChunkSnapshotRecord, String> STORAGE_URI = createField(DSL.name("storage_uri"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.chunk_snapshot.payload</code>.
     */
    public final TableField<ChunkSnapshotRecord, JSONB> PAYLOAD = createField(DSL.name("payload"), SQLDataType.JSONB, this, "");

    /**
     * The column <code>public.chunk_snapshot.snapshot_kind</code>.
     */
    public final TableField<ChunkSnapshotRecord, SnapshotKind> SNAPSHOT_KIND = createField(DSL.name("snapshot_kind"), DefaultDataType.getDefaultDataType("\"public\".\"snapshot_kind_enum\"").nullable(false).defaultValue(DSL.field(DSL.raw("'mesh-surface'::snapshot_kind_enum"), org.jooq.impl.SQLDataType.OTHER)), this, "", new SnapshotKindBinding());

    /**
     * The column <code>public.chunk_snapshot.non_empty_cells</code>.
     */
    public final TableField<ChunkSnapshotRecord, Integer> NON_EMPTY_CELLS = createField(DSL.name("non_empty_cells"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.chunk_snapshot.compressed_bytes</code>.
     */
    public final TableField<ChunkSnapshotRecord, Integer> COMPRESSED_BYTES = createField(DSL.name("compressed_bytes"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.chunk_snapshot.checksum_sha256</code>.
     */
    public final TableField<ChunkSnapshotRecord, byte[]> CHECKSUM_SHA256 = createField(DSL.name("checksum_sha256"), SQLDataType.BLOB, this, "");

    /**
     * The column <code>public.chunk_snapshot.created_at</code>.
     */
    public final TableField<ChunkSnapshotRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.chunk_snapshot.updated_at</code>.
     */
    public final TableField<ChunkSnapshotRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.chunk_snapshot.deleted_at</code>.
     */
    public final TableField<ChunkSnapshotRecord, OffsetDateTime> DELETED_AT = createField(DSL.name("deleted_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    private ChunkSnapshot(Name alias, Table<ChunkSnapshotRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ChunkSnapshot(Name alias, Table<ChunkSnapshotRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.chunk_snapshot</code> table reference
     */
    public ChunkSnapshot(String alias) {
        this(DSL.name(alias), CHUNK_SNAPSHOT);
    }

    /**
     * Create an aliased <code>public.chunk_snapshot</code> table reference
     */
    public ChunkSnapshot(Name alias) {
        this(alias, CHUNK_SNAPSHOT);
    }

    /**
     * Create a <code>public.chunk_snapshot</code> table reference
     */
    public ChunkSnapshot() {
        this(DSL.name("chunk_snapshot"), null);
    }

    public <O extends Record> ChunkSnapshot(Table<O> path, ForeignKey<O, ChunkSnapshotRecord> childPath, InverseForeignKey<O, ChunkSnapshotRecord> parentPath) {
        super(path, childPath, parentPath, CHUNK_SNAPSHOT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ChunkSnapshotPath extends ChunkSnapshot implements Path<ChunkSnapshotRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ChunkSnapshotPath(Table<O> path, ForeignKey<O, ChunkSnapshotRecord> childPath, InverseForeignKey<O, ChunkSnapshotRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ChunkSnapshotPath(Name alias, Table<ChunkSnapshotRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ChunkSnapshotPath as(String alias) {
            return new ChunkSnapshotPath(DSL.name(alias), this);
        }

        @Override
        public ChunkSnapshotPath as(Name alias) {
            return new ChunkSnapshotPath(alias, this);
        }

        @Override
        public ChunkSnapshotPath as(Table<?> alias) {
            return new ChunkSnapshotPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_CHUNK_SNAPSHOT_CHUNK_DESC);
    }

    @Override
    public UniqueKey<ChunkSnapshotRecord> getPrimaryKey() {
        return Keys.CHUNK_SNAPSHOT_PKEY;
    }

    @Override
    public List<UniqueKey<ChunkSnapshotRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.CHUNK_SNAPSHOT_CHUNK_ID_VERSION_KEY);
    }

    @Override
    public List<ForeignKey<ChunkSnapshotRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CHUNK_SNAPSHOT__CHUNK_SNAPSHOT_CHUNK_ID_FKEY);
    }

    private transient ChunkIndexPath _chunkIndex;

    /**
     * Get the implicit join path to the <code>public.chunk_index</code> table.
     */
    public ChunkIndexPath chunkIndex() {
        if (_chunkIndex == null)
            _chunkIndex = new ChunkIndexPath(this, Keys.CHUNK_SNAPSHOT__CHUNK_SNAPSHOT_CHUNK_ID_FKEY, null);

        return _chunkIndex;
    }

    private transient ChunkMeshPath _chunkMesh;

    /**
     * Get the implicit to-many join path to the <code>public.chunk_mesh</code>
     * table
     */
    public ChunkMeshPath chunkMesh() {
        if (_chunkMesh == null)
            _chunkMesh = new ChunkMeshPath(this, null, Keys.CHUNK_MESH__CHUNK_MESH_SNAPSHOT_ID_FKEY.getInverseKey());

        return _chunkMesh;
    }

    @Override
    public TableField<ChunkSnapshotRecord, OffsetDateTime> getRecordTimestamp() {
        return UPDATED_AT;
    }

    @Override
    public ChunkSnapshot as(String alias) {
        return new ChunkSnapshot(DSL.name(alias), this);
    }

    @Override
    public ChunkSnapshot as(Name alias) {
        return new ChunkSnapshot(alias, this);
    }

    @Override
    public ChunkSnapshot as(Table<?> alias) {
        return new ChunkSnapshot(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ChunkSnapshot rename(String name) {
        return new ChunkSnapshot(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ChunkSnapshot rename(Name name) {
        return new ChunkSnapshot(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ChunkSnapshot rename(Table<?> name) {
        return new ChunkSnapshot(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ChunkSnapshot where(Condition condition) {
        return new ChunkSnapshot(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ChunkSnapshot where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ChunkSnapshot where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ChunkSnapshot where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ChunkSnapshot where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ChunkSnapshot where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ChunkSnapshot where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ChunkSnapshot where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ChunkSnapshot whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ChunkSnapshot whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
