/*
 * This file is generated by jOOQ.
 */
package com.colombus.snapshot.jooq.tables;


import com.colombus.snapshot.jooq.Indexes;
import com.colombus.snapshot.jooq.Keys;
import com.colombus.snapshot.jooq.Public;
import com.colombus.snapshot.jooq.tables.ChunkIndex.ChunkIndexPath;
import com.colombus.snapshot.jooq.tables.ChunkSnapshot.ChunkSnapshotPath;
import com.colombus.snapshot.jooq.tables.records.ChunkMeshRecord;
import com.colombus.snapshot.model.jooq.binding.ArtifactKindBinding;
import com.colombus.snapshot.model.type.ArtifactKind;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.DefaultDataType;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ChunkMesh extends TableImpl<ChunkMeshRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.chunk_mesh</code>
     */
    public static final ChunkMesh CHUNK_MESH = new ChunkMesh();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ChunkMeshRecord> getRecordType() {
        return ChunkMeshRecord.class;
    }

    /**
     * The column <code>public.chunk_mesh.uuid</code>.
     */
    public final TableField<ChunkMeshRecord, java.util.UUID> UUID = createField(DSL.name("uuid"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.chunk_mesh.chunk_id</code>.
     */
    public final TableField<ChunkMeshRecord, java.util.UUID> CHUNK_ID = createField(DSL.name("chunk_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.chunk_mesh.snapshot_id</code>.
     */
    public final TableField<ChunkMeshRecord, java.util.UUID> SNAPSHOT_ID = createField(DSL.name("snapshot_id"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.chunk_mesh.mesh_version</code>.
     */
    public final TableField<ChunkMeshRecord, Long> MESH_VERSION = createField(DSL.name("mesh_version"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.chunk_mesh.artifact_uri</code>.
     */
    public final TableField<ChunkMeshRecord, String> ARTIFACT_URI = createField(DSL.name("artifact_uri"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.chunk_mesh.artifact_kind</code>.
     */
    public final TableField<ChunkMeshRecord, ArtifactKind> ARTIFACT_KIND = createField(DSL.name("artifact_kind"), DefaultDataType.getDefaultDataType("\"public\".\"artifact_kind_enum\"").nullable(false).defaultValue(DSL.field(DSL.raw("'gltf+draco'::artifact_kind_enum"), org.jooq.impl.SQLDataType.OTHER)), this, "", new ArtifactKindBinding());

    /**
     * The column <code>public.chunk_mesh.tri_count</code>.
     */
    public final TableField<ChunkMeshRecord, Long> TRI_COUNT = createField(DSL.name("tri_count"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.chunk_mesh.vertex_count</code>.
     */
    public final TableField<ChunkMeshRecord, Long> VERTEX_COUNT = createField(DSL.name("vertex_count"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.chunk_mesh.compressed_bytes</code>.
     */
    public final TableField<ChunkMeshRecord, Integer> COMPRESSED_BYTES = createField(DSL.name("compressed_bytes"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.chunk_mesh.checksum_sha256</code>.
     */
    public final TableField<ChunkMeshRecord, byte[]> CHECKSUM_SHA256 = createField(DSL.name("checksum_sha256"), SQLDataType.BLOB, this, "");

    /**
     * The column <code>public.chunk_mesh.created_at</code>.
     */
    public final TableField<ChunkMeshRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.chunk_mesh.updated_at</code>.
     */
    public final TableField<ChunkMeshRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.chunk_mesh.deleted_at</code>.
     */
    public final TableField<ChunkMeshRecord, OffsetDateTime> DELETED_AT = createField(DSL.name("deleted_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    private ChunkMesh(Name alias, Table<ChunkMeshRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ChunkMesh(Name alias, Table<ChunkMeshRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.chunk_mesh</code> table reference
     */
    public ChunkMesh(String alias) {
        this(DSL.name(alias), CHUNK_MESH);
    }

    /**
     * Create an aliased <code>public.chunk_mesh</code> table reference
     */
    public ChunkMesh(Name alias) {
        this(alias, CHUNK_MESH);
    }

    /**
     * Create a <code>public.chunk_mesh</code> table reference
     */
    public ChunkMesh() {
        this(DSL.name("chunk_mesh"), null);
    }

    public <O extends Record> ChunkMesh(Table<O> path, ForeignKey<O, ChunkMeshRecord> childPath, InverseForeignKey<O, ChunkMeshRecord> parentPath) {
        super(path, childPath, parentPath, CHUNK_MESH);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ChunkMeshPath extends ChunkMesh implements Path<ChunkMeshRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ChunkMeshPath(Table<O> path, ForeignKey<O, ChunkMeshRecord> childPath, InverseForeignKey<O, ChunkMeshRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ChunkMeshPath(Name alias, Table<ChunkMeshRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ChunkMeshPath as(String alias) {
            return new ChunkMeshPath(DSL.name(alias), this);
        }

        @Override
        public ChunkMeshPath as(Name alias) {
            return new ChunkMeshPath(alias, this);
        }

        @Override
        public ChunkMeshPath as(Table<?> alias) {
            return new ChunkMeshPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_CHUNK_MESH_CHUNK_DESC);
    }

    @Override
    public UniqueKey<ChunkMeshRecord> getPrimaryKey() {
        return Keys.CHUNK_MESH_PKEY;
    }

    @Override
    public List<UniqueKey<ChunkMeshRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.CHUNK_MESH_CHUNK_ID_MESH_VERSION_KEY);
    }

    @Override
    public List<ForeignKey<ChunkMeshRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CHUNK_MESH__CHUNK_MESH_CHUNK_ID_FKEY, Keys.CHUNK_MESH__CHUNK_MESH_SNAPSHOT_ID_FKEY);
    }

    private transient ChunkIndexPath _chunkIndex;

    /**
     * Get the implicit join path to the <code>public.chunk_index</code> table.
     */
    public ChunkIndexPath chunkIndex() {
        if (_chunkIndex == null)
            _chunkIndex = new ChunkIndexPath(this, Keys.CHUNK_MESH__CHUNK_MESH_CHUNK_ID_FKEY, null);

        return _chunkIndex;
    }

    private transient ChunkSnapshotPath _chunkSnapshot;

    /**
     * Get the implicit join path to the <code>public.chunk_snapshot</code>
     * table.
     */
    public ChunkSnapshotPath chunkSnapshot() {
        if (_chunkSnapshot == null)
            _chunkSnapshot = new ChunkSnapshotPath(this, Keys.CHUNK_MESH__CHUNK_MESH_SNAPSHOT_ID_FKEY, null);

        return _chunkSnapshot;
    }

    @Override
    public TableField<ChunkMeshRecord, OffsetDateTime> getRecordTimestamp() {
        return UPDATED_AT;
    }

    @Override
    public ChunkMesh as(String alias) {
        return new ChunkMesh(DSL.name(alias), this);
    }

    @Override
    public ChunkMesh as(Name alias) {
        return new ChunkMesh(alias, this);
    }

    @Override
    public ChunkMesh as(Table<?> alias) {
        return new ChunkMesh(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ChunkMesh rename(String name) {
        return new ChunkMesh(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ChunkMesh rename(Name name) {
        return new ChunkMesh(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ChunkMesh rename(Table<?> name) {
        return new ChunkMesh(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ChunkMesh where(Condition condition) {
        return new ChunkMesh(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ChunkMesh where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ChunkMesh where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ChunkMesh where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ChunkMesh where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ChunkMesh where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ChunkMesh where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ChunkMesh where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ChunkMesh whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ChunkMesh whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
