/*
 * This file is generated by jOOQ.
 */
package com.colombus.snapshot.jooq.tables;


import com.colombus.snapshot.jooq.Keys;
import com.colombus.snapshot.jooq.Public;
import com.colombus.snapshot.jooq.tables.World.WorldPath;
import com.colombus.snapshot.jooq.tables.records.WorldLodRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WorldLod extends TableImpl<WorldLodRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.world_lod</code>
     */
    public static final WorldLod WORLD_LOD = new WorldLod();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WorldLodRecord> getRecordType() {
        return WorldLodRecord.class;
    }

    /**
     * The column <code>public.world_lod.uuid</code>.
     */
    public final TableField<WorldLodRecord, java.util.UUID> UUID = createField(DSL.name("uuid"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.world_lod.world_id</code>.
     */
    public final TableField<WorldLodRecord, java.util.UUID> WORLD_ID = createField(DSL.name("world_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.world_lod.lod</code>.
     */
    public final TableField<WorldLodRecord, Short> LOD = createField(DSL.name("lod"), SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * The column <code>public.world_lod.chunk_edge_cells</code>.
     */
    public final TableField<WorldLodRecord, Integer> CHUNK_EDGE_CELLS = createField(DSL.name("chunk_edge_cells"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.world_lod.voxel_size_m</code>.
     */
    public final TableField<WorldLodRecord, Double> VOXEL_SIZE_M = createField(DSL.name("voxel_size_m"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.world_lod.morton_order</code>.
     */
    public final TableField<WorldLodRecord, Boolean> MORTON_ORDER = createField(DSL.name("morton_order"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.world_lod.lod_meta</code>.
     */
    public final TableField<WorldLodRecord, JSONB> LOD_META = createField(DSL.name("lod_meta"), SQLDataType.JSONB, this, "");

    /**
     * The column <code>public.world_lod.created_at</code>.
     */
    public final TableField<WorldLodRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.world_lod.updated_at</code>.
     */
    public final TableField<WorldLodRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.world_lod.deleted_at</code>.
     */
    public final TableField<WorldLodRecord, OffsetDateTime> DELETED_AT = createField(DSL.name("deleted_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    private WorldLod(Name alias, Table<WorldLodRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private WorldLod(Name alias, Table<WorldLodRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.world_lod</code> table reference
     */
    public WorldLod(String alias) {
        this(DSL.name(alias), WORLD_LOD);
    }

    /**
     * Create an aliased <code>public.world_lod</code> table reference
     */
    public WorldLod(Name alias) {
        this(alias, WORLD_LOD);
    }

    /**
     * Create a <code>public.world_lod</code> table reference
     */
    public WorldLod() {
        this(DSL.name("world_lod"), null);
    }

    public <O extends Record> WorldLod(Table<O> path, ForeignKey<O, WorldLodRecord> childPath, InverseForeignKey<O, WorldLodRecord> parentPath) {
        super(path, childPath, parentPath, WORLD_LOD);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class WorldLodPath extends WorldLod implements Path<WorldLodRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> WorldLodPath(Table<O> path, ForeignKey<O, WorldLodRecord> childPath, InverseForeignKey<O, WorldLodRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private WorldLodPath(Name alias, Table<WorldLodRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public WorldLodPath as(String alias) {
            return new WorldLodPath(DSL.name(alias), this);
        }

        @Override
        public WorldLodPath as(Name alias) {
            return new WorldLodPath(alias, this);
        }

        @Override
        public WorldLodPath as(Table<?> alias) {
            return new WorldLodPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<WorldLodRecord> getPrimaryKey() {
        return Keys.WORLD_LOD_PKEY;
    }

    @Override
    public List<UniqueKey<WorldLodRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.WORLD_LOD_WORLD_ID_LOD_KEY);
    }

    @Override
    public List<ForeignKey<WorldLodRecord, ?>> getReferences() {
        return Arrays.asList(Keys.WORLD_LOD__WORLD_LOD_WORLD_ID_FKEY);
    }

    private transient WorldPath _world;

    /**
     * Get the implicit join path to the <code>public.world</code> table.
     */
    public WorldPath world() {
        if (_world == null)
            _world = new WorldPath(this, Keys.WORLD_LOD__WORLD_LOD_WORLD_ID_FKEY, null);

        return _world;
    }

    @Override
    public List<Check<WorldLodRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("world_lod_chunk_edge_cells_check"), "((chunk_edge_cells > 0))", true),
            Internal.createCheck(this, DSL.name("world_lod_voxel_size_m_check"), "((voxel_size_m > (0)::double precision))", true)
        );
    }

    @Override
    public TableField<WorldLodRecord, OffsetDateTime> getRecordTimestamp() {
        return UPDATED_AT;
    }

    @Override
    public WorldLod as(String alias) {
        return new WorldLod(DSL.name(alias), this);
    }

    @Override
    public WorldLod as(Name alias) {
        return new WorldLod(alias, this);
    }

    @Override
    public WorldLod as(Table<?> alias) {
        return new WorldLod(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public WorldLod rename(String name) {
        return new WorldLod(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public WorldLod rename(Name name) {
        return new WorldLod(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public WorldLod rename(Table<?> name) {
        return new WorldLod(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WorldLod where(Condition condition) {
        return new WorldLod(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WorldLod where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WorldLod where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WorldLod where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WorldLod where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WorldLod where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WorldLod where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public WorldLod where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WorldLod whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public WorldLod whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
