/*
 * This file is generated by jOOQ.
 */
package com.colombus.snapshot.jooq.tables;


import com.colombus.snapshot.jooq.Keys;
import com.colombus.snapshot.jooq.Public;
import com.colombus.snapshot.jooq.tables.ChunkIndex.ChunkIndexPath;
import com.colombus.snapshot.jooq.tables.WorldLod.WorldLodPath;
import com.colombus.snapshot.jooq.tables.records.WorldRecord;

import java.time.OffsetDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class World extends TableImpl<WorldRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.world</code>
     */
    public static final World WORLD = new World();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WorldRecord> getRecordType() {
        return WorldRecord.class;
    }

    /**
     * The column <code>public.world.uuid</code>.
     */
    public final TableField<WorldRecord, java.util.UUID> UUID = createField(DSL.name("uuid"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.world.name</code>.
     */
    public final TableField<WorldRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.world.description</code>.
     */
    public final TableField<WorldRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.world.origin_x_ecef</code>.
     */
    public final TableField<WorldRecord, Double> ORIGIN_X_ECEF = createField(DSL.name("origin_x_ecef"), SQLDataType.DOUBLE.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.DOUBLE)), this, "");

    /**
     * The column <code>public.world.origin_y_ecef</code>.
     */
    public final TableField<WorldRecord, Double> ORIGIN_Y_ECEF = createField(DSL.name("origin_y_ecef"), SQLDataType.DOUBLE.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.DOUBLE)), this, "");

    /**
     * The column <code>public.world.origin_z_ecef</code>.
     */
    public final TableField<WorldRecord, Double> ORIGIN_Z_ECEF = createField(DSL.name("origin_z_ecef"), SQLDataType.DOUBLE.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.DOUBLE)), this, "");

    /**
     * The column <code>public.world.created_at</code>.
     */
    public final TableField<WorldRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.world.updated_at</code>.
     */
    public final TableField<WorldRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.world.deleted_at</code>.
     */
    public final TableField<WorldRecord, OffsetDateTime> DELETED_AT = createField(DSL.name("deleted_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    private World(Name alias, Table<WorldRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private World(Name alias, Table<WorldRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.world</code> table reference
     */
    public World(String alias) {
        this(DSL.name(alias), WORLD);
    }

    /**
     * Create an aliased <code>public.world</code> table reference
     */
    public World(Name alias) {
        this(alias, WORLD);
    }

    /**
     * Create a <code>public.world</code> table reference
     */
    public World() {
        this(DSL.name("world"), null);
    }

    public <O extends Record> World(Table<O> path, ForeignKey<O, WorldRecord> childPath, InverseForeignKey<O, WorldRecord> parentPath) {
        super(path, childPath, parentPath, WORLD);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class WorldPath extends World implements Path<WorldRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> WorldPath(Table<O> path, ForeignKey<O, WorldRecord> childPath, InverseForeignKey<O, WorldRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private WorldPath(Name alias, Table<WorldRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public WorldPath as(String alias) {
            return new WorldPath(DSL.name(alias), this);
        }

        @Override
        public WorldPath as(Name alias) {
            return new WorldPath(alias, this);
        }

        @Override
        public WorldPath as(Table<?> alias) {
            return new WorldPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<WorldRecord> getPrimaryKey() {
        return Keys.WORLD_PKEY;
    }

    private transient ChunkIndexPath _chunkIndex;

    /**
     * Get the implicit to-many join path to the <code>public.chunk_index</code>
     * table
     */
    public ChunkIndexPath chunkIndex() {
        if (_chunkIndex == null)
            _chunkIndex = new ChunkIndexPath(this, null, Keys.CHUNK_INDEX__CHUNK_INDEX_WORLD_ID_FKEY.getInverseKey());

        return _chunkIndex;
    }

    private transient WorldLodPath _worldLod;

    /**
     * Get the implicit to-many join path to the <code>public.world_lod</code>
     * table
     */
    public WorldLodPath worldLod() {
        if (_worldLod == null)
            _worldLod = new WorldLodPath(this, null, Keys.WORLD_LOD__WORLD_LOD_WORLD_ID_FKEY.getInverseKey());

        return _worldLod;
    }

    @Override
    public TableField<WorldRecord, OffsetDateTime> getRecordTimestamp() {
        return UPDATED_AT;
    }

    @Override
    public World as(String alias) {
        return new World(DSL.name(alias), this);
    }

    @Override
    public World as(Name alias) {
        return new World(alias, this);
    }

    @Override
    public World as(Table<?> alias) {
        return new World(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public World rename(String name) {
        return new World(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public World rename(Name name) {
        return new World(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public World rename(Table<?> name) {
        return new World(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public World where(Condition condition) {
        return new World(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public World where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public World where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public World where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public World where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public World where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public World where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public World where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public World whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public World whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
