/*
 * This file is generated by jOOQ.
 */
package com.colombus.user.jooq;


import com.colombus.user.jooq.tables.AuthEvent;
import com.colombus.user.jooq.tables.OutboxEvent;
import com.colombus.user.jooq.tables.UserAccount;
import com.colombus.user.jooq.tables.UserIdentity;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index IDX_AUTH_EVENT_KIND_TIME = Internal.createIndex(DSL.name("idx_auth_event_kind_time"), AuthEvent.AUTH_EVENT, new OrderField[] { AuthEvent.AUTH_EVENT.KIND, AuthEvent.AUTH_EVENT.CREATED_AT.desc() }, false);
    public static final Index IDX_AUTH_EVENT_PROVIDER_TIME = Internal.createIndex(DSL.name("idx_auth_event_provider_time"), AuthEvent.AUTH_EVENT, new OrderField[] { AuthEvent.AUTH_EVENT.PROVIDER, AuthEvent.AUTH_EVENT.CREATED_AT.desc() }, false);
    public static final Index IDX_AUTH_EVENT_UUID = Internal.createIndex(DSL.name("idx_auth_event_uuid"), AuthEvent.AUTH_EVENT, new OrderField[] { AuthEvent.AUTH_EVENT.ID }, false);
    public static final Index IDX_OUTBOX_CREATED = Internal.createIndex(DSL.name("idx_outbox_created"), OutboxEvent.OUTBOX_EVENT, new OrderField[] { OutboxEvent.OUTBOX_EVENT.CREATED_AT.desc() }, false);
    public static final Index IDX_USER_ACCOUNT_CREATED_AT = Internal.createIndex(DSL.name("idx_user_account_created_at"), UserAccount.USER_ACCOUNT, new OrderField[] { UserAccount.USER_ACCOUNT.CREATED_AT.desc() }, false);
    public static final Index IDX_USER_ACCOUNT_LAST_LOGIN = Internal.createIndex(DSL.name("idx_user_account_last_login"), UserAccount.USER_ACCOUNT, new OrderField[] { UserAccount.USER_ACCOUNT.LAST_LOGIN_AT.desc() }, false);
    public static final Index IDX_USER_ACCOUNT_METADATA_GIN = Internal.createIndex(DSL.name("idx_user_account_metadata_gin"), UserAccount.USER_ACCOUNT, new OrderField[] { UserAccount.USER_ACCOUNT.METADATA }, false);
    public static final Index IDX_USER_ACCOUNT_ROLES_GIN = Internal.createIndex(DSL.name("idx_user_account_roles_gin"), UserAccount.USER_ACCOUNT, new OrderField[] { UserAccount.USER_ACCOUNT.ROLES }, false);
    public static final Index IDX_USER_IDENTITY_PROVIDER = Internal.createIndex(DSL.name("idx_user_identity_provider"), UserIdentity.USER_IDENTITY, new OrderField[] { UserIdentity.USER_IDENTITY.PROVIDER, UserIdentity.USER_IDENTITY.PROVIDER_TENANT }, false);
    public static final Index IDX_USER_IDENTITY_USER_ID = Internal.createIndex(DSL.name("idx_user_identity_user_id"), UserIdentity.USER_IDENTITY, new OrderField[] { UserIdentity.USER_IDENTITY.USER_ID }, false);
    public static final Index UQ_IDENTITY_PROVIDER_TUPLE_ALIVE = Internal.createIndex(DSL.name("uq_identity_provider_tuple_alive"), UserIdentity.USER_IDENTITY, new OrderField[] { UserIdentity.USER_IDENTITY.PROVIDER, UserIdentity.USER_IDENTITY.PROVIDER_TENANT, UserIdentity.USER_IDENTITY.PROVIDER_SUB }, true);
    public static final Index UQ_OUTBOX_AGGREGATE_VERSION = Internal.createIndex(DSL.name("uq_outbox_aggregate_version"), OutboxEvent.OUTBOX_EVENT, new OrderField[] { OutboxEvent.OUTBOX_EVENT.AGGREGATE, OutboxEvent.OUTBOX_EVENT.AGGREGATE_ID, OutboxEvent.OUTBOX_EVENT.TYPE, OutboxEvent.OUTBOX_EVENT.VERSION }, true);
    public static final Index UQ_USER_ACCOUNT_EMAIL_ALIVE = Internal.createIndex(DSL.name("uq_user_account_email_alive"), UserAccount.USER_ACCOUNT, new OrderField[] { UserAccount.USER_ACCOUNT.EMAIL }, true);
}
