/*
 * This file is generated by jOOQ.
 */
package com.colombus.user.jooq;


import com.colombus.user.jooq.tables.AuthEvent;
import com.colombus.user.jooq.tables.NicknameSeries;
import com.colombus.user.jooq.tables.OutboxEvent;
import com.colombus.user.jooq.tables.UserAccount;
import com.colombus.user.jooq.tables.UserIdentity;
import com.colombus.user.jooq.tables.records.AuthEventRecord;
import com.colombus.user.jooq.tables.records.NicknameSeriesRecord;
import com.colombus.user.jooq.tables.records.OutboxEventRecord;
import com.colombus.user.jooq.tables.records.UserAccountRecord;
import com.colombus.user.jooq.tables.records.UserIdentityRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.QOM.ForeignKeyRule;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AuthEventRecord> AUTH_EVENT_PKEY = Internal.createUniqueKey(AuthEvent.AUTH_EVENT, DSL.name("auth_event_pkey"), new TableField[] { AuthEvent.AUTH_EVENT.ID, AuthEvent.AUTH_EVENT.CREATED_AT }, true);
    public static final UniqueKey<NicknameSeriesRecord> NICKNAME_SERIES_PKEY = Internal.createUniqueKey(NicknameSeries.NICKNAME_SERIES, DSL.name("nickname_series_pkey"), new TableField[] { NicknameSeries.NICKNAME_SERIES.NICKNAME }, true);
    public static final UniqueKey<OutboxEventRecord> OUTBOX_EVENT_PKEY = Internal.createUniqueKey(OutboxEvent.OUTBOX_EVENT, DSL.name("outbox_event_pkey"), new TableField[] { OutboxEvent.OUTBOX_EVENT.ID }, true);
    public static final UniqueKey<UserAccountRecord> USER_ACCOUNT_PKEY = Internal.createUniqueKey(UserAccount.USER_ACCOUNT, DSL.name("user_account_pkey"), new TableField[] { UserAccount.USER_ACCOUNT.ID }, true);
    public static final UniqueKey<UserIdentityRecord> USER_IDENTITY_PKEY = Internal.createUniqueKey(UserIdentity.USER_IDENTITY, DSL.name("user_identity_pkey"), new TableField[] { UserIdentity.USER_IDENTITY.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<AuthEventRecord, UserAccountRecord> AUTH_EVENT__AUTH_EVENT_USER_ID_FKEY = Internal.createForeignKey(AuthEvent.AUTH_EVENT, DSL.name("auth_event_user_id_fkey"), new TableField[] { AuthEvent.AUTH_EVENT.USER_ID }, Keys.USER_ACCOUNT_PKEY, new TableField[] { UserAccount.USER_ACCOUNT.ID }, true, ForeignKeyRule.RESTRICT, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<UserIdentityRecord, UserAccountRecord> USER_IDENTITY__USER_IDENTITY_USER_ID_FKEY = Internal.createForeignKey(UserIdentity.USER_IDENTITY, DSL.name("user_identity_user_id_fkey"), new TableField[] { UserIdentity.USER_IDENTITY.USER_ID }, Keys.USER_ACCOUNT_PKEY, new TableField[] { UserAccount.USER_ACCOUNT.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
}
