/*
 * This file is generated by jOOQ.
 */
package com.colombus.user.jooq;


import com.colombus.user.jooq.tables.AuthEvent;
import com.colombus.user.jooq.tables.NicknameSeries;
import com.colombus.user.jooq.tables.OutboxEvent;
import com.colombus.user.jooq.tables.UserAccount;
import com.colombus.user.jooq.tables.UserIdentity;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.DSL;
import org.jooq.impl.SchemaImpl;


/**
 * standard public schema
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.auth_event</code>.
     */
    public final AuthEvent AUTH_EVENT = AuthEvent.AUTH_EVENT;

    /**
     * The table <code>public.nickname_series</code>.
     */
    public final NicknameSeries NICKNAME_SERIES = NicknameSeries.NICKNAME_SERIES;

    /**
     * The table <code>public.outbox_event</code>.
     */
    public final OutboxEvent OUTBOX_EVENT = OutboxEvent.OUTBOX_EVENT;

    /**
     * The table <code>public.user_account</code>.
     */
    public final UserAccount USER_ACCOUNT = UserAccount.USER_ACCOUNT;

    /**
     * The table <code>public.user_identity</code>.
     */
    public final UserIdentity USER_IDENTITY = UserIdentity.USER_IDENTITY;

    /**
     * No further instances allowed
     */
    private Public() {
        super(DSL.name("public"), null, DSL.comment("standard public schema"));
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            AuthEvent.AUTH_EVENT,
            NicknameSeries.NICKNAME_SERIES,
            OutboxEvent.OUTBOX_EVENT,
            UserAccount.USER_ACCOUNT,
            UserIdentity.USER_IDENTITY
        );
    }
}
