/*
 * This file is generated by jOOQ.
 */
package com.colombus.user.jooq;


import com.colombus.user.jooq.tables.AuthEvent;
import com.colombus.user.jooq.tables.NicknameSeries;
import com.colombus.user.jooq.tables.OutboxEvent;
import com.colombus.user.jooq.tables.UserAccount;
import com.colombus.user.jooq.tables.UserIdentity;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.auth_event</code>.
     */
    public static final AuthEvent AUTH_EVENT = AuthEvent.AUTH_EVENT;

    /**
     * The table <code>public.nickname_series</code>.
     */
    public static final NicknameSeries NICKNAME_SERIES = NicknameSeries.NICKNAME_SERIES;

    /**
     * The table <code>public.outbox_event</code>.
     */
    public static final OutboxEvent OUTBOX_EVENT = OutboxEvent.OUTBOX_EVENT;

    /**
     * The table <code>public.user_account</code>.
     */
    public static final UserAccount USER_ACCOUNT = UserAccount.USER_ACCOUNT;

    /**
     * The table <code>public.user_identity</code>.
     */
    public static final UserIdentity USER_IDENTITY = UserIdentity.USER_IDENTITY;
}
