/*
 * This file is generated by jOOQ.
 */
package com.colombus.clan.jooq.tables;


import com.colombus.clan.jooq.Indexes;
import com.colombus.clan.jooq.Keys;
import com.colombus.clan.jooq.Public;
import com.colombus.clan.jooq.tables.ClanInfo.ClanInfoPath;
import com.colombus.clan.jooq.tables.records.ClanInviteTicketRecord;
import com.colombus.common.jooq.OffsetDateTimeToInstantConverter;

import java.time.Instant;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ClanInviteTicket extends TableImpl<ClanInviteTicketRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.clan_invite_ticket</code>
     */
    public static final ClanInviteTicket CLAN_INVITE_TICKET = new ClanInviteTicket();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ClanInviteTicketRecord> getRecordType() {
        return ClanInviteTicketRecord.class;
    }

    /**
     * The column <code>public.clan_invite_ticket.id</code>.
     */
    public final TableField<ClanInviteTicketRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("uuidv7()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.clan_invite_ticket.clan_id</code>.
     */
    public final TableField<ClanInviteTicketRecord, UUID> CLAN_ID = createField(DSL.name("clan_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.clan_invite_ticket.code</code>.
     */
    public final TableField<ClanInviteTicketRecord, String> CODE = createField(DSL.name("code"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.clan_invite_ticket.created_by</code>.
     */
    public final TableField<ClanInviteTicketRecord, UUID> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.clan_invite_ticket.max_uses</code>.
     */
    public final TableField<ClanInviteTicketRecord, Integer> MAX_USES = createField(DSL.name("max_uses"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.clan_invite_ticket.use_count</code>.
     */
    public final TableField<ClanInviteTicketRecord, Integer> USE_COUNT = createField(DSL.name("use_count"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.clan_invite_ticket.expires_at</code>.
     */
    public final TableField<ClanInviteTicketRecord, Instant> EXPIRES_AT = createField(DSL.name("expires_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "", new OffsetDateTimeToInstantConverter());

    /**
     * The column <code>public.clan_invite_ticket.is_revoked</code>.
     */
    public final TableField<ClanInviteTicketRecord, Boolean> IS_REVOKED = createField(DSL.name("is_revoked"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.clan_invite_ticket.metadata</code>.
     */
    public final TableField<ClanInviteTicketRecord, JSONB> METADATA = createField(DSL.name("metadata"), SQLDataType.JSONB.nullable(false).defaultValue(DSL.field(DSL.raw("'{}'::jsonb"), SQLDataType.JSONB)), this, "");

    /**
     * The column <code>public.clan_invite_ticket.created_at</code>.
     */
    public final TableField<ClanInviteTicketRecord, Instant> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "", new OffsetDateTimeToInstantConverter());

    /**
     * The column <code>public.clan_invite_ticket.updated_at</code>.
     */
    public final TableField<ClanInviteTicketRecord, Instant> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "", new OffsetDateTimeToInstantConverter());

    /**
     * The column <code>public.clan_invite_ticket.deleted_at</code>.
     */
    public final TableField<ClanInviteTicketRecord, Instant> DELETED_AT = createField(DSL.name("deleted_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "", new OffsetDateTimeToInstantConverter());

    private ClanInviteTicket(Name alias, Table<ClanInviteTicketRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ClanInviteTicket(Name alias, Table<ClanInviteTicketRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.clan_invite_ticket</code> table reference
     */
    public ClanInviteTicket(String alias) {
        this(DSL.name(alias), CLAN_INVITE_TICKET);
    }

    /**
     * Create an aliased <code>public.clan_invite_ticket</code> table reference
     */
    public ClanInviteTicket(Name alias) {
        this(alias, CLAN_INVITE_TICKET);
    }

    /**
     * Create a <code>public.clan_invite_ticket</code> table reference
     */
    public ClanInviteTicket() {
        this(DSL.name("clan_invite_ticket"), null);
    }

    public <O extends Record> ClanInviteTicket(Table<O> path, ForeignKey<O, ClanInviteTicketRecord> childPath, InverseForeignKey<O, ClanInviteTicketRecord> parentPath) {
        super(path, childPath, parentPath, CLAN_INVITE_TICKET);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ClanInviteTicketPath extends ClanInviteTicket implements Path<ClanInviteTicketRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ClanInviteTicketPath(Table<O> path, ForeignKey<O, ClanInviteTicketRecord> childPath, InverseForeignKey<O, ClanInviteTicketRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ClanInviteTicketPath(Name alias, Table<ClanInviteTicketRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ClanInviteTicketPath as(String alias) {
            return new ClanInviteTicketPath(DSL.name(alias), this);
        }

        @Override
        public ClanInviteTicketPath as(Name alias) {
            return new ClanInviteTicketPath(alias, this);
        }

        @Override
        public ClanInviteTicketPath as(Table<?> alias) {
            return new ClanInviteTicketPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_CLAN_INVITE_TICKET_CLAN_ACTIVE, Indexes.IDX_CLAN_INVITE_TICKET_CODE);
    }

    @Override
    public UniqueKey<ClanInviteTicketRecord> getPrimaryKey() {
        return Keys.CLAN_INVITE_TICKET_PKEY;
    }

    @Override
    public List<UniqueKey<ClanInviteTicketRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UQ_CLAN_INVITE_TICKET_CODE);
    }

    @Override
    public List<ForeignKey<ClanInviteTicketRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CLAN_INVITE_TICKET__FK_CLAN_INVITE_TICKET_CLAN);
    }

    private transient ClanInfoPath _clanInfo;

    /**
     * Get the implicit join path to the <code>public.clan_info</code> table.
     */
    public ClanInfoPath clanInfo() {
        if (_clanInfo == null)
            _clanInfo = new ClanInfoPath(this, Keys.CLAN_INVITE_TICKET__FK_CLAN_INVITE_TICKET_CLAN, null);

        return _clanInfo;
    }

    @Override
    public List<Check<ClanInviteTicketRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("chk_clan_invite_ticket_expiry"), "((expires_at > created_at))", true),
            Internal.createCheck(this, DSL.name("chk_clan_invite_ticket_max_uses"), "((max_uses >= 0))", true),
            Internal.createCheck(this, DSL.name("chk_clan_invite_ticket_use_count"), "((use_count >= 0))", true)
        );
    }

    @Override
    public TableField<ClanInviteTicketRecord, Instant> getRecordTimestamp() {
        return UPDATED_AT;
    }

    @Override
    public ClanInviteTicket as(String alias) {
        return new ClanInviteTicket(DSL.name(alias), this);
    }

    @Override
    public ClanInviteTicket as(Name alias) {
        return new ClanInviteTicket(alias, this);
    }

    @Override
    public ClanInviteTicket as(Table<?> alias) {
        return new ClanInviteTicket(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ClanInviteTicket rename(String name) {
        return new ClanInviteTicket(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ClanInviteTicket rename(Name name) {
        return new ClanInviteTicket(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ClanInviteTicket rename(Table<?> name) {
        return new ClanInviteTicket(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClanInviteTicket where(Condition condition) {
        return new ClanInviteTicket(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClanInviteTicket where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClanInviteTicket where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClanInviteTicket where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ClanInviteTicket where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ClanInviteTicket where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ClanInviteTicket where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ClanInviteTicket where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClanInviteTicket whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClanInviteTicket whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
