/*
 * This file is generated by jOOQ.
 */
package com.colombus.clan.jooq.tables;


import com.colombus.clan.jooq.Indexes;
import com.colombus.clan.jooq.Keys;
import com.colombus.clan.jooq.Public;
import com.colombus.clan.jooq.tables.ClanInviteTicket.ClanInviteTicketPath;
import com.colombus.clan.jooq.tables.ClanJoinRequest.ClanJoinRequestPath;
import com.colombus.clan.jooq.tables.ClanMember.ClanMemberPath;
import com.colombus.clan.jooq.tables.records.ClanInfoRecord;
import com.colombus.clan.model.jooq.binding.ClanJoinPolicyBinding;
import com.colombus.clan.model.type.ClanJoinPolicy;
import com.colombus.common.jooq.JsonNodeConverter;
import com.colombus.common.jooq.OffsetDateTimeToInstantConverter;
import com.fasterxml.jackson.databind.JsonNode;

import java.time.Instant;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.DefaultDataType;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.postgres.extensions.bindings.CitextBinding;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ClanInfo extends TableImpl<ClanInfoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.clan_info</code>
     */
    public static final ClanInfo CLAN_INFO = new ClanInfo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ClanInfoRecord> getRecordType() {
        return ClanInfoRecord.class;
    }

    /**
     * The column <code>public.clan_info.id</code>.
     */
    public final TableField<ClanInfoRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.clan_info.handle</code>.
     */
    public final TableField<ClanInfoRecord, String> HANDLE = createField(DSL.name("handle"), DefaultDataType.getDefaultDataType("\"public\".\"citext\"").nullable(false), this, "", new CitextBinding());

    /**
     * The column <code>public.clan_info.name</code>.
     */
    public final TableField<ClanInfoRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.clan_info.description</code>.
     */
    public final TableField<ClanInfoRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.clan_info.owner_id</code>.
     */
    public final TableField<ClanInfoRecord, UUID> OWNER_ID = createField(DSL.name("owner_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.clan_info.join_policy</code>.
     */
    public final TableField<ClanInfoRecord, ClanJoinPolicy> JOIN_POLICY = createField(DSL.name("join_policy"), DefaultDataType.getDefaultDataType("\"public\".\"clan_join_policy_enum\"").nullable(false).defaultValue(DSL.field(DSL.raw("'OPEN'::clan_join_policy_enum"), org.jooq.impl.SQLDataType.OTHER)), this, "", new ClanJoinPolicyBinding());

    /**
     * The column <code>public.clan_info.is_public</code>.
     */
    public final TableField<ClanInfoRecord, Boolean> IS_PUBLIC = createField(DSL.name("is_public"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.clan_info.member_count</code>.
     */
    public final TableField<ClanInfoRecord, Integer> MEMBER_COUNT = createField(DSL.name("member_count"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.clan_info.paint_count_total</code>.
     */
    public final TableField<ClanInfoRecord, Long> PAINT_COUNT_TOTAL = createField(DSL.name("paint_count_total"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.clan_info.metadata</code>.
     */
    public final TableField<ClanInfoRecord, JsonNode> METADATA = createField(DSL.name("metadata"), SQLDataType.JSONB.nullable(false).defaultValue(DSL.field(DSL.raw("'{}'::jsonb"), SQLDataType.JSONB)), this, "", new JsonNodeConverter());

    /**
     * The column <code>public.clan_info.created_at</code>.
     */
    public final TableField<ClanInfoRecord, Instant> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "", new OffsetDateTimeToInstantConverter());

    /**
     * The column <code>public.clan_info.updated_at</code>.
     */
    public final TableField<ClanInfoRecord, Instant> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "", new OffsetDateTimeToInstantConverter());

    /**
     * The column <code>public.clan_info.deleted_at</code>.
     */
    public final TableField<ClanInfoRecord, Instant> DELETED_AT = createField(DSL.name("deleted_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "", new OffsetDateTimeToInstantConverter());

    private ClanInfo(Name alias, Table<ClanInfoRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ClanInfo(Name alias, Table<ClanInfoRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.clan_info</code> table reference
     */
    public ClanInfo(String alias) {
        this(DSL.name(alias), CLAN_INFO);
    }

    /**
     * Create an aliased <code>public.clan_info</code> table reference
     */
    public ClanInfo(Name alias) {
        this(alias, CLAN_INFO);
    }

    /**
     * Create a <code>public.clan_info</code> table reference
     */
    public ClanInfo() {
        this(DSL.name("clan_info"), null);
    }

    public <O extends Record> ClanInfo(Table<O> path, ForeignKey<O, ClanInfoRecord> childPath, InverseForeignKey<O, ClanInfoRecord> parentPath) {
        super(path, childPath, parentPath, CLAN_INFO);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ClanInfoPath extends ClanInfo implements Path<ClanInfoRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ClanInfoPath(Table<O> path, ForeignKey<O, ClanInfoRecord> childPath, InverseForeignKey<O, ClanInfoRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ClanInfoPath(Name alias, Table<ClanInfoRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ClanInfoPath as(String alias) {
            return new ClanInfoPath(DSL.name(alias), this);
        }

        @Override
        public ClanInfoPath as(Name alias) {
            return new ClanInfoPath(alias, this);
        }

        @Override
        public ClanInfoPath as(Table<?> alias) {
            return new ClanInfoPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_CLAN_OWNER_ID_ACTIVE);
    }

    @Override
    public UniqueKey<ClanInfoRecord> getPrimaryKey() {
        return Keys.CLAN_INFO_PKEY;
    }

    @Override
    public List<UniqueKey<ClanInfoRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UQ_CLAN_HANDLE);
    }

    private transient ClanInviteTicketPath _clanInviteTicket;

    /**
     * Get the implicit to-many join path to the
     * <code>public.clan_invite_ticket</code> table
     */
    public ClanInviteTicketPath clanInviteTicket() {
        if (_clanInviteTicket == null)
            _clanInviteTicket = new ClanInviteTicketPath(this, null, Keys.CLAN_INVITE_TICKET__FK_CLAN_INVITE_TICKET_CLAN.getInverseKey());

        return _clanInviteTicket;
    }

    private transient ClanJoinRequestPath _clanJoinRequest;

    /**
     * Get the implicit to-many join path to the
     * <code>public.clan_join_request</code> table
     */
    public ClanJoinRequestPath clanJoinRequest() {
        if (_clanJoinRequest == null)
            _clanJoinRequest = new ClanJoinRequestPath(this, null, Keys.CLAN_JOIN_REQUEST__FK_CLAN_JOIN_REQUEST_CLAN.getInverseKey());

        return _clanJoinRequest;
    }

    private transient ClanMemberPath _clanMember;

    /**
     * Get the implicit to-many join path to the <code>public.clan_member</code>
     * table
     */
    public ClanMemberPath clanMember() {
        if (_clanMember == null)
            _clanMember = new ClanMemberPath(this, null, Keys.CLAN_MEMBER__FK_CLAN_MEMBER_CLAN.getInverseKey());

        return _clanMember;
    }

    @Override
    public List<Check<ClanInfoRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("clan_info_member_count_check"), "((member_count >= 0))", true),
            Internal.createCheck(this, DSL.name("clan_info_paint_count_total_check"), "((paint_count_total >= 0))", true)
        );
    }

    @Override
    public TableField<ClanInfoRecord, Instant> getRecordTimestamp() {
        return UPDATED_AT;
    }

    @Override
    public ClanInfo as(String alias) {
        return new ClanInfo(DSL.name(alias), this);
    }

    @Override
    public ClanInfo as(Name alias) {
        return new ClanInfo(alias, this);
    }

    @Override
    public ClanInfo as(Table<?> alias) {
        return new ClanInfo(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ClanInfo rename(String name) {
        return new ClanInfo(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ClanInfo rename(Name name) {
        return new ClanInfo(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ClanInfo rename(Table<?> name) {
        return new ClanInfo(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClanInfo where(Condition condition) {
        return new ClanInfo(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClanInfo where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClanInfo where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClanInfo where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ClanInfo where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ClanInfo where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ClanInfo where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ClanInfo where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClanInfo whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClanInfo whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
