/*
 * This file is generated by jOOQ.
 */
package com.colombus.clan.jooq.tables;


import com.colombus.clan.jooq.Indexes;
import com.colombus.clan.jooq.Keys;
import com.colombus.clan.jooq.Public;
import com.colombus.clan.jooq.tables.ClanInfo.ClanInfoPath;
import com.colombus.clan.jooq.tables.records.ClanJoinRequestRecord;
import com.colombus.clan.model.jooq.binding.ClanJoinRequestStatusBinding;
import com.colombus.clan.model.type.ClanJoinRequestStatus;
import com.colombus.common.jooq.OffsetDateTimeToInstantConverter;

import java.time.Instant;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.DefaultDataType;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ClanJoinRequest extends TableImpl<ClanJoinRequestRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.clan_join_request</code>
     */
    public static final ClanJoinRequest CLAN_JOIN_REQUEST = new ClanJoinRequest();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ClanJoinRequestRecord> getRecordType() {
        return ClanJoinRequestRecord.class;
    }

    /**
     * The column <code>public.clan_join_request.id</code>.
     */
    public final TableField<ClanJoinRequestRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.clan_join_request.clan_id</code>.
     */
    public final TableField<ClanJoinRequestRecord, UUID> CLAN_ID = createField(DSL.name("clan_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.clan_join_request.user_id</code>.
     */
    public final TableField<ClanJoinRequestRecord, UUID> USER_ID = createField(DSL.name("user_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.clan_join_request.status</code>.
     */
    public final TableField<ClanJoinRequestRecord, ClanJoinRequestStatus> STATUS = createField(DSL.name("status"), DefaultDataType.getDefaultDataType("\"public\".\"clan_join_request_status_enum\"").nullable(false).defaultValue(DSL.field(DSL.raw("'PENDING'::clan_join_request_status_enum"), org.jooq.impl.SQLDataType.OTHER)), this, "", new ClanJoinRequestStatusBinding());

    /**
     * The column <code>public.clan_join_request.message</code>.
     */
    public final TableField<ClanJoinRequestRecord, String> MESSAGE = createField(DSL.name("message"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.clan_join_request.reviewer_id</code>.
     */
    public final TableField<ClanJoinRequestRecord, UUID> REVIEWER_ID = createField(DSL.name("reviewer_id"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.clan_join_request.decided_at</code>.
     */
    public final TableField<ClanJoinRequestRecord, Instant> DECIDED_AT = createField(DSL.name("decided_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "", new OffsetDateTimeToInstantConverter());

    /**
     * The column <code>public.clan_join_request.created_at</code>.
     */
    public final TableField<ClanJoinRequestRecord, Instant> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "", new OffsetDateTimeToInstantConverter());

    /**
     * The column <code>public.clan_join_request.updated_at</code>.
     */
    public final TableField<ClanJoinRequestRecord, Instant> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "", new OffsetDateTimeToInstantConverter());

    /**
     * The column <code>public.clan_join_request.deleted_at</code>.
     */
    public final TableField<ClanJoinRequestRecord, Instant> DELETED_AT = createField(DSL.name("deleted_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "", new OffsetDateTimeToInstantConverter());

    private ClanJoinRequest(Name alias, Table<ClanJoinRequestRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ClanJoinRequest(Name alias, Table<ClanJoinRequestRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.clan_join_request</code> table reference
     */
    public ClanJoinRequest(String alias) {
        this(DSL.name(alias), CLAN_JOIN_REQUEST);
    }

    /**
     * Create an aliased <code>public.clan_join_request</code> table reference
     */
    public ClanJoinRequest(Name alias) {
        this(alias, CLAN_JOIN_REQUEST);
    }

    /**
     * Create a <code>public.clan_join_request</code> table reference
     */
    public ClanJoinRequest() {
        this(DSL.name("clan_join_request"), null);
    }

    public <O extends Record> ClanJoinRequest(Table<O> path, ForeignKey<O, ClanJoinRequestRecord> childPath, InverseForeignKey<O, ClanJoinRequestRecord> parentPath) {
        super(path, childPath, parentPath, CLAN_JOIN_REQUEST);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ClanJoinRequestPath extends ClanJoinRequest implements Path<ClanJoinRequestRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ClanJoinRequestPath(Table<O> path, ForeignKey<O, ClanJoinRequestRecord> childPath, InverseForeignKey<O, ClanJoinRequestRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ClanJoinRequestPath(Name alias, Table<ClanJoinRequestRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ClanJoinRequestPath as(String alias) {
            return new ClanJoinRequestPath(DSL.name(alias), this);
        }

        @Override
        public ClanJoinRequestPath as(Name alias) {
            return new ClanJoinRequestPath(alias, this);
        }

        @Override
        public ClanJoinRequestPath as(Table<?> alias) {
            return new ClanJoinRequestPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_CLAN_JOIN_REQUEST_CLAN, Indexes.IDX_CLAN_JOIN_REQUEST_USER, Indexes.UQ_CLAN_JOIN_REQUEST_PENDING);
    }

    @Override
    public UniqueKey<ClanJoinRequestRecord> getPrimaryKey() {
        return Keys.CLAN_JOIN_REQUEST_PKEY;
    }

    @Override
    public List<ForeignKey<ClanJoinRequestRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CLAN_JOIN_REQUEST__FK_CLAN_JOIN_REQUEST_CLAN);
    }

    private transient ClanInfoPath _clanInfo;

    /**
     * Get the implicit join path to the <code>public.clan_info</code> table.
     */
    public ClanInfoPath clanInfo() {
        if (_clanInfo == null)
            _clanInfo = new ClanInfoPath(this, Keys.CLAN_JOIN_REQUEST__FK_CLAN_JOIN_REQUEST_CLAN, null);

        return _clanInfo;
    }

    @Override
    public TableField<ClanJoinRequestRecord, Instant> getRecordTimestamp() {
        return UPDATED_AT;
    }

    @Override
    public ClanJoinRequest as(String alias) {
        return new ClanJoinRequest(DSL.name(alias), this);
    }

    @Override
    public ClanJoinRequest as(Name alias) {
        return new ClanJoinRequest(alias, this);
    }

    @Override
    public ClanJoinRequest as(Table<?> alias) {
        return new ClanJoinRequest(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ClanJoinRequest rename(String name) {
        return new ClanJoinRequest(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ClanJoinRequest rename(Name name) {
        return new ClanJoinRequest(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ClanJoinRequest rename(Table<?> name) {
        return new ClanJoinRequest(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClanJoinRequest where(Condition condition) {
        return new ClanJoinRequest(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClanJoinRequest where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClanJoinRequest where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClanJoinRequest where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ClanJoinRequest where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ClanJoinRequest where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ClanJoinRequest where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ClanJoinRequest where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClanJoinRequest whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClanJoinRequest whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
