/*
 * This file is generated by jOOQ.
 */
package com.colombus.clan.jooq.tables;


import com.colombus.clan.jooq.Indexes;
import com.colombus.clan.jooq.Keys;
import com.colombus.clan.jooq.Public;
import com.colombus.clan.jooq.tables.ClanInfo.ClanInfoPath;
import com.colombus.clan.jooq.tables.records.ClanMemberRecord;
import com.colombus.clan.model.jooq.binding.ClanMemberRoleBinding;
import com.colombus.clan.model.jooq.binding.ClanMemberStatusBinding;
import com.colombus.clan.model.type.ClanMemberRole;
import com.colombus.clan.model.type.ClanMemberStatus;
import com.colombus.common.jooq.OffsetDateTimeToInstantConverter;

import java.time.Instant;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.DefaultDataType;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ClanMember extends TableImpl<ClanMemberRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.clan_member</code>
     */
    public static final ClanMember CLAN_MEMBER = new ClanMember();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ClanMemberRecord> getRecordType() {
        return ClanMemberRecord.class;
    }

    /**
     * The column <code>public.clan_member.id</code>.
     */
    public final TableField<ClanMemberRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.clan_member.clan_id</code>.
     */
    public final TableField<ClanMemberRecord, UUID> CLAN_ID = createField(DSL.name("clan_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.clan_member.user_id</code>.
     */
    public final TableField<ClanMemberRecord, UUID> USER_ID = createField(DSL.name("user_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.clan_member.role</code>.
     */
    public final TableField<ClanMemberRecord, ClanMemberRole> ROLE = createField(DSL.name("role"), DefaultDataType.getDefaultDataType("\"public\".\"clan_member_role_enum\"").nullable(false).defaultValue(DSL.field(DSL.raw("'MEMBER'::clan_member_role_enum"), org.jooq.impl.SQLDataType.OTHER)), this, "", new ClanMemberRoleBinding());

    /**
     * The column <code>public.clan_member.status</code>.
     */
    public final TableField<ClanMemberRecord, ClanMemberStatus> STATUS = createField(DSL.name("status"), DefaultDataType.getDefaultDataType("\"public\".\"clan_member_status_enum\"").nullable(false).defaultValue(DSL.field(DSL.raw("'ACTIVE'::clan_member_status_enum"), org.jooq.impl.SQLDataType.OTHER)), this, "", new ClanMemberStatusBinding());

    /**
     * The column <code>public.clan_member.paint_count_total</code>.
     */
    public final TableField<ClanMemberRecord, Long> PAINT_COUNT_TOTAL = createField(DSL.name("paint_count_total"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.clan_member.joined_at</code>.
     */
    public final TableField<ClanMemberRecord, Instant> JOINED_AT = createField(DSL.name("joined_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "", new OffsetDateTimeToInstantConverter());

    /**
     * The column <code>public.clan_member.left_at</code>.
     */
    public final TableField<ClanMemberRecord, Instant> LEFT_AT = createField(DSL.name("left_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "", new OffsetDateTimeToInstantConverter());

    /**
     * The column <code>public.clan_member.created_at</code>.
     */
    public final TableField<ClanMemberRecord, Instant> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "", new OffsetDateTimeToInstantConverter());

    /**
     * The column <code>public.clan_member.updated_at</code>.
     */
    public final TableField<ClanMemberRecord, Instant> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "", new OffsetDateTimeToInstantConverter());

    /**
     * The column <code>public.clan_member.deleted_at</code>.
     */
    public final TableField<ClanMemberRecord, Instant> DELETED_AT = createField(DSL.name("deleted_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "", new OffsetDateTimeToInstantConverter());

    private ClanMember(Name alias, Table<ClanMemberRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ClanMember(Name alias, Table<ClanMemberRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.clan_member</code> table reference
     */
    public ClanMember(String alias) {
        this(DSL.name(alias), CLAN_MEMBER);
    }

    /**
     * Create an aliased <code>public.clan_member</code> table reference
     */
    public ClanMember(Name alias) {
        this(alias, CLAN_MEMBER);
    }

    /**
     * Create a <code>public.clan_member</code> table reference
     */
    public ClanMember() {
        this(DSL.name("clan_member"), null);
    }

    public <O extends Record> ClanMember(Table<O> path, ForeignKey<O, ClanMemberRecord> childPath, InverseForeignKey<O, ClanMemberRecord> parentPath) {
        super(path, childPath, parentPath, CLAN_MEMBER);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ClanMemberPath extends ClanMember implements Path<ClanMemberRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ClanMemberPath(Table<O> path, ForeignKey<O, ClanMemberRecord> childPath, InverseForeignKey<O, ClanMemberRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ClanMemberPath(Name alias, Table<ClanMemberRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ClanMemberPath as(String alias) {
            return new ClanMemberPath(DSL.name(alias), this);
        }

        @Override
        public ClanMemberPath as(Name alias) {
            return new ClanMemberPath(alias, this);
        }

        @Override
        public ClanMemberPath as(Table<?> alias) {
            return new ClanMemberPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_CLAN_MEMBER_CLAN_ACTIVE, Indexes.IDX_CLAN_MEMBER_USER_ACTIVE, Indexes.UQ_CLAN_MEMBER_ACTIVE, Indexes.UQ_CLAN_MEMBER_ACTIVE_USER);
    }

    @Override
    public UniqueKey<ClanMemberRecord> getPrimaryKey() {
        return Keys.CLAN_MEMBER_PKEY;
    }

    @Override
    public List<ForeignKey<ClanMemberRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CLAN_MEMBER__FK_CLAN_MEMBER_CLAN);
    }

    private transient ClanInfoPath _clanInfo;

    /**
     * Get the implicit join path to the <code>public.clan_info</code> table.
     */
    public ClanInfoPath clanInfo() {
        if (_clanInfo == null)
            _clanInfo = new ClanInfoPath(this, Keys.CLAN_MEMBER__FK_CLAN_MEMBER_CLAN, null);

        return _clanInfo;
    }

    @Override
    public List<Check<ClanMemberRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("clan_member_paint_count_total_check"), "((paint_count_total >= 0))", true)
        );
    }

    @Override
    public TableField<ClanMemberRecord, Instant> getRecordTimestamp() {
        return UPDATED_AT;
    }

    @Override
    public ClanMember as(String alias) {
        return new ClanMember(DSL.name(alias), this);
    }

    @Override
    public ClanMember as(Name alias) {
        return new ClanMember(alias, this);
    }

    @Override
    public ClanMember as(Table<?> alias) {
        return new ClanMember(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ClanMember rename(String name) {
        return new ClanMember(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ClanMember rename(Name name) {
        return new ClanMember(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ClanMember rename(Table<?> name) {
        return new ClanMember(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClanMember where(Condition condition) {
        return new ClanMember(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClanMember where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClanMember where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClanMember where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ClanMember where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ClanMember where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ClanMember where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ClanMember where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClanMember whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ClanMember whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
