/*
 * This file is generated by jOOQ.
 */
package com.colombus.media.jooq;


import com.colombus.media.jooq.tables.AssetLink;
import com.colombus.media.jooq.tables.ImageAsset;
import com.colombus.media.jooq.tables.OutboxEvent;
import com.colombus.media.jooq.tables.StagingUploadTicket;
import com.colombus.media.jooq.tables.SubjectRegistry;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index IDX_ASSET_LINK_ASSET = Internal.createIndex(DSL.name("idx_asset_link_asset"), AssetLink.ASSET_LINK, new OrderField[] { AssetLink.ASSET_LINK.ASSET_ID }, false);
    public static final Index IDX_ASSET_LINK_SUBJECT = Internal.createIndex(DSL.name("idx_asset_link_subject"), AssetLink.ASSET_LINK, new OrderField[] { AssetLink.ASSET_LINK.SUBJECT_KIND, AssetLink.ASSET_LINK.SUBJECT_ID }, false);
    public static final Index IDX_IMAGE_ASSET_ACTIVE = Internal.createIndex(DSL.name("idx_image_asset_active"), ImageAsset.IMAGE_ASSET, new OrderField[] { ImageAsset.IMAGE_ASSET.IS_ACTIVE }, false);
    public static final Index IDX_IMAGE_ASSET_CONTENT_SHA256 = Internal.createIndex(DSL.name("idx_image_asset_content_sha256"), ImageAsset.IMAGE_ASSET, new OrderField[] { ImageAsset.IMAGE_ASSET.CONTENT_SHA256 }, false);
    public static final Index IDX_IMAGE_ASSET_CREATED_AT = Internal.createIndex(DSL.name("idx_image_asset_created_at"), ImageAsset.IMAGE_ASSET, new OrderField[] { ImageAsset.IMAGE_ASSET.CREATED_AT.desc() }, false);
    public static final Index IDX_OUTBOX_CREATED = Internal.createIndex(DSL.name("idx_outbox_created"), OutboxEvent.OUTBOX_EVENT, new OrderField[] { OutboxEvent.OUTBOX_EVENT.CREATED_AT.desc() }, false);
    public static final Index IDX_STAGING_TICKET_EXPIRES = Internal.createIndex(DSL.name("idx_staging_ticket_expires"), StagingUploadTicket.STAGING_UPLOAD_TICKET, new OrderField[] { StagingUploadTicket.STAGING_UPLOAD_TICKET.EXPIRES_AT }, false);
    public static final Index IDX_STAGING_TICKET_SUBJECT = Internal.createIndex(DSL.name("idx_staging_ticket_subject"), StagingUploadTicket.STAGING_UPLOAD_TICKET, new OrderField[] { StagingUploadTicket.STAGING_UPLOAD_TICKET.SUBJECT_KIND, StagingUploadTicket.STAGING_UPLOAD_TICKET.SUBJECT_ID }, false);
    public static final Index IDX_SUBJECT_REGISTRY_KIND_ALIVE = Internal.createIndex(DSL.name("idx_subject_registry_kind_alive"), SubjectRegistry.SUBJECT_REGISTRY, new OrderField[] { SubjectRegistry.SUBJECT_REGISTRY.KIND, SubjectRegistry.SUBJECT_REGISTRY.ALIVE }, false);
    public static final Index UQ_ASSET_LINK_ACTIVE_ONE_PER_SUBJECT_PURPOSE = Internal.createIndex(DSL.name("uq_asset_link_active_one_per_subject_purpose"), AssetLink.ASSET_LINK, new OrderField[] { AssetLink.ASSET_LINK.SUBJECT_KIND, AssetLink.ASSET_LINK.SUBJECT_ID, AssetLink.ASSET_LINK.PURPOSE }, true);
    public static final Index UQ_OUTBOX_AGGREGATE_VERSION = Internal.createIndex(DSL.name("uq_outbox_aggregate_version"), OutboxEvent.OUTBOX_EVENT, new OrderField[] { OutboxEvent.OUTBOX_EVENT.AGGREGATE, OutboxEvent.OUTBOX_EVENT.AGGREGATE_ID, OutboxEvent.OUTBOX_EVENT.TYPE, OutboxEvent.OUTBOX_EVENT.VERSION }, true);
}
