/*
 * This file is generated by jOOQ.
 */
package com.colombus.media.jooq;


import com.colombus.media.jooq.tables.AssetLink;
import com.colombus.media.jooq.tables.ImageAsset;
import com.colombus.media.jooq.tables.OutboxEvent;
import com.colombus.media.jooq.tables.StagingUploadTicket;
import com.colombus.media.jooq.tables.SubjectRegistry;
import com.colombus.media.jooq.tables.records.AssetLinkRecord;
import com.colombus.media.jooq.tables.records.ImageAssetRecord;
import com.colombus.media.jooq.tables.records.OutboxEventRecord;
import com.colombus.media.jooq.tables.records.StagingUploadTicketRecord;
import com.colombus.media.jooq.tables.records.SubjectRegistryRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.QOM.ForeignKeyRule;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AssetLinkRecord> ASSET_LINK_PKEY = Internal.createUniqueKey(AssetLink.ASSET_LINK, DSL.name("asset_link_pkey"), new TableField[] { AssetLink.ASSET_LINK.ID }, true);
    public static final UniqueKey<ImageAssetRecord> IMAGE_ASSET_PKEY = Internal.createUniqueKey(ImageAsset.IMAGE_ASSET, DSL.name("image_asset_pkey"), new TableField[] { ImageAsset.IMAGE_ASSET.ID }, true);
    public static final UniqueKey<ImageAssetRecord> UQ_IMAGE_ASSET_RAW = Internal.createUniqueKey(ImageAsset.IMAGE_ASSET, DSL.name("uq_image_asset_raw"), new TableField[] { ImageAsset.IMAGE_ASSET.RAW_SHA256 }, true);
    public static final UniqueKey<OutboxEventRecord> OUTBOX_EVENT_PKEY = Internal.createUniqueKey(OutboxEvent.OUTBOX_EVENT, DSL.name("outbox_event_pkey"), new TableField[] { OutboxEvent.OUTBOX_EVENT.ID }, true);
    public static final UniqueKey<StagingUploadTicketRecord> STAGING_UPLOAD_TICKET_PKEY = Internal.createUniqueKey(StagingUploadTicket.STAGING_UPLOAD_TICKET, DSL.name("staging_upload_ticket_pkey"), new TableField[] { StagingUploadTicket.STAGING_UPLOAD_TICKET.ASSET_ID }, true);
    public static final UniqueKey<SubjectRegistryRecord> SUBJECT_REGISTRY_PKEY = Internal.createUniqueKey(SubjectRegistry.SUBJECT_REGISTRY, DSL.name("subject_registry_pkey"), new TableField[] { SubjectRegistry.SUBJECT_REGISTRY.KIND, SubjectRegistry.SUBJECT_REGISTRY.SUBJECT_ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<AssetLinkRecord, ImageAssetRecord> ASSET_LINK__ASSET_LINK_ASSET_ID_FKEY = Internal.createForeignKey(AssetLink.ASSET_LINK, DSL.name("asset_link_asset_id_fkey"), new TableField[] { AssetLink.ASSET_LINK.ASSET_ID }, Keys.IMAGE_ASSET_PKEY, new TableField[] { ImageAsset.IMAGE_ASSET.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<AssetLinkRecord, SubjectRegistryRecord> ASSET_LINK__FK_ASSET_LINK_SUBJECT = Internal.createForeignKey(AssetLink.ASSET_LINK, DSL.name("fk_asset_link_subject"), new TableField[] { AssetLink.ASSET_LINK.SUBJECT_KIND, AssetLink.ASSET_LINK.SUBJECT_ID }, Keys.SUBJECT_REGISTRY_PKEY, new TableField[] { SubjectRegistry.SUBJECT_REGISTRY.KIND, SubjectRegistry.SUBJECT_REGISTRY.SUBJECT_ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<StagingUploadTicketRecord, SubjectRegistryRecord> STAGING_UPLOAD_TICKET__FK_STAGING_SUBJECT = Internal.createForeignKey(StagingUploadTicket.STAGING_UPLOAD_TICKET, DSL.name("fk_staging_subject"), new TableField[] { StagingUploadTicket.STAGING_UPLOAD_TICKET.SUBJECT_KIND, StagingUploadTicket.STAGING_UPLOAD_TICKET.SUBJECT_ID }, Keys.SUBJECT_REGISTRY_PKEY, new TableField[] { SubjectRegistry.SUBJECT_REGISTRY.KIND, SubjectRegistry.SUBJECT_REGISTRY.SUBJECT_ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
}
