/*
 * This file is generated by jOOQ.
 */
package com.colombus.media.jooq;


import com.colombus.media.jooq.tables.AssetLink;
import com.colombus.media.jooq.tables.ImageAsset;
import com.colombus.media.jooq.tables.OutboxEvent;
import com.colombus.media.jooq.tables.StagingUploadTicket;
import com.colombus.media.jooq.tables.SubjectRegistry;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.DSL;
import org.jooq.impl.SchemaImpl;


/**
 * standard public schema
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.asset_link</code>.
     */
    public final AssetLink ASSET_LINK = AssetLink.ASSET_LINK;

    /**
     * The table <code>public.image_asset</code>.
     */
    public final ImageAsset IMAGE_ASSET = ImageAsset.IMAGE_ASSET;

    /**
     * The table <code>public.outbox_event</code>.
     */
    public final OutboxEvent OUTBOX_EVENT = OutboxEvent.OUTBOX_EVENT;

    /**
     * The table <code>public.staging_upload_ticket</code>.
     */
    public final StagingUploadTicket STAGING_UPLOAD_TICKET = StagingUploadTicket.STAGING_UPLOAD_TICKET;

    /**
     * The table <code>public.subject_registry</code>.
     */
    public final SubjectRegistry SUBJECT_REGISTRY = SubjectRegistry.SUBJECT_REGISTRY;

    /**
     * No further instances allowed
     */
    private Public() {
        super(DSL.name("public"), null, DSL.comment("standard public schema"));
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            AssetLink.ASSET_LINK,
            ImageAsset.IMAGE_ASSET,
            OutboxEvent.OUTBOX_EVENT,
            StagingUploadTicket.STAGING_UPLOAD_TICKET,
            SubjectRegistry.SUBJECT_REGISTRY
        );
    }
}
