/*
 * This file is generated by jOOQ.
 */
package com.colombus.media.jooq;


import com.colombus.media.jooq.tables.AssetLink;
import com.colombus.media.jooq.tables.ImageAsset;
import com.colombus.media.jooq.tables.OutboxEvent;
import com.colombus.media.jooq.tables.StagingUploadTicket;
import com.colombus.media.jooq.tables.SubjectRegistry;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.asset_link</code>.
     */
    public static final AssetLink ASSET_LINK = AssetLink.ASSET_LINK;

    /**
     * The table <code>public.image_asset</code>.
     */
    public static final ImageAsset IMAGE_ASSET = ImageAsset.IMAGE_ASSET;

    /**
     * The table <code>public.outbox_event</code>.
     */
    public static final OutboxEvent OUTBOX_EVENT = OutboxEvent.OUTBOX_EVENT;

    /**
     * The table <code>public.staging_upload_ticket</code>.
     */
    public static final StagingUploadTicket STAGING_UPLOAD_TICKET = StagingUploadTicket.STAGING_UPLOAD_TICKET;

    /**
     * The table <code>public.subject_registry</code>.
     */
    public static final SubjectRegistry SUBJECT_REGISTRY = SubjectRegistry.SUBJECT_REGISTRY;
}
