/*
 * This file is generated by jOOQ.
 */
package com.colombus.media.jooq.tables.records;


import com.colombus.common.kafka.subject.model.type.AssetPurpose;
import com.colombus.common.kafka.subject.model.type.SubjectKind;
import com.colombus.media.jooq.tables.AssetLink;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AssetLinkRecord extends UpdatableRecordImpl<AssetLinkRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.asset_link.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.asset_link.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.asset_link.subject_kind</code>.
     */
    public void setSubjectKind(SubjectKind value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.asset_link.subject_kind</code>.
     */
    public SubjectKind getSubjectKind() {
        return (SubjectKind) get(1);
    }

    /**
     * Setter for <code>public.asset_link.subject_id</code>.
     */
    public void setSubjectId(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.asset_link.subject_id</code>.
     */
    public UUID getSubjectId() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>public.asset_link.purpose</code>.
     */
    public void setPurpose(AssetPurpose value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.asset_link.purpose</code>.
     */
    public AssetPurpose getPurpose() {
        return (AssetPurpose) get(3);
    }

    /**
     * Setter for <code>public.asset_link.asset_id</code>.
     */
    public void setAssetId(UUID value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.asset_link.asset_id</code>.
     */
    public UUID getAssetId() {
        return (UUID) get(4);
    }

    /**
     * Setter for <code>public.asset_link.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.asset_link.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(5);
    }

    /**
     * Setter for <code>public.asset_link.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.asset_link.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(6);
    }

    /**
     * Setter for <code>public.asset_link.deleted_at</code>.
     */
    public void setDeletedAt(OffsetDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.asset_link.deleted_at</code>.
     */
    public OffsetDateTime getDeletedAt() {
        return (OffsetDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AssetLinkRecord
     */
    public AssetLinkRecord() {
        super(AssetLink.ASSET_LINK);
    }

    /**
     * Create a detached, initialised AssetLinkRecord
     */
    public AssetLinkRecord(UUID id, SubjectKind subjectKind, UUID subjectId, AssetPurpose purpose, UUID assetId, OffsetDateTime createdAt, OffsetDateTime updatedAt, OffsetDateTime deletedAt) {
        super(AssetLink.ASSET_LINK);

        setId(id);
        setSubjectKind(subjectKind);
        setSubjectId(subjectId);
        setPurpose(purpose);
        setAssetId(assetId);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setDeletedAt(deletedAt);
        resetTouchedOnNotNull();
    }
}
