/*
 * This file is generated by jOOQ.
 */
package com.colombus.media.jooq.tables.records;


import com.colombus.media.jooq.tables.ImageAsset;
import com.fasterxml.jackson.databind.JsonNode;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ImageAssetRecord extends UpdatableRecordImpl<ImageAssetRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.image_asset.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.image_asset.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.image_asset.raw_sha256</code>.
     */
    public void setRawSha256(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.image_asset.raw_sha256</code>.
     */
    public String getRawSha256() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.image_asset.content_sha256</code>.
     */
    public void setContentSha256(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.image_asset.content_sha256</code>.
     */
    public String getContentSha256() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.image_asset.content_type</code>.
     */
    public void setContentType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.image_asset.content_type</code>.
     */
    public String getContentType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.image_asset.width</code>.
     */
    public void setWidth(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.image_asset.width</code>.
     */
    public Integer getWidth() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.image_asset.height</code>.
     */
    public void setHeight(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.image_asset.height</code>.
     */
    public Integer getHeight() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.image_asset.size_bytes</code>.
     */
    public void setSizeBytes(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.image_asset.size_bytes</code>.
     */
    public Long getSizeBytes() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>public.image_asset.storage_bucket</code>.
     */
    public void setStorageBucket(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.image_asset.storage_bucket</code>.
     */
    public String getStorageBucket() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.image_asset.storage_key</code>.
     */
    public void setStorageKey(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.image_asset.storage_key</code>.
     */
    public String getStorageKey() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.image_asset.public_url</code>.
     */
    public void setPublicUrl(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.image_asset.public_url</code>.
     */
    public String getPublicUrl() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.image_asset.exif</code>.
     */
    public void setExif(JsonNode value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.image_asset.exif</code>.
     */
    public JsonNode getExif() {
        return (JsonNode) get(10);
    }

    /**
     * Setter for <code>public.image_asset.is_active</code>.
     */
    public void setIsActive(Boolean value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.image_asset.is_active</code>.
     */
    public Boolean getIsActive() {
        return (Boolean) get(11);
    }

    /**
     * Setter for <code>public.image_asset.blocked_at</code>.
     */
    public void setBlockedAt(OffsetDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.image_asset.blocked_at</code>.
     */
    public OffsetDateTime getBlockedAt() {
        return (OffsetDateTime) get(12);
    }

    /**
     * Setter for <code>public.image_asset.blocked_reason</code>.
     */
    public void setBlockedReason(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.image_asset.blocked_reason</code>.
     */
    public String getBlockedReason() {
        return (String) get(13);
    }

    /**
     * Setter for <code>public.image_asset.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.image_asset.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(14);
    }

    /**
     * Setter for <code>public.image_asset.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.image_asset.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(15);
    }

    /**
     * Setter for <code>public.image_asset.deleted_at</code>.
     */
    public void setDeletedAt(OffsetDateTime value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.image_asset.deleted_at</code>.
     */
    public OffsetDateTime getDeletedAt() {
        return (OffsetDateTime) get(16);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ImageAssetRecord
     */
    public ImageAssetRecord() {
        super(ImageAsset.IMAGE_ASSET);
    }

    /**
     * Create a detached, initialised ImageAssetRecord
     */
    public ImageAssetRecord(UUID id, String rawSha256, String contentSha256, String contentType, Integer width, Integer height, Long sizeBytes, String storageBucket, String storageKey, String publicUrl, JsonNode exif, Boolean isActive, OffsetDateTime blockedAt, String blockedReason, OffsetDateTime createdAt, OffsetDateTime updatedAt, OffsetDateTime deletedAt) {
        super(ImageAsset.IMAGE_ASSET);

        setId(id);
        setRawSha256(rawSha256);
        setContentSha256(contentSha256);
        setContentType(contentType);
        setWidth(width);
        setHeight(height);
        setSizeBytes(sizeBytes);
        setStorageBucket(storageBucket);
        setStorageKey(storageKey);
        setPublicUrl(publicUrl);
        setExif(exif);
        setIsActive(isActive);
        setBlockedAt(blockedAt);
        setBlockedReason(blockedReason);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setDeletedAt(deletedAt);
        resetTouchedOnNotNull();
    }
}
