/*
 * This file is generated by jOOQ.
 */
package com.colombus.media.jooq.tables.records;


import com.colombus.common.kafka.subject.model.type.AssetPurpose;
import com.colombus.common.kafka.subject.model.type.SubjectKind;
import com.colombus.media.jooq.tables.StagingUploadTicket;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class StagingUploadTicketRecord extends UpdatableRecordImpl<StagingUploadTicketRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.staging_upload_ticket.asset_id</code>.
     */
    public void setAssetId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.staging_upload_ticket.asset_id</code>.
     */
    public UUID getAssetId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.staging_upload_ticket.subject_kind</code>.
     */
    public void setSubjectKind(SubjectKind value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.staging_upload_ticket.subject_kind</code>.
     */
    public SubjectKind getSubjectKind() {
        return (SubjectKind) get(1);
    }

    /**
     * Setter for <code>public.staging_upload_ticket.subject_id</code>.
     */
    public void setSubjectId(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.staging_upload_ticket.subject_id</code>.
     */
    public UUID getSubjectId() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>public.staging_upload_ticket.purpose</code>.
     */
    public void setPurpose(AssetPurpose value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.staging_upload_ticket.purpose</code>.
     */
    public AssetPurpose getPurpose() {
        return (AssetPurpose) get(3);
    }

    /**
     * Setter for <code>public.staging_upload_ticket.s3_key</code>.
     */
    public void setS3Key(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.staging_upload_ticket.s3_key</code>.
     */
    public String getS3Key() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.staging_upload_ticket.expires_at</code>.
     */
    public void setExpiresAt(OffsetDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.staging_upload_ticket.expires_at</code>.
     */
    public OffsetDateTime getExpiresAt() {
        return (OffsetDateTime) get(5);
    }

    /**
     * Setter for <code>public.staging_upload_ticket.status</code>.
     */
    public void setStatus(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.staging_upload_ticket.status</code>.
     */
    public String getStatus() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.staging_upload_ticket.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.staging_upload_ticket.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(7);
    }

    /**
     * Setter for <code>public.staging_upload_ticket.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.staging_upload_ticket.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(8);
    }

    /**
     * Setter for <code>public.staging_upload_ticket.used_at</code>.
     */
    public void setUsedAt(OffsetDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.staging_upload_ticket.used_at</code>.
     */
    public OffsetDateTime getUsedAt() {
        return (OffsetDateTime) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StagingUploadTicketRecord
     */
    public StagingUploadTicketRecord() {
        super(StagingUploadTicket.STAGING_UPLOAD_TICKET);
    }

    /**
     * Create a detached, initialised StagingUploadTicketRecord
     */
    public StagingUploadTicketRecord(UUID assetId, SubjectKind subjectKind, UUID subjectId, AssetPurpose purpose, String s3Key, OffsetDateTime expiresAt, String status, OffsetDateTime createdAt, OffsetDateTime updatedAt, OffsetDateTime usedAt) {
        super(StagingUploadTicket.STAGING_UPLOAD_TICKET);

        setAssetId(assetId);
        setSubjectKind(subjectKind);
        setSubjectId(subjectId);
        setPurpose(purpose);
        setS3Key(s3Key);
        setExpiresAt(expiresAt);
        setStatus(status);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setUsedAt(usedAt);
        resetTouchedOnNotNull();
    }
}
