/*
 * This file is generated by jOOQ.
 */
package com.colombus.media.jooq.tables.records;


import com.colombus.common.kafka.subject.model.type.SubjectKind;
import com.colombus.media.jooq.tables.SubjectRegistry;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SubjectRegistryRecord extends UpdatableRecordImpl<SubjectRegistryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.subject_registry.kind</code>.
     */
    public void setKind(SubjectKind value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.subject_registry.kind</code>.
     */
    public SubjectKind getKind() {
        return (SubjectKind) get(0);
    }

    /**
     * Setter for <code>public.subject_registry.subject_id</code>.
     */
    public void setSubjectId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.subject_registry.subject_id</code>.
     */
    public UUID getSubjectId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.subject_registry.alive</code>.
     */
    public void setAlive(Boolean value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.subject_registry.alive</code>.
     */
    public Boolean getAlive() {
        return (Boolean) get(2);
    }

    /**
     * Setter for <code>public.subject_registry.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.subject_registry.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(3);
    }

    /**
     * Setter for <code>public.subject_registry.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.subject_registry.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<SubjectKind, UUID> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SubjectRegistryRecord
     */
    public SubjectRegistryRecord() {
        super(SubjectRegistry.SUBJECT_REGISTRY);
    }

    /**
     * Create a detached, initialised SubjectRegistryRecord
     */
    public SubjectRegistryRecord(SubjectKind kind, UUID subjectId, Boolean alive, OffsetDateTime createdAt, OffsetDateTime updatedAt) {
        super(SubjectRegistry.SUBJECT_REGISTRY);

        setKind(kind);
        setSubjectId(subjectId);
        setAlive(alive);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetTouchedOnNotNull();
    }
}
