/*
 * This file is generated by jOOQ.
 */
package com.colombus.user.jooq.tables;


import com.colombus.common.jooq.OffsetDateTimeToInstantConverter;
import com.colombus.user.jooq.Indexes;
import com.colombus.user.jooq.Keys;
import com.colombus.user.jooq.Public;
import com.colombus.user.jooq.tables.UserAccount.UserAccountPath;
import com.colombus.user.jooq.tables.records.AuthEventRecord;
import com.colombus.user.model.jooq.binding.AuthEventKindBinding;
import com.colombus.user.model.jooq.binding.AuthProviderBinding;
import com.colombus.user.model.type.AuthEventKind;
import com.colombus.user.model.type.AuthProvider;

import java.time.Instant;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.DefaultDataType;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.postgres.extensions.bindings.InetBinding;
import org.jooq.postgres.extensions.types.Inet;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AuthEvent extends TableImpl<AuthEventRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.auth_event</code>
     */
    public static final AuthEvent AUTH_EVENT = new AuthEvent();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AuthEventRecord> getRecordType() {
        return AuthEventRecord.class;
    }

    /**
     * The column <code>public.auth_event.id</code>.
     */
    public final TableField<AuthEventRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("uuidv7()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.auth_event.user_id</code>.
     */
    public final TableField<AuthEventRecord, UUID> USER_ID = createField(DSL.name("user_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.auth_event.provider</code>.
     */
    public final TableField<AuthEventRecord, AuthProvider> PROVIDER = createField(DSL.name("provider"), DefaultDataType.getDefaultDataType("\"public\".\"auth_provider\""), this, "", new AuthProviderBinding());

    /**
     * The column <code>public.auth_event.kind</code>.
     */
    public final TableField<AuthEventRecord, AuthEventKind> KIND = createField(DSL.name("kind"), DefaultDataType.getDefaultDataType("\"public\".\"auth_event_kind\"").nullable(false), this, "", new AuthEventKindBinding());

    /**
     * The column <code>public.auth_event.detail</code>.
     */
    public final TableField<AuthEventRecord, String> DETAIL = createField(DSL.name("detail"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.auth_event.ip_addr</code>.
     */
    public final TableField<AuthEventRecord, Inet> IP_ADDR = createField(DSL.name("ip_addr"), DefaultDataType.getDefaultDataType("\"pg_catalog\".\"inet\""), this, "", new InetBinding());

    /**
     * The column <code>public.auth_event.user_agent</code>.
     */
    public final TableField<AuthEventRecord, String> USER_AGENT = createField(DSL.name("user_agent"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.auth_event.created_at</code>.
     */
    public final TableField<AuthEventRecord, Instant> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "", new OffsetDateTimeToInstantConverter());

    /**
     * The column <code>public.auth_event.updated_at</code>.
     */
    public final TableField<AuthEventRecord, Instant> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "", new OffsetDateTimeToInstantConverter());

    /**
     * The column <code>public.auth_event.deleted_at</code>.
     */
    public final TableField<AuthEventRecord, Instant> DELETED_AT = createField(DSL.name("deleted_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "", new OffsetDateTimeToInstantConverter());

    private AuthEvent(Name alias, Table<AuthEventRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AuthEvent(Name alias, Table<AuthEventRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.auth_event</code> table reference
     */
    public AuthEvent(String alias) {
        this(DSL.name(alias), AUTH_EVENT);
    }

    /**
     * Create an aliased <code>public.auth_event</code> table reference
     */
    public AuthEvent(Name alias) {
        this(alias, AUTH_EVENT);
    }

    /**
     * Create a <code>public.auth_event</code> table reference
     */
    public AuthEvent() {
        this(DSL.name("auth_event"), null);
    }

    public <O extends Record> AuthEvent(Table<O> path, ForeignKey<O, AuthEventRecord> childPath, InverseForeignKey<O, AuthEventRecord> parentPath) {
        super(path, childPath, parentPath, AUTH_EVENT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class AuthEventPath extends AuthEvent implements Path<AuthEventRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> AuthEventPath(Table<O> path, ForeignKey<O, AuthEventRecord> childPath, InverseForeignKey<O, AuthEventRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private AuthEventPath(Name alias, Table<AuthEventRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public AuthEventPath as(String alias) {
            return new AuthEventPath(DSL.name(alias), this);
        }

        @Override
        public AuthEventPath as(Name alias) {
            return new AuthEventPath(alias, this);
        }

        @Override
        public AuthEventPath as(Table<?> alias) {
            return new AuthEventPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_AUTH_EVENT_KIND_TIME, Indexes.IDX_AUTH_EVENT_PROVIDER_TIME, Indexes.IDX_AUTH_EVENT_UUID);
    }

    @Override
    public UniqueKey<AuthEventRecord> getPrimaryKey() {
        return Keys.AUTH_EVENT_PKEY;
    }

    @Override
    public List<ForeignKey<AuthEventRecord, ?>> getReferences() {
        return Arrays.asList(Keys.AUTH_EVENT__AUTH_EVENT_USER_ID_FKEY);
    }

    private transient UserAccountPath _userAccount;

    /**
     * Get the implicit join path to the <code>public.user_account</code> table.
     */
    public UserAccountPath userAccount() {
        if (_userAccount == null)
            _userAccount = new UserAccountPath(this, Keys.AUTH_EVENT__AUTH_EVENT_USER_ID_FKEY, null);

        return _userAccount;
    }

    @Override
    public TableField<AuthEventRecord, Instant> getRecordTimestamp() {
        return UPDATED_AT;
    }

    @Override
    public AuthEvent as(String alias) {
        return new AuthEvent(DSL.name(alias), this);
    }

    @Override
    public AuthEvent as(Name alias) {
        return new AuthEvent(alias, this);
    }

    @Override
    public AuthEvent as(Table<?> alias) {
        return new AuthEvent(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AuthEvent rename(String name) {
        return new AuthEvent(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AuthEvent rename(Name name) {
        return new AuthEvent(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AuthEvent rename(Table<?> name) {
        return new AuthEvent(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuthEvent where(Condition condition) {
        return new AuthEvent(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuthEvent where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuthEvent where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuthEvent where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AuthEvent where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AuthEvent where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AuthEvent where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AuthEvent where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuthEvent whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuthEvent whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
