/*
 * This file is generated by jOOQ.
 */
package com.colombus.user.jooq.tables;


import com.colombus.user.jooq.Keys;
import com.colombus.user.jooq.Public;
import com.colombus.user.jooq.tables.records.NicknameSeriesRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class NicknameSeries extends TableImpl<NicknameSeriesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.nickname_series</code>
     */
    public static final NicknameSeries NICKNAME_SERIES = new NicknameSeries();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<NicknameSeriesRecord> getRecordType() {
        return NicknameSeriesRecord.class;
    }

    /**
     * The column <code>public.nickname_series.nickname</code>.
     */
    public final TableField<NicknameSeriesRecord, String> NICKNAME = createField(DSL.name("nickname"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.nickname_series.next_seq</code>.
     */
    public final TableField<NicknameSeriesRecord, Integer> NEXT_SEQ = createField(DSL.name("next_seq"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("1"), SQLDataType.INTEGER)), this, "");

    private NicknameSeries(Name alias, Table<NicknameSeriesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private NicknameSeries(Name alias, Table<NicknameSeriesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.nickname_series</code> table reference
     */
    public NicknameSeries(String alias) {
        this(DSL.name(alias), NICKNAME_SERIES);
    }

    /**
     * Create an aliased <code>public.nickname_series</code> table reference
     */
    public NicknameSeries(Name alias) {
        this(alias, NICKNAME_SERIES);
    }

    /**
     * Create a <code>public.nickname_series</code> table reference
     */
    public NicknameSeries() {
        this(DSL.name("nickname_series"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<NicknameSeriesRecord> getPrimaryKey() {
        return Keys.NICKNAME_SERIES_PKEY;
    }

    @Override
    public NicknameSeries as(String alias) {
        return new NicknameSeries(DSL.name(alias), this);
    }

    @Override
    public NicknameSeries as(Name alias) {
        return new NicknameSeries(alias, this);
    }

    @Override
    public NicknameSeries as(Table<?> alias) {
        return new NicknameSeries(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public NicknameSeries rename(String name) {
        return new NicknameSeries(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public NicknameSeries rename(Name name) {
        return new NicknameSeries(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public NicknameSeries rename(Table<?> name) {
        return new NicknameSeries(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NicknameSeries where(Condition condition) {
        return new NicknameSeries(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NicknameSeries where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NicknameSeries where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NicknameSeries where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public NicknameSeries where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public NicknameSeries where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public NicknameSeries where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public NicknameSeries where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NicknameSeries whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public NicknameSeries whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
