/*
 * This file is generated by jOOQ.
 */
package com.colombus.user.jooq.tables;


import com.colombus.common.domain.outbox.model.type.OutboxStatus;
import com.colombus.common.jooq.JsonNodeConverter;
import com.colombus.common.jooq.OffsetDateTimeToInstantConverter;
import com.colombus.user.jooq.Indexes;
import com.colombus.user.jooq.Keys;
import com.colombus.user.jooq.Public;
import com.colombus.user.jooq.tables.records.OutboxEventRecord;
import com.fasterxml.jackson.databind.JsonNode;

import java.time.Instant;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.DefaultDataType;
import org.jooq.impl.EnumConverter;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OutboxEvent extends TableImpl<OutboxEventRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.outbox_event</code>
     */
    public static final OutboxEvent OUTBOX_EVENT = new OutboxEvent();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OutboxEventRecord> getRecordType() {
        return OutboxEventRecord.class;
    }

    /**
     * The column <code>public.outbox_event.id</code>.
     */
    public final TableField<OutboxEventRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("uuidv7()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.outbox_event.aggregate</code>.
     */
    public final TableField<OutboxEventRecord, String> AGGREGATE = createField(DSL.name("aggregate"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.outbox_event.aggregate_id</code>.
     */
    public final TableField<OutboxEventRecord, UUID> AGGREGATE_ID = createField(DSL.name("aggregate_id"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.outbox_event.type</code>.
     */
    public final TableField<OutboxEventRecord, String> TYPE = createField(DSL.name("type"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.outbox_event.version</code>.
     */
    public final TableField<OutboxEventRecord, Long> VERSION = createField(DSL.name("version"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.outbox_event.payload</code>.
     */
    public final TableField<OutboxEventRecord, JsonNode> PAYLOAD = createField(DSL.name("payload"), SQLDataType.JSONB.nullable(false), this, "", new JsonNodeConverter());

    /**
     * The column <code>public.outbox_event.headers</code>.
     */
    public final TableField<OutboxEventRecord, JsonNode> HEADERS = createField(DSL.name("headers"), SQLDataType.JSONB.nullable(false).defaultValue(DSL.field(DSL.raw("'{}'::jsonb"), SQLDataType.JSONB)), this, "", new JsonNodeConverter());

    /**
     * The column <code>public.outbox_event.status</code>.
     */
    public final TableField<OutboxEventRecord, OutboxStatus> STATUS = createField(DSL.name("status"), DefaultDataType.getDefaultDataType("\"public\".\"outbox_status\"").nullable(false).defaultValue(DSL.field(DSL.raw("'PENDING'::outbox_status"), org.jooq.impl.SQLDataType.OTHER)), this, "", new EnumConverter<Object, OutboxStatus>(Object.class, OutboxStatus.class));

    /**
     * The column <code>public.outbox_event.attempts</code>.
     */
    public final TableField<OutboxEventRecord, Integer> ATTEMPTS = createField(DSL.name("attempts"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.outbox_event.last_error</code>.
     */
    public final TableField<OutboxEventRecord, String> LAST_ERROR = createField(DSL.name("last_error"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.outbox_event.next_attempt_at</code>.
     */
    public final TableField<OutboxEventRecord, Instant> NEXT_ATTEMPT_AT = createField(DSL.name("next_attempt_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "", new OffsetDateTimeToInstantConverter());

    /**
     * The column <code>public.outbox_event.locked_by</code>.
     */
    public final TableField<OutboxEventRecord, String> LOCKED_BY = createField(DSL.name("locked_by"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.outbox_event.locked_until</code>.
     */
    public final TableField<OutboxEventRecord, OffsetDateTime> LOCKED_UNTIL = createField(DSL.name("locked_until"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.outbox_event.created_at</code>.
     */
    public final TableField<OutboxEventRecord, Instant> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "", new OffsetDateTimeToInstantConverter());

    /**
     * The column <code>public.outbox_event.updated_at</code>.
     */
    public final TableField<OutboxEventRecord, Instant> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "", new OffsetDateTimeToInstantConverter());

    /**
     * The column <code>public.outbox_event.published_at</code>.
     */
    public final TableField<OutboxEventRecord, Instant> PUBLISHED_AT = createField(DSL.name("published_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "", new OffsetDateTimeToInstantConverter());

    /**
     * The column <code>public.outbox_event.deleted_at</code>.
     */
    public final TableField<OutboxEventRecord, Instant> DELETED_AT = createField(DSL.name("deleted_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "", new OffsetDateTimeToInstantConverter());

    private OutboxEvent(Name alias, Table<OutboxEventRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private OutboxEvent(Name alias, Table<OutboxEventRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.outbox_event</code> table reference
     */
    public OutboxEvent(String alias) {
        this(DSL.name(alias), OUTBOX_EVENT);
    }

    /**
     * Create an aliased <code>public.outbox_event</code> table reference
     */
    public OutboxEvent(Name alias) {
        this(alias, OUTBOX_EVENT);
    }

    /**
     * Create a <code>public.outbox_event</code> table reference
     */
    public OutboxEvent() {
        this(DSL.name("outbox_event"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_OUTBOX_CREATED, Indexes.UQ_OUTBOX_AGGREGATE_VERSION);
    }

    @Override
    public UniqueKey<OutboxEventRecord> getPrimaryKey() {
        return Keys.OUTBOX_EVENT_PKEY;
    }

    @Override
    public List<Check<OutboxEventRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("chk_outbox_processing_has_lock"), "(((status <> 'PROCESSING'::outbox_status) OR ((locked_until IS NOT NULL) AND (locked_by IS NOT NULL))))", true)
        );
    }

    @Override
    public TableField<OutboxEventRecord, Instant> getRecordTimestamp() {
        return UPDATED_AT;
    }

    @Override
    public OutboxEvent as(String alias) {
        return new OutboxEvent(DSL.name(alias), this);
    }

    @Override
    public OutboxEvent as(Name alias) {
        return new OutboxEvent(alias, this);
    }

    @Override
    public OutboxEvent as(Table<?> alias) {
        return new OutboxEvent(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public OutboxEvent rename(String name) {
        return new OutboxEvent(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public OutboxEvent rename(Name name) {
        return new OutboxEvent(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public OutboxEvent rename(Table<?> name) {
        return new OutboxEvent(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OutboxEvent where(Condition condition) {
        return new OutboxEvent(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OutboxEvent where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OutboxEvent where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OutboxEvent where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OutboxEvent where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OutboxEvent where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OutboxEvent where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OutboxEvent where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OutboxEvent whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OutboxEvent whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
