/*
 * This file is generated by jOOQ.
 */
package com.colombus.user.jooq.tables;


import com.colombus.common.jooq.JsonNodeConverter;
import com.colombus.common.jooq.OffsetDateTimeToInstantConverter;
import com.colombus.user.jooq.Indexes;
import com.colombus.user.jooq.Keys;
import com.colombus.user.jooq.Public;
import com.colombus.user.jooq.tables.AuthEvent.AuthEventPath;
import com.colombus.user.jooq.tables.UserIdentity.UserIdentityPath;
import com.colombus.user.jooq.tables.records.UserAccountRecord;
import com.colombus.user.model.jooq.converter.AccountRoleListConverter;
import com.colombus.user.model.type.AccountRole;
import com.fasterxml.jackson.databind.JsonNode;

import java.time.Instant;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.DefaultDataType;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.postgres.extensions.bindings.CitextBinding;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserAccount extends TableImpl<UserAccountRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.user_account</code>
     */
    public static final UserAccount USER_ACCOUNT = new UserAccount();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserAccountRecord> getRecordType() {
        return UserAccountRecord.class;
    }

    /**
     * The column <code>public.user_account.id</code>.
     */
    public final TableField<UserAccountRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.user_account.email</code>.
     */
    public final TableField<UserAccountRecord, String> EMAIL = createField(DSL.name("email"), DefaultDataType.getDefaultDataType("\"public\".\"citext\""), this, "", new CitextBinding());

    /**
     * The column <code>public.user_account.nickname</code>.
     */
    public final TableField<UserAccountRecord, String> NICKNAME = createField(DSL.name("nickname"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.user_account.nickname_seq</code>.
     */
    public final TableField<UserAccountRecord, Integer> NICKNAME_SEQ = createField(DSL.name("nickname_seq"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.user_account.nickname_handle</code>.
     */
    public final TableField<UserAccountRecord, String> NICKNAME_HANDLE = createField(DSL.name("nickname_handle"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.user_account.roles</code>.
     */
    public final TableField<UserAccountRecord, List<AccountRole>> ROLES = createField(DSL.name("roles"), DefaultDataType.getDefaultDataType("\"public\".\"account_role\"").array().nullable(false).defaultValue(DSL.field(DSL.raw("ARRAY['USER'::account_role]"), org.jooq.impl.SQLDataType.OTHER.array())), this, "", new AccountRoleListConverter());

    /**
     * The column <code>public.user_account.is_active</code>.
     */
    public final TableField<UserAccountRecord, Boolean> IS_ACTIVE = createField(DSL.name("is_active"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.user_account.email_verified</code>.
     */
    public final TableField<UserAccountRecord, Boolean> EMAIL_VERIFIED = createField(DSL.name("email_verified"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.user_account.paint_count_total</code>.
     */
    public final TableField<UserAccountRecord, Long> PAINT_COUNT_TOTAL = createField(DSL.name("paint_count_total"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.user_account.metadata</code>.
     */
    public final TableField<UserAccountRecord, JsonNode> METADATA = createField(DSL.name("metadata"), SQLDataType.JSONB.nullable(false).defaultValue(DSL.field(DSL.raw("'{}'::jsonb"), SQLDataType.JSONB)), this, "", new JsonNodeConverter());

    /**
     * The column <code>public.user_account.last_login_at</code>.
     */
    public final TableField<UserAccountRecord, Instant> LAST_LOGIN_AT = createField(DSL.name("last_login_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "", new OffsetDateTimeToInstantConverter());

    /**
     * The column <code>public.user_account.login_count</code>.
     */
    public final TableField<UserAccountRecord, Long> LOGIN_COUNT = createField(DSL.name("login_count"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.user_account.blocked_at</code>.
     */
    public final TableField<UserAccountRecord, Instant> BLOCKED_AT = createField(DSL.name("blocked_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "", new OffsetDateTimeToInstantConverter());

    /**
     * The column <code>public.user_account.blocked_reason</code>.
     */
    public final TableField<UserAccountRecord, String> BLOCKED_REASON = createField(DSL.name("blocked_reason"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.user_account.created_at</code>.
     */
    public final TableField<UserAccountRecord, Instant> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "", new OffsetDateTimeToInstantConverter());

    /**
     * The column <code>public.user_account.updated_at</code>.
     */
    public final TableField<UserAccountRecord, Instant> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "", new OffsetDateTimeToInstantConverter());

    /**
     * The column <code>public.user_account.deleted_at</code>.
     */
    public final TableField<UserAccountRecord, Instant> DELETED_AT = createField(DSL.name("deleted_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "", new OffsetDateTimeToInstantConverter());

    private UserAccount(Name alias, Table<UserAccountRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private UserAccount(Name alias, Table<UserAccountRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.user_account</code> table reference
     */
    public UserAccount(String alias) {
        this(DSL.name(alias), USER_ACCOUNT);
    }

    /**
     * Create an aliased <code>public.user_account</code> table reference
     */
    public UserAccount(Name alias) {
        this(alias, USER_ACCOUNT);
    }

    /**
     * Create a <code>public.user_account</code> table reference
     */
    public UserAccount() {
        this(DSL.name("user_account"), null);
    }

    public <O extends Record> UserAccount(Table<O> path, ForeignKey<O, UserAccountRecord> childPath, InverseForeignKey<O, UserAccountRecord> parentPath) {
        super(path, childPath, parentPath, USER_ACCOUNT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class UserAccountPath extends UserAccount implements Path<UserAccountRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> UserAccountPath(Table<O> path, ForeignKey<O, UserAccountRecord> childPath, InverseForeignKey<O, UserAccountRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private UserAccountPath(Name alias, Table<UserAccountRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public UserAccountPath as(String alias) {
            return new UserAccountPath(DSL.name(alias), this);
        }

        @Override
        public UserAccountPath as(Name alias) {
            return new UserAccountPath(alias, this);
        }

        @Override
        public UserAccountPath as(Table<?> alias) {
            return new UserAccountPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_USER_ACCOUNT_CREATED_AT, Indexes.IDX_USER_ACCOUNT_LAST_LOGIN, Indexes.IDX_USER_ACCOUNT_METADATA_GIN, Indexes.IDX_USER_ACCOUNT_ROLES_GIN, Indexes.UQ_USER_ACCOUNT_EMAIL_ALIVE);
    }

    @Override
    public UniqueKey<UserAccountRecord> getPrimaryKey() {
        return Keys.USER_ACCOUNT_PKEY;
    }

    private transient AuthEventPath _authEvent;

    /**
     * Get the implicit to-many join path to the <code>public.auth_event</code>
     * table
     */
    public AuthEventPath authEvent() {
        if (_authEvent == null)
            _authEvent = new AuthEventPath(this, null, Keys.AUTH_EVENT__AUTH_EVENT_USER_ID_FKEY.getInverseKey());

        return _authEvent;
    }

    private transient UserIdentityPath _userIdentity;

    /**
     * Get the implicit to-many join path to the
     * <code>public.user_identity</code> table
     */
    public UserIdentityPath userIdentity() {
        if (_userIdentity == null)
            _userIdentity = new UserIdentityPath(this, null, Keys.USER_IDENTITY__USER_IDENTITY_USER_ID_FKEY.getInverseKey());

        return _userIdentity;
    }

    @Override
    public List<Check<UserAccountRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("chk_deleted_means_inactive"), "(((deleted_at IS NULL) OR (is_active = false)))", true),
            Internal.createCheck(this, DSL.name("chk_email_verified_requires_email"), "(((NOT email_verified) OR (email IS NOT NULL)))", true),
            Internal.createCheck(this, DSL.name("chk_nickname_seq_range"), "(((nickname_seq >= 0) AND (nickname_seq <= 9999)))", true),
            Internal.createCheck(this, DSL.name("chk_nickname_seq_requires_nickname"), "(((nickname_seq IS NULL) OR (nickname IS NOT NULL)))", true),
            Internal.createCheck(this, DSL.name("chk_roles_canonical_and_not_empty"), "(((roles = normalize_account_roles(roles)) AND (array_length(roles, 1) >= 1)))", true),
            Internal.createCheck(this, DSL.name("user_account_paint_count_total_check"), "((paint_count_total >= 0))", true)
        );
    }

    @Override
    public TableField<UserAccountRecord, Instant> getRecordTimestamp() {
        return UPDATED_AT;
    }

    @Override
    public UserAccount as(String alias) {
        return new UserAccount(DSL.name(alias), this);
    }

    @Override
    public UserAccount as(Name alias) {
        return new UserAccount(alias, this);
    }

    @Override
    public UserAccount as(Table<?> alias) {
        return new UserAccount(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserAccount rename(String name) {
        return new UserAccount(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserAccount rename(Name name) {
        return new UserAccount(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserAccount rename(Table<?> name) {
        return new UserAccount(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserAccount where(Condition condition) {
        return new UserAccount(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserAccount where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserAccount where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserAccount where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserAccount where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserAccount where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserAccount where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserAccount where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserAccount whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserAccount whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
