/*
 * This file is generated by jOOQ.
 */
package com.colombus.user.jooq.tables;


import com.colombus.common.jooq.OffsetDateTimeToInstantConverter;
import com.colombus.user.jooq.Indexes;
import com.colombus.user.jooq.Keys;
import com.colombus.user.jooq.Public;
import com.colombus.user.jooq.tables.UserAccount.UserAccountPath;
import com.colombus.user.jooq.tables.records.UserIdentityRecord;
import com.colombus.user.model.jooq.binding.AuthProviderBinding;
import com.colombus.user.model.type.AuthProvider;

import java.time.Instant;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.DefaultDataType;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.postgres.extensions.bindings.CitextBinding;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserIdentity extends TableImpl<UserIdentityRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.user_identity</code>
     */
    public static final UserIdentity USER_IDENTITY = new UserIdentity();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserIdentityRecord> getRecordType() {
        return UserIdentityRecord.class;
    }

    /**
     * The column <code>public.user_identity.id</code>.
     */
    public final TableField<UserIdentityRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.user_identity.user_id</code>.
     */
    public final TableField<UserIdentityRecord, UUID> USER_ID = createField(DSL.name("user_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.user_identity.provider</code>.
     */
    public final TableField<UserIdentityRecord, AuthProvider> PROVIDER = createField(DSL.name("provider"), DefaultDataType.getDefaultDataType("\"public\".\"auth_provider\"").nullable(false), this, "", new AuthProviderBinding());

    /**
     * The column <code>public.user_identity.provider_tenant</code>.
     */
    public final TableField<UserIdentityRecord, String> PROVIDER_TENANT = createField(DSL.name("provider_tenant"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.user_identity.provider_sub</code>.
     */
    public final TableField<UserIdentityRecord, String> PROVIDER_SUB = createField(DSL.name("provider_sub"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.user_identity.email_at_provider</code>.
     */
    public final TableField<UserIdentityRecord, String> EMAIL_AT_PROVIDER = createField(DSL.name("email_at_provider"), DefaultDataType.getDefaultDataType("\"public\".\"citext\""), this, "", new CitextBinding());

    /**
     * The column <code>public.user_identity.display_name_at_provider</code>.
     */
    public final TableField<UserIdentityRecord, String> DISPLAY_NAME_AT_PROVIDER = createField(DSL.name("display_name_at_provider"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.user_identity.last_sync_at</code>.
     */
    public final TableField<UserIdentityRecord, Instant> LAST_SYNC_AT = createField(DSL.name("last_sync_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "", new OffsetDateTimeToInstantConverter());

    /**
     * The column <code>public.user_identity.created_at</code>.
     */
    public final TableField<UserIdentityRecord, Instant> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "", new OffsetDateTimeToInstantConverter());

    /**
     * The column <code>public.user_identity.updated_at</code>.
     */
    public final TableField<UserIdentityRecord, Instant> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "", new OffsetDateTimeToInstantConverter());

    /**
     * The column <code>public.user_identity.deleted_at</code>.
     */
    public final TableField<UserIdentityRecord, Instant> DELETED_AT = createField(DSL.name("deleted_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "", new OffsetDateTimeToInstantConverter());

    private UserIdentity(Name alias, Table<UserIdentityRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private UserIdentity(Name alias, Table<UserIdentityRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.user_identity</code> table reference
     */
    public UserIdentity(String alias) {
        this(DSL.name(alias), USER_IDENTITY);
    }

    /**
     * Create an aliased <code>public.user_identity</code> table reference
     */
    public UserIdentity(Name alias) {
        this(alias, USER_IDENTITY);
    }

    /**
     * Create a <code>public.user_identity</code> table reference
     */
    public UserIdentity() {
        this(DSL.name("user_identity"), null);
    }

    public <O extends Record> UserIdentity(Table<O> path, ForeignKey<O, UserIdentityRecord> childPath, InverseForeignKey<O, UserIdentityRecord> parentPath) {
        super(path, childPath, parentPath, USER_IDENTITY);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class UserIdentityPath extends UserIdentity implements Path<UserIdentityRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> UserIdentityPath(Table<O> path, ForeignKey<O, UserIdentityRecord> childPath, InverseForeignKey<O, UserIdentityRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private UserIdentityPath(Name alias, Table<UserIdentityRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public UserIdentityPath as(String alias) {
            return new UserIdentityPath(DSL.name(alias), this);
        }

        @Override
        public UserIdentityPath as(Name alias) {
            return new UserIdentityPath(alias, this);
        }

        @Override
        public UserIdentityPath as(Table<?> alias) {
            return new UserIdentityPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_USER_IDENTITY_PROVIDER, Indexes.IDX_USER_IDENTITY_USER_ID, Indexes.UQ_IDENTITY_PROVIDER_TUPLE_ALIVE);
    }

    @Override
    public UniqueKey<UserIdentityRecord> getPrimaryKey() {
        return Keys.USER_IDENTITY_PKEY;
    }

    @Override
    public List<ForeignKey<UserIdentityRecord, ?>> getReferences() {
        return Arrays.asList(Keys.USER_IDENTITY__USER_IDENTITY_USER_ID_FKEY);
    }

    private transient UserAccountPath _userAccount;

    /**
     * Get the implicit join path to the <code>public.user_account</code> table.
     */
    public UserAccountPath userAccount() {
        if (_userAccount == null)
            _userAccount = new UserAccountPath(this, Keys.USER_IDENTITY__USER_IDENTITY_USER_ID_FKEY, null);

        return _userAccount;
    }

    @Override
    public TableField<UserIdentityRecord, Instant> getRecordTimestamp() {
        return UPDATED_AT;
    }

    @Override
    public UserIdentity as(String alias) {
        return new UserIdentity(DSL.name(alias), this);
    }

    @Override
    public UserIdentity as(Name alias) {
        return new UserIdentity(alias, this);
    }

    @Override
    public UserIdentity as(Table<?> alias) {
        return new UserIdentity(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserIdentity rename(String name) {
        return new UserIdentity(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserIdentity rename(Name name) {
        return new UserIdentity(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserIdentity rename(Table<?> name) {
        return new UserIdentity(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserIdentity where(Condition condition) {
        return new UserIdentity(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserIdentity where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserIdentity where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserIdentity where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserIdentity where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserIdentity where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserIdentity where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserIdentity where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserIdentity whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserIdentity whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
