/*
 * This file is generated by jOOQ.
 */
package com.colombus.snapshot.jooq;


import com.colombus.snapshot.jooq.tables.ChunkCompactionJob;
import com.colombus.snapshot.jooq.tables.ChunkIndex;
import com.colombus.snapshot.jooq.tables.ChunkMesh;
import com.colombus.snapshot.jooq.tables.ChunkSnapshot;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index IDX_CHUNK_INDEX_WORLD_GRID = Internal.createIndex(DSL.name("idx_chunk_index_world_grid"), ChunkIndex.CHUNK_INDEX, new OrderField[] { ChunkIndex.CHUNK_INDEX.WORLD_ID, ChunkIndex.CHUNK_INDEX.LOD, ChunkIndex.CHUNK_INDEX.TX, ChunkIndex.CHUNK_INDEX.TY, ChunkIndex.CHUNK_INDEX.IX, ChunkIndex.CHUNK_INDEX.IY, ChunkIndex.CHUNK_INDEX.IZ }, false);
    public static final Index IDX_CHUNK_MESH_CHUNK_DESC = Internal.createIndex(DSL.name("idx_chunk_mesh_chunk_desc"), ChunkMesh.CHUNK_MESH, new OrderField[] { ChunkMesh.CHUNK_MESH.CHUNK_ID, ChunkMesh.CHUNK_MESH.MESH_VERSION.desc() }, false);
    public static final Index IDX_CHUNK_SNAPSHOT_CHUNK_DESC = Internal.createIndex(DSL.name("idx_chunk_snapshot_chunk_desc"), ChunkSnapshot.CHUNK_SNAPSHOT, new OrderField[] { ChunkSnapshot.CHUNK_SNAPSHOT.CHUNK_ID, ChunkSnapshot.CHUNK_SNAPSHOT.VERSION.desc() }, false);
    public static final Index IDX_COMPACTION_CHUNK_STATUS = Internal.createIndex(DSL.name("idx_compaction_chunk_status"), ChunkCompactionJob.CHUNK_COMPACTION_JOB, new OrderField[] { ChunkCompactionJob.CHUNK_COMPACTION_JOB.CHUNK_ID, ChunkCompactionJob.CHUNK_COMPACTION_JOB.STATUS }, false);
}
