/*
 * This file is generated by jOOQ.
 */
package com.colombus.snapshot.jooq;


import com.colombus.snapshot.jooq.tables.ChunkCompactionJob;
import com.colombus.snapshot.jooq.tables.ChunkIndex;
import com.colombus.snapshot.jooq.tables.ChunkMesh;
import com.colombus.snapshot.jooq.tables.ChunkSnapshot;
import com.colombus.snapshot.jooq.tables.World;
import com.colombus.snapshot.jooq.tables.WorldLod;
import com.colombus.snapshot.jooq.tables.records.ChunkCompactionJobRecord;
import com.colombus.snapshot.jooq.tables.records.ChunkIndexRecord;
import com.colombus.snapshot.jooq.tables.records.ChunkMeshRecord;
import com.colombus.snapshot.jooq.tables.records.ChunkSnapshotRecord;
import com.colombus.snapshot.jooq.tables.records.WorldLodRecord;
import com.colombus.snapshot.jooq.tables.records.WorldRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.QOM.ForeignKeyRule;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ChunkCompactionJobRecord> CHUNK_COMPACTION_JOB_PKEY = Internal.createUniqueKey(ChunkCompactionJob.CHUNK_COMPACTION_JOB, DSL.name("chunk_compaction_job_pkey"), new TableField[] { ChunkCompactionJob.CHUNK_COMPACTION_JOB.UUID }, true);
    public static final UniqueKey<ChunkIndexRecord> CHUNK_INDEX_PKEY = Internal.createUniqueKey(ChunkIndex.CHUNK_INDEX, DSL.name("chunk_index_pkey"), new TableField[] { ChunkIndex.CHUNK_INDEX.UUID }, true);
    public static final UniqueKey<ChunkIndexRecord> CHUNK_INDEX_WORLD_ID_LOD_TX_TY_IX_IY_IZ_KEY = Internal.createUniqueKey(ChunkIndex.CHUNK_INDEX, DSL.name("chunk_index_world_id_lod_tx_ty_ix_iy_iz_key"), new TableField[] { ChunkIndex.CHUNK_INDEX.WORLD_ID, ChunkIndex.CHUNK_INDEX.LOD, ChunkIndex.CHUNK_INDEX.TX, ChunkIndex.CHUNK_INDEX.TY, ChunkIndex.CHUNK_INDEX.IX, ChunkIndex.CHUNK_INDEX.IY, ChunkIndex.CHUNK_INDEX.IZ }, true);
    public static final UniqueKey<ChunkMeshRecord> CHUNK_MESH_CHUNK_ID_MESH_VERSION_KEY = Internal.createUniqueKey(ChunkMesh.CHUNK_MESH, DSL.name("chunk_mesh_chunk_id_mesh_version_key"), new TableField[] { ChunkMesh.CHUNK_MESH.CHUNK_ID, ChunkMesh.CHUNK_MESH.MESH_VERSION }, true);
    public static final UniqueKey<ChunkMeshRecord> CHUNK_MESH_PKEY = Internal.createUniqueKey(ChunkMesh.CHUNK_MESH, DSL.name("chunk_mesh_pkey"), new TableField[] { ChunkMesh.CHUNK_MESH.UUID }, true);
    public static final UniqueKey<ChunkSnapshotRecord> CHUNK_SNAPSHOT_CHUNK_ID_VERSION_KEY = Internal.createUniqueKey(ChunkSnapshot.CHUNK_SNAPSHOT, DSL.name("chunk_snapshot_chunk_id_version_key"), new TableField[] { ChunkSnapshot.CHUNK_SNAPSHOT.CHUNK_ID, ChunkSnapshot.CHUNK_SNAPSHOT.VERSION }, true);
    public static final UniqueKey<ChunkSnapshotRecord> CHUNK_SNAPSHOT_PKEY = Internal.createUniqueKey(ChunkSnapshot.CHUNK_SNAPSHOT, DSL.name("chunk_snapshot_pkey"), new TableField[] { ChunkSnapshot.CHUNK_SNAPSHOT.UUID }, true);
    public static final UniqueKey<WorldRecord> WORLD_PKEY = Internal.createUniqueKey(World.WORLD, DSL.name("world_pkey"), new TableField[] { World.WORLD.UUID }, true);
    public static final UniqueKey<WorldLodRecord> WORLD_LOD_PKEY = Internal.createUniqueKey(WorldLod.WORLD_LOD, DSL.name("world_lod_pkey"), new TableField[] { WorldLod.WORLD_LOD.UUID }, true);
    public static final UniqueKey<WorldLodRecord> WORLD_LOD_WORLD_ID_LOD_KEY = Internal.createUniqueKey(WorldLod.WORLD_LOD, DSL.name("world_lod_world_id_lod_key"), new TableField[] { WorldLod.WORLD_LOD.WORLD_ID, WorldLod.WORLD_LOD.LOD }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<ChunkCompactionJobRecord, ChunkIndexRecord> CHUNK_COMPACTION_JOB__CHUNK_COMPACTION_JOB_CHUNK_ID_FKEY = Internal.createForeignKey(ChunkCompactionJob.CHUNK_COMPACTION_JOB, DSL.name("chunk_compaction_job_chunk_id_fkey"), new TableField[] { ChunkCompactionJob.CHUNK_COMPACTION_JOB.CHUNK_ID }, Keys.CHUNK_INDEX_PKEY, new TableField[] { ChunkIndex.CHUNK_INDEX.UUID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<ChunkIndexRecord, WorldRecord> CHUNK_INDEX__CHUNK_INDEX_WORLD_ID_FKEY = Internal.createForeignKey(ChunkIndex.CHUNK_INDEX, DSL.name("chunk_index_world_id_fkey"), new TableField[] { ChunkIndex.CHUNK_INDEX.WORLD_ID }, Keys.WORLD_PKEY, new TableField[] { World.WORLD.UUID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<ChunkMeshRecord, ChunkIndexRecord> CHUNK_MESH__CHUNK_MESH_CHUNK_ID_FKEY = Internal.createForeignKey(ChunkMesh.CHUNK_MESH, DSL.name("chunk_mesh_chunk_id_fkey"), new TableField[] { ChunkMesh.CHUNK_MESH.CHUNK_ID }, Keys.CHUNK_INDEX_PKEY, new TableField[] { ChunkIndex.CHUNK_INDEX.UUID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<ChunkMeshRecord, ChunkSnapshotRecord> CHUNK_MESH__CHUNK_MESH_SNAPSHOT_ID_FKEY = Internal.createForeignKey(ChunkMesh.CHUNK_MESH, DSL.name("chunk_mesh_snapshot_id_fkey"), new TableField[] { ChunkMesh.CHUNK_MESH.SNAPSHOT_ID }, Keys.CHUNK_SNAPSHOT_PKEY, new TableField[] { ChunkSnapshot.CHUNK_SNAPSHOT.UUID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<ChunkSnapshotRecord, ChunkIndexRecord> CHUNK_SNAPSHOT__CHUNK_SNAPSHOT_CHUNK_ID_FKEY = Internal.createForeignKey(ChunkSnapshot.CHUNK_SNAPSHOT, DSL.name("chunk_snapshot_chunk_id_fkey"), new TableField[] { ChunkSnapshot.CHUNK_SNAPSHOT.CHUNK_ID }, Keys.CHUNK_INDEX_PKEY, new TableField[] { ChunkIndex.CHUNK_INDEX.UUID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<WorldLodRecord, WorldRecord> WORLD_LOD__WORLD_LOD_WORLD_ID_FKEY = Internal.createForeignKey(WorldLod.WORLD_LOD, DSL.name("world_lod_world_id_fkey"), new TableField[] { WorldLod.WORLD_LOD.WORLD_ID }, Keys.WORLD_PKEY, new TableField[] { World.WORLD.UUID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
}
