/*
 * This file is generated by jOOQ.
 */
package com.colombus.snapshot.jooq;


import com.colombus.snapshot.jooq.tables.ChunkCompactionJob;
import com.colombus.snapshot.jooq.tables.ChunkIndex;
import com.colombus.snapshot.jooq.tables.ChunkMesh;
import com.colombus.snapshot.jooq.tables.ChunkSnapshot;
import com.colombus.snapshot.jooq.tables.World;
import com.colombus.snapshot.jooq.tables.WorldLod;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.DSL;
import org.jooq.impl.SchemaImpl;


/**
 * standard public schema
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.chunk_compaction_job</code>.
     */
    public final ChunkCompactionJob CHUNK_COMPACTION_JOB = ChunkCompactionJob.CHUNK_COMPACTION_JOB;

    /**
     * The table <code>public.chunk_index</code>.
     */
    public final ChunkIndex CHUNK_INDEX = ChunkIndex.CHUNK_INDEX;

    /**
     * The table <code>public.chunk_mesh</code>.
     */
    public final ChunkMesh CHUNK_MESH = ChunkMesh.CHUNK_MESH;

    /**
     * The table <code>public.chunk_snapshot</code>.
     */
    public final ChunkSnapshot CHUNK_SNAPSHOT = ChunkSnapshot.CHUNK_SNAPSHOT;

    /**
     * The table <code>public.world</code>.
     */
    public final World WORLD = World.WORLD;

    /**
     * The table <code>public.world_lod</code>.
     */
    public final WorldLod WORLD_LOD = WorldLod.WORLD_LOD;

    /**
     * No further instances allowed
     */
    private Public() {
        super(DSL.name("public"), null, DSL.comment("standard public schema"));
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            ChunkCompactionJob.CHUNK_COMPACTION_JOB,
            ChunkIndex.CHUNK_INDEX,
            ChunkMesh.CHUNK_MESH,
            ChunkSnapshot.CHUNK_SNAPSHOT,
            World.WORLD,
            WorldLod.WORLD_LOD
        );
    }
}
