/*
 * This file is generated by jOOQ.
 */
package com.colombus.snapshot.jooq;


import com.colombus.snapshot.jooq.tables.ChunkCompactionJob;
import com.colombus.snapshot.jooq.tables.ChunkIndex;
import com.colombus.snapshot.jooq.tables.ChunkMesh;
import com.colombus.snapshot.jooq.tables.ChunkSnapshot;
import com.colombus.snapshot.jooq.tables.World;
import com.colombus.snapshot.jooq.tables.WorldLod;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.chunk_compaction_job</code>.
     */
    public static final ChunkCompactionJob CHUNK_COMPACTION_JOB = ChunkCompactionJob.CHUNK_COMPACTION_JOB;

    /**
     * The table <code>public.chunk_index</code>.
     */
    public static final ChunkIndex CHUNK_INDEX = ChunkIndex.CHUNK_INDEX;

    /**
     * The table <code>public.chunk_mesh</code>.
     */
    public static final ChunkMesh CHUNK_MESH = ChunkMesh.CHUNK_MESH;

    /**
     * The table <code>public.chunk_snapshot</code>.
     */
    public static final ChunkSnapshot CHUNK_SNAPSHOT = ChunkSnapshot.CHUNK_SNAPSHOT;

    /**
     * The table <code>public.world</code>.
     */
    public static final World WORLD = World.WORLD;

    /**
     * The table <code>public.world_lod</code>.
     */
    public static final WorldLod WORLD_LOD = WorldLod.WORLD_LOD;
}
