/*
 * This file is generated by jOOQ.
 */
package com.colombus.clan.jooq;


import com.colombus.clan.jooq.tables.ClanInfo;
import com.colombus.clan.jooq.tables.ClanInviteTicket;
import com.colombus.clan.jooq.tables.ClanJoinRequest;
import com.colombus.clan.jooq.tables.ClanMember;
import com.colombus.clan.jooq.tables.OutboxEvent;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index IDX_CLAN_INVITE_TICKET_CLAN_ACTIVE = Internal.createIndex(DSL.name("idx_clan_invite_ticket_clan_active"), ClanInviteTicket.CLAN_INVITE_TICKET, new OrderField[] { ClanInviteTicket.CLAN_INVITE_TICKET.CLAN_ID, ClanInviteTicket.CLAN_INVITE_TICKET.EXPIRES_AT }, false);
    public static final Index IDX_CLAN_INVITE_TICKET_CODE = Internal.createIndex(DSL.name("idx_clan_invite_ticket_code"), ClanInviteTicket.CLAN_INVITE_TICKET, new OrderField[] { ClanInviteTicket.CLAN_INVITE_TICKET.CODE }, false);
    public static final Index IDX_CLAN_JOIN_REQUEST_CLAN = Internal.createIndex(DSL.name("idx_clan_join_request_clan"), ClanJoinRequest.CLAN_JOIN_REQUEST, new OrderField[] { ClanJoinRequest.CLAN_JOIN_REQUEST.CLAN_ID, ClanJoinRequest.CLAN_JOIN_REQUEST.STATUS }, false);
    public static final Index IDX_CLAN_JOIN_REQUEST_USER = Internal.createIndex(DSL.name("idx_clan_join_request_user"), ClanJoinRequest.CLAN_JOIN_REQUEST, new OrderField[] { ClanJoinRequest.CLAN_JOIN_REQUEST.USER_ID, ClanJoinRequest.CLAN_JOIN_REQUEST.STATUS }, false);
    public static final Index IDX_CLAN_MEMBER_CLAN_ACTIVE = Internal.createIndex(DSL.name("idx_clan_member_clan_active"), ClanMember.CLAN_MEMBER, new OrderField[] { ClanMember.CLAN_MEMBER.CLAN_ID }, false);
    public static final Index IDX_CLAN_MEMBER_USER_ACTIVE = Internal.createIndex(DSL.name("idx_clan_member_user_active"), ClanMember.CLAN_MEMBER, new OrderField[] { ClanMember.CLAN_MEMBER.USER_ID }, false);
    public static final Index IDX_CLAN_OWNER_ID_ACTIVE = Internal.createIndex(DSL.name("idx_clan_owner_id_active"), ClanInfo.CLAN_INFO, new OrderField[] { ClanInfo.CLAN_INFO.OWNER_ID }, false);
    public static final Index IDX_OUTBOX_CREATED = Internal.createIndex(DSL.name("idx_outbox_created"), OutboxEvent.OUTBOX_EVENT, new OrderField[] { OutboxEvent.OUTBOX_EVENT.CREATED_AT.desc() }, false);
    public static final Index UQ_CLAN_JOIN_REQUEST_PENDING = Internal.createIndex(DSL.name("uq_clan_join_request_pending"), ClanJoinRequest.CLAN_JOIN_REQUEST, new OrderField[] { ClanJoinRequest.CLAN_JOIN_REQUEST.CLAN_ID, ClanJoinRequest.CLAN_JOIN_REQUEST.USER_ID }, true);
    public static final Index UQ_CLAN_MEMBER_ACTIVE = Internal.createIndex(DSL.name("uq_clan_member_active"), ClanMember.CLAN_MEMBER, new OrderField[] { ClanMember.CLAN_MEMBER.CLAN_ID, ClanMember.CLAN_MEMBER.USER_ID }, true);
    public static final Index UQ_CLAN_MEMBER_ACTIVE_USER = Internal.createIndex(DSL.name("uq_clan_member_active_user"), ClanMember.CLAN_MEMBER, new OrderField[] { ClanMember.CLAN_MEMBER.USER_ID }, true);
    public static final Index UQ_OUTBOX_AGGREGATE_VERSION = Internal.createIndex(DSL.name("uq_outbox_aggregate_version"), OutboxEvent.OUTBOX_EVENT, new OrderField[] { OutboxEvent.OUTBOX_EVENT.AGGREGATE, OutboxEvent.OUTBOX_EVENT.AGGREGATE_ID, OutboxEvent.OUTBOX_EVENT.TYPE, OutboxEvent.OUTBOX_EVENT.VERSION }, true);
}
