/*
 * This file is generated by jOOQ.
 */
package com.colombus.clan.jooq;


import com.colombus.clan.jooq.tables.ClanInfo;
import com.colombus.clan.jooq.tables.ClanInviteTicket;
import com.colombus.clan.jooq.tables.ClanJoinRequest;
import com.colombus.clan.jooq.tables.ClanMember;
import com.colombus.clan.jooq.tables.OutboxEvent;
import com.colombus.clan.jooq.tables.records.ClanInfoRecord;
import com.colombus.clan.jooq.tables.records.ClanInviteTicketRecord;
import com.colombus.clan.jooq.tables.records.ClanJoinRequestRecord;
import com.colombus.clan.jooq.tables.records.ClanMemberRecord;
import com.colombus.clan.jooq.tables.records.OutboxEventRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.QOM.ForeignKeyRule;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ClanInfoRecord> CLAN_INFO_PKEY = Internal.createUniqueKey(ClanInfo.CLAN_INFO, DSL.name("clan_info_pkey"), new TableField[] { ClanInfo.CLAN_INFO.ID }, true);
    public static final UniqueKey<ClanInfoRecord> UQ_CLAN_HANDLE = Internal.createUniqueKey(ClanInfo.CLAN_INFO, DSL.name("uq_clan_handle"), new TableField[] { ClanInfo.CLAN_INFO.HANDLE }, true);
    public static final UniqueKey<ClanInviteTicketRecord> CLAN_INVITE_TICKET_PKEY = Internal.createUniqueKey(ClanInviteTicket.CLAN_INVITE_TICKET, DSL.name("clan_invite_ticket_pkey"), new TableField[] { ClanInviteTicket.CLAN_INVITE_TICKET.ID }, true);
    public static final UniqueKey<ClanInviteTicketRecord> UQ_CLAN_INVITE_TICKET_CODE = Internal.createUniqueKey(ClanInviteTicket.CLAN_INVITE_TICKET, DSL.name("uq_clan_invite_ticket_code"), new TableField[] { ClanInviteTicket.CLAN_INVITE_TICKET.CODE }, true);
    public static final UniqueKey<ClanJoinRequestRecord> CLAN_JOIN_REQUEST_PKEY = Internal.createUniqueKey(ClanJoinRequest.CLAN_JOIN_REQUEST, DSL.name("clan_join_request_pkey"), new TableField[] { ClanJoinRequest.CLAN_JOIN_REQUEST.ID }, true);
    public static final UniqueKey<ClanMemberRecord> CLAN_MEMBER_PKEY = Internal.createUniqueKey(ClanMember.CLAN_MEMBER, DSL.name("clan_member_pkey"), new TableField[] { ClanMember.CLAN_MEMBER.ID }, true);
    public static final UniqueKey<OutboxEventRecord> OUTBOX_EVENT_PKEY = Internal.createUniqueKey(OutboxEvent.OUTBOX_EVENT, DSL.name("outbox_event_pkey"), new TableField[] { OutboxEvent.OUTBOX_EVENT.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<ClanInviteTicketRecord, ClanInfoRecord> CLAN_INVITE_TICKET__FK_CLAN_INVITE_TICKET_CLAN = Internal.createForeignKey(ClanInviteTicket.CLAN_INVITE_TICKET, DSL.name("fk_clan_invite_ticket_clan"), new TableField[] { ClanInviteTicket.CLAN_INVITE_TICKET.CLAN_ID }, Keys.CLAN_INFO_PKEY, new TableField[] { ClanInfo.CLAN_INFO.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<ClanJoinRequestRecord, ClanInfoRecord> CLAN_JOIN_REQUEST__FK_CLAN_JOIN_REQUEST_CLAN = Internal.createForeignKey(ClanJoinRequest.CLAN_JOIN_REQUEST, DSL.name("fk_clan_join_request_clan"), new TableField[] { ClanJoinRequest.CLAN_JOIN_REQUEST.CLAN_ID }, Keys.CLAN_INFO_PKEY, new TableField[] { ClanInfo.CLAN_INFO.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<ClanMemberRecord, ClanInfoRecord> CLAN_MEMBER__FK_CLAN_MEMBER_CLAN = Internal.createForeignKey(ClanMember.CLAN_MEMBER, DSL.name("fk_clan_member_clan"), new TableField[] { ClanMember.CLAN_MEMBER.CLAN_ID }, Keys.CLAN_INFO_PKEY, new TableField[] { ClanInfo.CLAN_INFO.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
}
