/*
 * This file is generated by jOOQ.
 */
package com.colombus.clan.jooq;


import com.colombus.clan.jooq.tables.ClanInfo;
import com.colombus.clan.jooq.tables.ClanInviteTicket;
import com.colombus.clan.jooq.tables.ClanJoinRequest;
import com.colombus.clan.jooq.tables.ClanMember;
import com.colombus.clan.jooq.tables.OutboxEvent;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.DSL;
import org.jooq.impl.SchemaImpl;


/**
 * standard public schema
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.clan_info</code>.
     */
    public final ClanInfo CLAN_INFO = ClanInfo.CLAN_INFO;

    /**
     * The table <code>public.clan_invite_ticket</code>.
     */
    public final ClanInviteTicket CLAN_INVITE_TICKET = ClanInviteTicket.CLAN_INVITE_TICKET;

    /**
     * The table <code>public.clan_join_request</code>.
     */
    public final ClanJoinRequest CLAN_JOIN_REQUEST = ClanJoinRequest.CLAN_JOIN_REQUEST;

    /**
     * The table <code>public.clan_member</code>.
     */
    public final ClanMember CLAN_MEMBER = ClanMember.CLAN_MEMBER;

    /**
     * The table <code>public.outbox_event</code>.
     */
    public final OutboxEvent OUTBOX_EVENT = OutboxEvent.OUTBOX_EVENT;

    /**
     * No further instances allowed
     */
    private Public() {
        super(DSL.name("public"), null, DSL.comment("standard public schema"));
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            ClanInfo.CLAN_INFO,
            ClanInviteTicket.CLAN_INVITE_TICKET,
            ClanJoinRequest.CLAN_JOIN_REQUEST,
            ClanMember.CLAN_MEMBER,
            OutboxEvent.OUTBOX_EVENT
        );
    }
}
