/*
 * This file is generated by jOOQ.
 */
package com.colombus.clan.jooq;


import com.colombus.clan.jooq.tables.ClanInfo;
import com.colombus.clan.jooq.tables.ClanInviteTicket;
import com.colombus.clan.jooq.tables.ClanJoinRequest;
import com.colombus.clan.jooq.tables.ClanMember;
import com.colombus.clan.jooq.tables.OutboxEvent;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.clan_info</code>.
     */
    public static final ClanInfo CLAN_INFO = ClanInfo.CLAN_INFO;

    /**
     * The table <code>public.clan_invite_ticket</code>.
     */
    public static final ClanInviteTicket CLAN_INVITE_TICKET = ClanInviteTicket.CLAN_INVITE_TICKET;

    /**
     * The table <code>public.clan_join_request</code>.
     */
    public static final ClanJoinRequest CLAN_JOIN_REQUEST = ClanJoinRequest.CLAN_JOIN_REQUEST;

    /**
     * The table <code>public.clan_member</code>.
     */
    public static final ClanMember CLAN_MEMBER = ClanMember.CLAN_MEMBER;

    /**
     * The table <code>public.outbox_event</code>.
     */
    public static final OutboxEvent OUTBOX_EVENT = OutboxEvent.OUTBOX_EVENT;
}
