/*
 * This file is generated by jOOQ.
 */
package com.colombus.snapshot.jooq.tables.records;


import com.colombus.snapshot.jooq.tables.ChunkCompactionJob;
import com.colombus.snapshot.model.type.CompactionStatus;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ChunkCompactionJobRecord extends UpdatableRecordImpl<ChunkCompactionJobRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.chunk_compaction_job.uuid</code>.
     */
    public void setUuid(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.chunk_compaction_job.uuid</code>.
     */
    public UUID getUuid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.chunk_compaction_job.chunk_id</code>.
     */
    public void setChunkId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.chunk_compaction_job.chunk_id</code>.
     */
    public UUID getChunkId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.chunk_compaction_job.from_version</code>.
     */
    public void setFromVersion(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.chunk_compaction_job.from_version</code>.
     */
    public Long getFromVersion() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.chunk_compaction_job.to_version</code>.
     */
    public void setToVersion(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.chunk_compaction_job.to_version</code>.
     */
    public Long getToVersion() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.chunk_compaction_job.status</code>.
     */
    public void setStatus(CompactionStatus value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.chunk_compaction_job.status</code>.
     */
    public CompactionStatus getStatus() {
        return (CompactionStatus) get(4);
    }

    /**
     * Setter for <code>public.chunk_compaction_job.started_at</code>.
     */
    public void setStartedAt(OffsetDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.chunk_compaction_job.started_at</code>.
     */
    public OffsetDateTime getStartedAt() {
        return (OffsetDateTime) get(5);
    }

    /**
     * Setter for <code>public.chunk_compaction_job.finished_at</code>.
     */
    public void setFinishedAt(OffsetDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.chunk_compaction_job.finished_at</code>.
     */
    public OffsetDateTime getFinishedAt() {
        return (OffsetDateTime) get(6);
    }

    /**
     * Setter for <code>public.chunk_compaction_job.stats</code>.
     */
    public void setStats(JSONB value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.chunk_compaction_job.stats</code>.
     */
    public JSONB getStats() {
        return (JSONB) get(7);
    }

    /**
     * Setter for <code>public.chunk_compaction_job.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.chunk_compaction_job.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(8);
    }

    /**
     * Setter for <code>public.chunk_compaction_job.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.chunk_compaction_job.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(9);
    }

    /**
     * Setter for <code>public.chunk_compaction_job.deleted_at</code>.
     */
    public void setDeletedAt(OffsetDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.chunk_compaction_job.deleted_at</code>.
     */
    public OffsetDateTime getDeletedAt() {
        return (OffsetDateTime) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ChunkCompactionJobRecord
     */
    public ChunkCompactionJobRecord() {
        super(ChunkCompactionJob.CHUNK_COMPACTION_JOB);
    }

    /**
     * Create a detached, initialised ChunkCompactionJobRecord
     */
    public ChunkCompactionJobRecord(UUID uuid, UUID chunkId, Long fromVersion, Long toVersion, CompactionStatus status, OffsetDateTime startedAt, OffsetDateTime finishedAt, JSONB stats, OffsetDateTime createdAt, OffsetDateTime updatedAt, OffsetDateTime deletedAt) {
        super(ChunkCompactionJob.CHUNK_COMPACTION_JOB);

        setUuid(uuid);
        setChunkId(chunkId);
        setFromVersion(fromVersion);
        setToVersion(toVersion);
        setStatus(status);
        setStartedAt(startedAt);
        setFinishedAt(finishedAt);
        setStats(stats);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setDeletedAt(deletedAt);
        resetTouchedOnNotNull();
    }
}
