/*
 * This file is generated by jOOQ.
 */
package com.colombus.snapshot.jooq.tables.records;


import com.colombus.snapshot.jooq.tables.ChunkMesh;
import com.colombus.snapshot.model.type.ArtifactKind;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ChunkMeshRecord extends UpdatableRecordImpl<ChunkMeshRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.chunk_mesh.uuid</code>.
     */
    public void setUuid(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.chunk_mesh.uuid</code>.
     */
    public UUID getUuid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.chunk_mesh.chunk_id</code>.
     */
    public void setChunkId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.chunk_mesh.chunk_id</code>.
     */
    public UUID getChunkId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.chunk_mesh.snapshot_id</code>.
     */
    public void setSnapshotId(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.chunk_mesh.snapshot_id</code>.
     */
    public UUID getSnapshotId() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>public.chunk_mesh.mesh_version</code>.
     */
    public void setMeshVersion(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.chunk_mesh.mesh_version</code>.
     */
    public Long getMeshVersion() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.chunk_mesh.artifact_uri</code>.
     */
    public void setArtifactUri(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.chunk_mesh.artifact_uri</code>.
     */
    public String getArtifactUri() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.chunk_mesh.artifact_kind</code>.
     */
    public void setArtifactKind(ArtifactKind value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.chunk_mesh.artifact_kind</code>.
     */
    public ArtifactKind getArtifactKind() {
        return (ArtifactKind) get(5);
    }

    /**
     * Setter for <code>public.chunk_mesh.tri_count</code>.
     */
    public void setTriCount(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.chunk_mesh.tri_count</code>.
     */
    public Long getTriCount() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>public.chunk_mesh.vertex_count</code>.
     */
    public void setVertexCount(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.chunk_mesh.vertex_count</code>.
     */
    public Long getVertexCount() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>public.chunk_mesh.compressed_bytes</code>.
     */
    public void setCompressedBytes(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.chunk_mesh.compressed_bytes</code>.
     */
    public Integer getCompressedBytes() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>public.chunk_mesh.checksum_sha256</code>.
     */
    public void setChecksumSha256(byte[] value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.chunk_mesh.checksum_sha256</code>.
     */
    public byte[] getChecksumSha256() {
        return (byte[]) get(9);
    }

    /**
     * Setter for <code>public.chunk_mesh.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.chunk_mesh.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(10);
    }

    /**
     * Setter for <code>public.chunk_mesh.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.chunk_mesh.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(11);
    }

    /**
     * Setter for <code>public.chunk_mesh.deleted_at</code>.
     */
    public void setDeletedAt(OffsetDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.chunk_mesh.deleted_at</code>.
     */
    public OffsetDateTime getDeletedAt() {
        return (OffsetDateTime) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ChunkMeshRecord
     */
    public ChunkMeshRecord() {
        super(ChunkMesh.CHUNK_MESH);
    }

    /**
     * Create a detached, initialised ChunkMeshRecord
     */
    public ChunkMeshRecord(UUID uuid, UUID chunkId, UUID snapshotId, Long meshVersion, String artifactUri, ArtifactKind artifactKind, Long triCount, Long vertexCount, Integer compressedBytes, byte[] checksumSha256, OffsetDateTime createdAt, OffsetDateTime updatedAt, OffsetDateTime deletedAt) {
        super(ChunkMesh.CHUNK_MESH);

        setUuid(uuid);
        setChunkId(chunkId);
        setSnapshotId(snapshotId);
        setMeshVersion(meshVersion);
        setArtifactUri(artifactUri);
        setArtifactKind(artifactKind);
        setTriCount(triCount);
        setVertexCount(vertexCount);
        setCompressedBytes(compressedBytes);
        setChecksumSha256(checksumSha256);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setDeletedAt(deletedAt);
        resetTouchedOnNotNull();
    }
}
