/*
 * This file is generated by jOOQ.
 */
package com.colombus.snapshot.jooq.tables.records;


import com.colombus.snapshot.jooq.tables.ChunkIndex;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ChunkIndexRecord extends UpdatableRecordImpl<ChunkIndexRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.chunk_index.uuid</code>.
     */
    public void setUuid(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.chunk_index.uuid</code>.
     */
    public UUID getUuid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.chunk_index.world_id</code>.
     */
    public void setWorldId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.chunk_index.world_id</code>.
     */
    public UUID getWorldId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.chunk_index.lod</code>.
     */
    public void setLod(Short value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.chunk_index.lod</code>.
     */
    public Short getLod() {
        return (Short) get(2);
    }

    /**
     * Setter for <code>public.chunk_index.tx</code>.
     */
    public void setTx(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.chunk_index.tx</code>.
     */
    public Integer getTx() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.chunk_index.ty</code>.
     */
    public void setTy(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.chunk_index.ty</code>.
     */
    public Integer getTy() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.chunk_index.ix</code>.
     */
    public void setIx(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.chunk_index.ix</code>.
     */
    public Integer getIx() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.chunk_index.iy</code>.
     */
    public void setIy(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.chunk_index.iy</code>.
     */
    public Integer getIy() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.chunk_index.iz</code>.
     */
    public void setIz(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.chunk_index.iz</code>.
     */
    public Integer getIz() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>public.chunk_index.edge_cells</code>.
     */
    public void setEdgeCells(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.chunk_index.edge_cells</code>.
     */
    public Integer getEdgeCells() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>public.chunk_index.voxel_size_m</code>.
     */
    public void setVoxelSizeM(Double value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.chunk_index.voxel_size_m</code>.
     */
    public Double getVoxelSizeM() {
        return (Double) get(9);
    }

    /**
     * Setter for <code>public.chunk_index.aabb_min_x</code>.
     */
    public void setAabbMinX(Double value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.chunk_index.aabb_min_x</code>.
     */
    public Double getAabbMinX() {
        return (Double) get(10);
    }

    /**
     * Setter for <code>public.chunk_index.aabb_min_y</code>.
     */
    public void setAabbMinY(Double value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.chunk_index.aabb_min_y</code>.
     */
    public Double getAabbMinY() {
        return (Double) get(11);
    }

    /**
     * Setter for <code>public.chunk_index.aabb_min_z</code>.
     */
    public void setAabbMinZ(Double value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.chunk_index.aabb_min_z</code>.
     */
    public Double getAabbMinZ() {
        return (Double) get(12);
    }

    /**
     * Setter for <code>public.chunk_index.aabb_max_x</code>.
     */
    public void setAabbMaxX(Double value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.chunk_index.aabb_max_x</code>.
     */
    public Double getAabbMaxX() {
        return (Double) get(13);
    }

    /**
     * Setter for <code>public.chunk_index.aabb_max_y</code>.
     */
    public void setAabbMaxY(Double value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.chunk_index.aabb_max_y</code>.
     */
    public Double getAabbMaxY() {
        return (Double) get(14);
    }

    /**
     * Setter for <code>public.chunk_index.aabb_max_z</code>.
     */
    public void setAabbMaxZ(Double value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.chunk_index.aabb_max_z</code>.
     */
    public Double getAabbMaxZ() {
        return (Double) get(15);
    }

    /**
     * Setter for <code>public.chunk_index.current_snapshot_id</code>.
     */
    public void setCurrentSnapshotId(UUID value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.chunk_index.current_snapshot_id</code>.
     */
    public UUID getCurrentSnapshotId() {
        return (UUID) get(16);
    }

    /**
     * Setter for <code>public.chunk_index.current_mesh_id</code>.
     */
    public void setCurrentMeshId(UUID value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.chunk_index.current_mesh_id</code>.
     */
    public UUID getCurrentMeshId() {
        return (UUID) get(17);
    }

    /**
     * Setter for <code>public.chunk_index.current_version</code>.
     */
    public void setCurrentVersion(Long value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.chunk_index.current_version</code>.
     */
    public Long getCurrentVersion() {
        return (Long) get(18);
    }

    /**
     * Setter for <code>public.chunk_index.current_mesh_version</code>.
     */
    public void setCurrentMeshVersion(Long value) {
        set(19, value);
    }

    /**
     * Getter for <code>public.chunk_index.current_mesh_version</code>.
     */
    public Long getCurrentMeshVersion() {
        return (Long) get(19);
    }

    /**
     * Setter for <code>public.chunk_index.last_write_at</code>.
     */
    public void setLastWriteAt(OffsetDateTime value) {
        set(20, value);
    }

    /**
     * Getter for <code>public.chunk_index.last_write_at</code>.
     */
    public OffsetDateTime getLastWriteAt() {
        return (OffsetDateTime) get(20);
    }

    /**
     * Setter for <code>public.chunk_index.last_compacted_at</code>.
     */
    public void setLastCompactedAt(OffsetDateTime value) {
        set(21, value);
    }

    /**
     * Getter for <code>public.chunk_index.last_compacted_at</code>.
     */
    public OffsetDateTime getLastCompactedAt() {
        return (OffsetDateTime) get(21);
    }

    /**
     * Setter for <code>public.chunk_index.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(22, value);
    }

    /**
     * Getter for <code>public.chunk_index.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(22);
    }

    /**
     * Setter for <code>public.chunk_index.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(23, value);
    }

    /**
     * Getter for <code>public.chunk_index.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(23);
    }

    /**
     * Setter for <code>public.chunk_index.deleted_at</code>.
     */
    public void setDeletedAt(OffsetDateTime value) {
        set(24, value);
    }

    /**
     * Getter for <code>public.chunk_index.deleted_at</code>.
     */
    public OffsetDateTime getDeletedAt() {
        return (OffsetDateTime) get(24);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ChunkIndexRecord
     */
    public ChunkIndexRecord() {
        super(ChunkIndex.CHUNK_INDEX);
    }

    /**
     * Create a detached, initialised ChunkIndexRecord
     */
    public ChunkIndexRecord(UUID uuid, UUID worldId, Short lod, Integer tx, Integer ty, Integer ix, Integer iy, Integer iz, Integer edgeCells, Double voxelSizeM, Double aabbMinX, Double aabbMinY, Double aabbMinZ, Double aabbMaxX, Double aabbMaxY, Double aabbMaxZ, UUID currentSnapshotId, UUID currentMeshId, Long currentVersion, Long currentMeshVersion, OffsetDateTime lastWriteAt, OffsetDateTime lastCompactedAt, OffsetDateTime createdAt, OffsetDateTime updatedAt, OffsetDateTime deletedAt) {
        super(ChunkIndex.CHUNK_INDEX);

        setUuid(uuid);
        setWorldId(worldId);
        setLod(lod);
        setTx(tx);
        setTy(ty);
        setIx(ix);
        setIy(iy);
        setIz(iz);
        setEdgeCells(edgeCells);
        setVoxelSizeM(voxelSizeM);
        setAabbMinX(aabbMinX);
        setAabbMinY(aabbMinY);
        setAabbMinZ(aabbMinZ);
        setAabbMaxX(aabbMaxX);
        setAabbMaxY(aabbMaxY);
        setAabbMaxZ(aabbMaxZ);
        setCurrentSnapshotId(currentSnapshotId);
        setCurrentMeshId(currentMeshId);
        setCurrentVersion(currentVersion);
        setCurrentMeshVersion(currentMeshVersion);
        setLastWriteAt(lastWriteAt);
        setLastCompactedAt(lastCompactedAt);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setDeletedAt(deletedAt);
        resetTouchedOnNotNull();
    }
}
