/*
 * This file is generated by jOOQ.
 */
package com.colombus.snapshot.jooq.tables.records;


import com.colombus.snapshot.jooq.tables.ChunkSnapshot;
import com.colombus.snapshot.model.type.SnapshotKind;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ChunkSnapshotRecord extends UpdatableRecordImpl<ChunkSnapshotRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.chunk_snapshot.uuid</code>.
     */
    public void setUuid(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.chunk_snapshot.uuid</code>.
     */
    public UUID getUuid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.chunk_snapshot.chunk_id</code>.
     */
    public void setChunkId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.chunk_snapshot.chunk_id</code>.
     */
    public UUID getChunkId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.chunk_snapshot.version</code>.
     */
    public void setVersion(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.chunk_snapshot.version</code>.
     */
    public Long getVersion() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.chunk_snapshot.schema_version</code>.
     */
    public void setSchemaVersion(Short value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.chunk_snapshot.schema_version</code>.
     */
    public Short getSchemaVersion() {
        return (Short) get(3);
    }

    /**
     * Setter for <code>public.chunk_snapshot.storage_uri</code>.
     */
    public void setStorageUri(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.chunk_snapshot.storage_uri</code>.
     */
    public String getStorageUri() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.chunk_snapshot.payload</code>.
     */
    public void setPayload(JSONB value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.chunk_snapshot.payload</code>.
     */
    public JSONB getPayload() {
        return (JSONB) get(5);
    }

    /**
     * Setter for <code>public.chunk_snapshot.snapshot_kind</code>.
     */
    public void setSnapshotKind(SnapshotKind value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.chunk_snapshot.snapshot_kind</code>.
     */
    public SnapshotKind getSnapshotKind() {
        return (SnapshotKind) get(6);
    }

    /**
     * Setter for <code>public.chunk_snapshot.non_empty_cells</code>.
     */
    public void setNonEmptyCells(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.chunk_snapshot.non_empty_cells</code>.
     */
    public Integer getNonEmptyCells() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>public.chunk_snapshot.compressed_bytes</code>.
     */
    public void setCompressedBytes(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.chunk_snapshot.compressed_bytes</code>.
     */
    public Integer getCompressedBytes() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>public.chunk_snapshot.checksum_sha256</code>.
     */
    public void setChecksumSha256(byte[] value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.chunk_snapshot.checksum_sha256</code>.
     */
    public byte[] getChecksumSha256() {
        return (byte[]) get(9);
    }

    /**
     * Setter for <code>public.chunk_snapshot.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.chunk_snapshot.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(10);
    }

    /**
     * Setter for <code>public.chunk_snapshot.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.chunk_snapshot.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(11);
    }

    /**
     * Setter for <code>public.chunk_snapshot.deleted_at</code>.
     */
    public void setDeletedAt(OffsetDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.chunk_snapshot.deleted_at</code>.
     */
    public OffsetDateTime getDeletedAt() {
        return (OffsetDateTime) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ChunkSnapshotRecord
     */
    public ChunkSnapshotRecord() {
        super(ChunkSnapshot.CHUNK_SNAPSHOT);
    }

    /**
     * Create a detached, initialised ChunkSnapshotRecord
     */
    public ChunkSnapshotRecord(UUID uuid, UUID chunkId, Long version, Short schemaVersion, String storageUri, JSONB payload, SnapshotKind snapshotKind, Integer nonEmptyCells, Integer compressedBytes, byte[] checksumSha256, OffsetDateTime createdAt, OffsetDateTime updatedAt, OffsetDateTime deletedAt) {
        super(ChunkSnapshot.CHUNK_SNAPSHOT);

        setUuid(uuid);
        setChunkId(chunkId);
        setVersion(version);
        setSchemaVersion(schemaVersion);
        setStorageUri(storageUri);
        setPayload(payload);
        setSnapshotKind(snapshotKind);
        setNonEmptyCells(nonEmptyCells);
        setCompressedBytes(compressedBytes);
        setChecksumSha256(checksumSha256);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setDeletedAt(deletedAt);
        resetTouchedOnNotNull();
    }
}
