/*
 * This file is generated by jOOQ.
 */
package com.colombus.snapshot.jooq.tables.records;


import com.colombus.snapshot.jooq.tables.World;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WorldRecord extends UpdatableRecordImpl<WorldRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.world.uuid</code>.
     */
    public void setUuid(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.world.uuid</code>.
     */
    public UUID getUuid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.world.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.world.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.world.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.world.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.world.origin_x_ecef</code>.
     */
    public void setOriginXEcef(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.world.origin_x_ecef</code>.
     */
    public Double getOriginXEcef() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>public.world.origin_y_ecef</code>.
     */
    public void setOriginYEcef(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.world.origin_y_ecef</code>.
     */
    public Double getOriginYEcef() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>public.world.origin_z_ecef</code>.
     */
    public void setOriginZEcef(Double value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.world.origin_z_ecef</code>.
     */
    public Double getOriginZEcef() {
        return (Double) get(5);
    }

    /**
     * Setter for <code>public.world.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.world.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(6);
    }

    /**
     * Setter for <code>public.world.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.world.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(7);
    }

    /**
     * Setter for <code>public.world.deleted_at</code>.
     */
    public void setDeletedAt(OffsetDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.world.deleted_at</code>.
     */
    public OffsetDateTime getDeletedAt() {
        return (OffsetDateTime) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WorldRecord
     */
    public WorldRecord() {
        super(World.WORLD);
    }

    /**
     * Create a detached, initialised WorldRecord
     */
    public WorldRecord(UUID uuid, String name, String description, Double originXEcef, Double originYEcef, Double originZEcef, OffsetDateTime createdAt, OffsetDateTime updatedAt, OffsetDateTime deletedAt) {
        super(World.WORLD);

        setUuid(uuid);
        setName(name);
        setDescription(description);
        setOriginXEcef(originXEcef);
        setOriginYEcef(originYEcef);
        setOriginZEcef(originZEcef);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setDeletedAt(deletedAt);
        resetTouchedOnNotNull();
    }
}
