/*
 * This file is generated by jOOQ.
 */
package com.colombus.snapshot.jooq.tables.records;


import com.colombus.snapshot.jooq.tables.WorldLod;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class WorldLodRecord extends UpdatableRecordImpl<WorldLodRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.world_lod.uuid</code>.
     */
    public void setUuid(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.world_lod.uuid</code>.
     */
    public UUID getUuid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.world_lod.world_id</code>.
     */
    public void setWorldId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.world_lod.world_id</code>.
     */
    public UUID getWorldId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.world_lod.lod</code>.
     */
    public void setLod(Short value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.world_lod.lod</code>.
     */
    public Short getLod() {
        return (Short) get(2);
    }

    /**
     * Setter for <code>public.world_lod.chunk_edge_cells</code>.
     */
    public void setChunkEdgeCells(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.world_lod.chunk_edge_cells</code>.
     */
    public Integer getChunkEdgeCells() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.world_lod.voxel_size_m</code>.
     */
    public void setVoxelSizeM(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.world_lod.voxel_size_m</code>.
     */
    public Double getVoxelSizeM() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>public.world_lod.morton_order</code>.
     */
    public void setMortonOrder(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.world_lod.morton_order</code>.
     */
    public Boolean getMortonOrder() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>public.world_lod.lod_meta</code>.
     */
    public void setLodMeta(JSONB value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.world_lod.lod_meta</code>.
     */
    public JSONB getLodMeta() {
        return (JSONB) get(6);
    }

    /**
     * Setter for <code>public.world_lod.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.world_lod.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(7);
    }

    /**
     * Setter for <code>public.world_lod.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.world_lod.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(8);
    }

    /**
     * Setter for <code>public.world_lod.deleted_at</code>.
     */
    public void setDeletedAt(OffsetDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.world_lod.deleted_at</code>.
     */
    public OffsetDateTime getDeletedAt() {
        return (OffsetDateTime) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WorldLodRecord
     */
    public WorldLodRecord() {
        super(WorldLod.WORLD_LOD);
    }

    /**
     * Create a detached, initialised WorldLodRecord
     */
    public WorldLodRecord(UUID uuid, UUID worldId, Short lod, Integer chunkEdgeCells, Double voxelSizeM, Boolean mortonOrder, JSONB lodMeta, OffsetDateTime createdAt, OffsetDateTime updatedAt, OffsetDateTime deletedAt) {
        super(WorldLod.WORLD_LOD);

        setUuid(uuid);
        setWorldId(worldId);
        setLod(lod);
        setChunkEdgeCells(chunkEdgeCells);
        setVoxelSizeM(voxelSizeM);
        setMortonOrder(mortonOrder);
        setLodMeta(lodMeta);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setDeletedAt(deletedAt);
        resetTouchedOnNotNull();
    }
}
